def _a(title, category, summary, body):
    return {"title": title, "category": category, "summary": summary, "content": body}


ARTICLES = [
    # ---------- FOCUS ----------
    _a("The Pomodoro Technique for Medical Study", "focus",
       "Use 25-minute focused blocks with 5-minute breaks to sustain attention across long study days.",
       "<p>The Pomodoro technique splits study into 25-minute focused intervals separated by 5-minute breaks, with a longer 20-30 minute break after four cycles.</p><p>For AMC preparation, attach each pomodoro to one concrete deliverable: one guideline topic card, ten MCQs, or one recall theme. Avoid passive re-reading — every block should end with something you produced (notes, flashcards, answered questions).</p><p>Track completed pomodoros daily. Most candidates sustain 8-12 high-quality blocks per day; more than that usually means quality is dropping.</p>"),
    _a("Deep Work: Protecting Your Best Hours", "focus",
       "Schedule your hardest material during your biological peak hours and defend them from interruptions.",
       "<p>Identify your two or three peak-alertness hours (commonly mid-morning). Reserve them for the hardest cognitive work — new topics, weak subjects, mixed MCQ blocks under timed conditions.</p><p>Push administrative tasks (organising notes, scheduling) into low-energy slots. Put your phone in another room; even a silent visible phone measurably reduces working memory capacity.</p>"),
    _a("Single-Tasking Beats Multitasking", "focus",
       "Task-switching costs can consume up to 40% of productive time. Study one subject per block.",
       "<p>Every switch between subjects or apps incurs a re-orientation cost. Batch similar work: do all your paediatrics MCQs in one block rather than alternating with messages or email.</p><p>Use a 'distraction sheet' — when an unrelated thought intrudes, write it down and return to it after the block ends.</p>"),
    _a("Designing a Distraction-Free Study Environment", "focus",
       "Your environment determines your default behaviour. Engineer it so studying is the path of least resistance.",
       "<p>Keep a dedicated study space used only for study. Pre-stage materials the night before so starting takes less than 60 seconds. Use website blockers during study hours.</p><p>Ambient noise around 50-60 dB (library hum, rain sounds) supports concentration for most people; lyrical music competes with verbal memory and harms retention of written material.</p>"),
    _a("Active Recall Over Re-Reading", "focus",
       "Testing yourself is the highest-yield study activity; re-reading creates familiarity without retention.",
       "<p>Close the book and write down everything you remember about a topic, then check against the guideline. Use the platform's flashcards and MCQ bank as your primary loop, not as an afterthought.</p><p>Aim for a 3:1 ratio of retrieval practice to new input in the final eight weeks before the exam.</p>"),

    # ---------- STRESS ----------
    _a("Box Breathing for Exam Anxiety", "stress",
       "A 4-4-4-4 breathing pattern downregulates the sympathetic nervous system in under two minutes.",
       "<p>Inhale for 4 seconds, hold for 4, exhale for 4, hold for 4. Repeat for 4-6 cycles. Use it before mock exams, between difficult MCQ blocks, and on exam morning.</p><p>Physiological sigh (double inhale through the nose, long exhale through the mouth) works even faster when you feel acute panic rising mid-exam.</p>"),
    _a("Cognitive Reframing of Exam Pressure", "stress",
       "Re-interpret arousal as readiness: the same physiology underlies anxiety and peak performance.",
       "<p>Telling yourself 'I am excited' rather than 'calm down' improves performance because it works with, not against, the arousal already present.</p><p>Write down your worst-case scenario and a realistic plan for it once — most exam anxiety is amplified by avoidance, not by the actual stakes.</p>"),
    _a("The Worry Window Technique", "stress",
       "Contain rumination to a scheduled 15-minute daily slot to free the rest of the day.",
       "<p>Pick a fixed daily 15-minute 'worry window'. When intrusive worries appear during study, note them on paper and defer them to the window. At the window, problem-solve on paper: what can I control, what is the next action?</p><p>Most deferred worries lose their charge before the window arrives.</p>"),
    _a("Recognising Burnout Early", "stress",
       "Exhaustion, cynicism, and falling efficacy are the three signatures — catch them before they compound.",
       "<p>Warning signs: dreading study you previously tolerated, declining MCQ scores despite more hours, irritability, sleep disruption, and emotional numbness.</p><p>The fix is rarely 'push harder'. Reduce volume by 30% for one week, reintroduce exercise and social contact, and rebuild from a sustainable baseline. One recovered week beats three depleted ones.</p>"),
    _a("Social Support During Long Preparation", "stress",
       "Isolation magnifies stress. Structured peer contact improves both wellbeing and retention.",
       "<p>Join or form a small study group (2-4 people) meeting twice weekly — teaching a topic aloud is among the strongest retention techniques known.</p><p>Tell family and friends your exam date and your weekly schedule so support is informed, not intrusive.</p>"),

    # ---------- SLEEP ----------
    _a("Sleep Is a Study Strategy", "sleep",
       "Memory consolidation happens during sleep; sacrificing it for extra hours is a net loss.",
       "<p>Declarative memory (facts, criteria, drug doses) consolidates during deep slow-wave sleep early in the night; procedural and integrative learning consolidates during REM later in the night. Cutting sleep from 8 to 6 hours disproportionately cuts REM.</p><p>Candidates who protect 7.5-8 hours consistently outperform those who trade sleep for extra study time over any horizon longer than a few days.</p>"),
    _a("A Wind-Down Routine That Works", "sleep",
       "A consistent 30-minute pre-sleep routine signals the brain to disengage from study mode.",
       "<p>Stop screens and MCQs 30-60 minutes before bed. Light stretching, a shower, and reviewing tomorrow's plan on paper all work. Keep the bedroom cool (18-19°C) and dark.</p><p>If you must study late, end with passive review (reading notes) rather than timed questions, which spike arousal.</p>"),
    _a("Caffeine: Dose and Timing", "sleep",
       "Caffeine has a 5-6 hour half-life — the afternoon coffee is still in your system at midnight.",
       "<p>Keep total intake under ~400 mg/day and stop by early afternoon. Use it strategically before high-difficulty blocks rather than constantly.</p><p>If you feel you 'need' caffeine to function at baseline, that is a sleep-debt signal, not a caffeine deficiency.</p>"),
    _a("Strategic Napping", "sleep",
       "A 10-20 minute nap restores alertness without grogginess; longer naps need full cycles.",
       "<p>Nap before 3 pm and keep it under 20 minutes, or commit to a full 90-minute cycle. Set an alarm; sleep inertia from 30-60 minute naps can impair performance for an hour.</p>"),
    _a("Managing Sleep the Week Before the Exam", "sleep",
       "Bank consistent sleep in the final week; one bad pre-exam night matters less after a good week.",
       "<p>Fix your wake time to match exam day at least five days out. Do a dress rehearsal: wake, eat, and travel as if it were exam day.</p><p>If exam-eve sleep is poor, don't panic — performance is driven more by the preceding week's sleep than the final night.</p>"),

    # ---------- EXERCISE ----------
    _a("Exercise as Cognitive Enhancement", "exercise",
       "Aerobic exercise acutely improves attention and long-term memory via BDNF.",
       "<p>Twenty to thirty minutes of moderate aerobic exercise increases hippocampal BDNF and improves encoding for several hours afterwards. A brisk walk before your hardest study block is a legitimate study technique.</p><p>Aim for 150 minutes of moderate activity weekly even during peak preparation — it returns more performance than the same time spent studying tired.</p>"),
    _a("Micro-Workouts Between Study Blocks", "exercise",
       "Two-minute movement snacks every hour offset the cognitive cost of prolonged sitting.",
       "<p>Between pomodoros: 20 squats, 10 push-ups, or a flight of stairs. These movement snacks improve cerebral blood flow and break the postural strain of long sitting.</p>"),
    _a("Strength Training and Stress Resilience", "exercise",
       "Resistance training twice weekly measurably reduces anxiety symptoms.",
       "<p>Two full-body sessions weekly (30-40 minutes) are enough. Strength training improves sleep quality and provides a sense of progress that buffers the open-ended feeling of exam preparation.</p>"),
    _a("Walking Meetings With Yourself", "exercise",
       "Use walks for audio review and spaced recall — movement plus retrieval is a powerful combination.",
       "<p>Record yourself summarising topics, or use the platform's notes read aloud, and review while walking. Recall practice during light exercise shows equal or better retention than seated review.</p>"),
    _a("Exercise Timing Around Study", "exercise",
       "Exercise before study sharpens focus; intense late-evening sessions can disrupt sleep.",
       "<p>Morning or midday training fits most schedules best. Finish vigorous exercise at least 2-3 hours before bed. Light evening yoga or stretching, by contrast, aids sleep onset.</p>"),

    # ---------- MOTIVATION ----------
    _a("Why You Started: The IMG Journey", "motivation",
       "Reconnecting with your purpose sustains effort when willpower runs out.",
       "<p>Write a single paragraph on why you chose to practise medicine in Australia — patient care, family, growth. Pin it where you study. Motivation follows meaning, and meaning survives bad mock scores.</p><p>Remember: thousands of IMGs have passed the AMC before you with the same doubts you have now.</p>"),
    _a("Process Goals Beat Outcome Goals", "motivation",
       "You can't control the pass mark today; you can control today's 20 MCQs.",
       "<p>Set daily process goals (questions answered, topics reviewed, flashcards cleared) rather than outcome goals (score X). Process goals are always achievable, which protects momentum.</p><p>Review weekly: did the process happen? If yes, trust it. If no, fix the schedule, not your self-worth.</p>"),
    _a("The Progress Journal", "motivation",
       "Five minutes of recording wins each evening builds the evidence base for confidence.",
       "<p>Each night, write three things you learned and one thing you got wrong and now understand. Over weeks this becomes proof of progress that feelings alone won't supply — re-read it before mock exams.</p>"),
    _a("Handling Setbacks and Failed Attempts", "motivation",
       "A failed attempt is data, not a verdict — diagnose, adjust, and re-enter.",
       "<p>Analyse a failed attempt like a clinician: which subjects, which question types, what conditions (time pressure, fatigue)? Build the next cycle around those specific deficits.</p><p>Many now-practising doctors in Australia passed on their second or third attempt. Persistence with adjustment — not raw repetition — is what converts attempts into passes.</p>"),
    _a("Celebrate Milestones Deliberately", "motivation",
       "Scheduled rewards consolidate habit loops over a months-long campaign.",
       "<p>Pre-commit rewards to milestones: finishing a subject, a 10-day streak, a mock above target. Small, immediate, and guilt-free works best — a meal out, an evening off, a film.</p><p>The brain repeats what gets rewarded. Make sure studying is what gets rewarded.</p>"),

    # ---------- WELLNESS ----------
    _a("Nutrition for Sustained Study", "wellness",
       "Stable glucose beats glucose spikes: protein-anchored meals sustain attention.",
       "<p>Anchor each meal with protein and fibre; avoid high-sugar lunches that produce a mid-afternoon crash. Keep nuts, fruit, and yoghurt within reach instead of confectionery.</p><p>Hydration matters: even 2% dehydration measurably impairs concentration. Keep a water bottle on the desk.</p>"),
    _a("Eye Strain and the 20-20-20 Rule", "wellness",
       "Every 20 minutes, look at something 20 feet away for 20 seconds.",
       "<p>Long screen sessions cause accommodative fatigue and headaches. Follow 20-20-20, increase font sizes, enable dark mode at night, and blink deliberately — blink rate halves during screen focus.</p>"),
    _a("Maintaining Relationships During Preparation", "wellness",
       "Your support network is part of your exam infrastructure — schedule it like study.",
       "<p>Block one protected evening per week for family or friends with no study talk. Communicate your timeline so loved ones know the intensity is temporary and bounded.</p>"),
    _a("Financial Stress and Practical Planning", "wellness",
       "Money worries compete for the same working memory as clinical knowledge.",
       "<p>Budget exam fees, resources, and travel early; explore payment plans and IMG community resources. Converting vague financial dread into a written plan releases significant cognitive bandwidth back to study.</p>"),
    _a("When to Seek Professional Help", "wellness",
       "Persistent low mood, hopelessness, or thoughts of self-harm warrant professional support now, not after the exam.",
       "<p>If low mood, anhedonia, or anxiety persist beyond two weeks, or you have any thoughts of self-harm, see a GP — doctors and IMGs are entitled to the same care they give others. In Australia, support is available from Lifeline (13 11 14) and the Doctors' Health Advisory Service in each state.</p><p>Seeking help early is a professional strength and protects both you and your future patients.</p>"),
]
