def _q(subject, topic, difficulty, stem, options, correct, explanation, learning_point, reference):
    return {
        "subject": subject, "topic": topic, "difficulty": difficulty, "question_text": stem,
        "options": [
            {"letter": letter, "text": text, "is_correct": letter == correct}
            for letter, text in zip("ABCDE", options)
        ],
        "explanation": explanation, "learning_point": learning_point, "reference": reference,
    }


MCQS_3 = [
    # ---------------- MEDICINE (12) ----------------
    _q("Medicine", "Giant cell arteritis", "medium",
       "A 72-year-old woman presents with 2 weeks of new right temporal headache, scalp tenderness when brushing her hair, and jaw pain on chewing. She reports one brief episode of blurred vision in the right eye yesterday. ESR is 88 mm/hr and CRP 64 mg/L. What is the most appropriate immediate management?",
       ["Arrange temporal artery biopsy and start treatment once the result is available",
        "Commence high-dose oral prednisolone immediately and arrange temporal artery biopsy within days",
        "Commence low-dose aspirin and review in one week",
        "Order an MRI brain to exclude an intracranial lesion before treatment",
        "Refer routinely to rheumatology outpatients"],
       "B",
       "New temporal headache, scalp tenderness and jaw claudication in a patient over 50 with markedly raised inflammatory markers is giant cell arteritis, and the transient visual loss signals impending permanent blindness from arteritic anterior ischaemic optic neuropathy. High-dose corticosteroids must be started immediately on clinical suspicion - vision lost to GCA is rarely recovered, and the fellow eye is at risk within days. Temporal artery biopsy should follow promptly but remains diagnostic for at least 1-2 weeks after starting steroids, so treatment is never delayed for it. Aspirin alone, imaging-first strategies and routine referral all risk irreversible blindness.",
       "Suspected GCA with visual symptoms: start high-dose corticosteroids immediately - never wait for the biopsy.",
       "RACGP guidelines / Therapeutic Guidelines: Rheumatology"),

    _q("Medicine", "Diabetic ketoacidosis", "medium",
       "A 19-year-old woman with type 1 diabetes presents with vomiting and abdominal pain after 2 days of poor insulin adherence. She is tachypnoeic with a ketotic odour. Glucose is 28 mmol/L, pH 7.12, bicarbonate 9 mmol/L, capillary ketones 5.8 mmol/L, K+ 5.4 mmol/L. What is the most appropriate initial management?",
       ["IV insulin bolus followed by subcutaneous insulin",
        "IV sodium bicarbonate to correct the acidosis",
        "IV 0.9% sodium chloride resuscitation, then an insulin infusion at 0.1 units/kg/hr with potassium replacement once K+ falls below 5.5 mmol/L",
        "Oral rehydration and rapid-acting insulin via her usual pen",
        "IV 5% dextrose with an insulin infusion from the outset"],
       "C",
       "This is moderate-severe DKA, and the treatment priorities are in a fixed order: fluid first, then insulin, with potassium vigilance throughout. Initial resuscitation is with 0.9% sodium chloride, followed by a fixed-rate IV insulin infusion; total body potassium is depleted despite the raised serum level, so potassium is added to fluids as soon as K+ falls below about 5.5 mmol/L and urine output is confirmed. Insulin boluses and subcutaneous regimens give unreliable delivery in a shocked, acidotic patient. Bicarbonate does not improve outcomes and risks paradoxical CNS acidosis; dextrose-containing fluid is introduced only once glucose falls to around 15 mmol/L.",
       "DKA: fluids first, fixed-rate insulin infusion second, and watch the potassium - serum K+ falls fast once insulin starts.",
       "RACGP guidelines / Australian Diabetes Society DKA guidance"),

    _q("Medicine", "Hyponatraemia", "hard",
       "A 68-year-old man treated for pneumonia is noted on day 4 to have serum sodium 118 mmol/L (admission 132 mmol/L). He is mildly confused but has no seizures. He is clinically euvolaemic; urine osmolality is 560 mOsm/kg and urine sodium 64 mmol/L. Thyroid function and morning cortisol are normal. What is the most appropriate management?",
       ["Rapid correction with hypertonic 3% saline targeting a normal sodium within 24 hours",
        "IV 0.9% sodium chloride at 125 mL/hr",
        "Fluid restriction to 1 litre/day with regular sodium monitoring, correcting no faster than 8 mmol/L per 24 hours",
        "Oral sodium chloride tablets and a loop diuretic",
        "Desmopressin to reduce urinary water loss"],
       "C",
       "Euvolaemic hyponatraemia with concentrated urine, high urine sodium and normal thyroid/adrenal function is SIADH, here secondary to pneumonia. With mild symptoms and a likely chronic component, first-line treatment is fluid restriction, with correction limited to no more than 8 mmol/L in 24 hours - overly rapid correction of chronic hyponatraemia causes osmotic demyelination syndrome. Hypertonic saline is reserved for severe symptoms (seizures, coma) and even then is given in small boluses targeting a rise of only 4-6 mmol/L. Isotonic saline can paradoxically worsen SIADH because the kidney excretes the sodium and retains the water, and desmopressin would aggravate water retention.",
       "Euvolaemic hyponatraemia with concentrated urine = SIADH: fluid restrict and never correct chronic hyponatraemia faster than 8 mmol/L per day.",
       "RACGP guidelines / Therapeutic Guidelines: Endocrinology"),

    _q("Medicine", "Gout", "easy",
       "A 58-year-old man on allopurinol 300 mg daily for gout presents with an acutely hot, swollen, exquisitely tender first metatarsophalangeal joint. He is afebrile and otherwise well, with normal renal function and no peptic ulcer history. What is the most appropriate management?",
       ["Stop allopurinol and start an NSAID",
        "Continue allopurinol and treat the flare with an NSAID or low-dose colchicine",
        "Double the allopurinol dose to abort the attack",
        "Commence probenecid",
        "Arrange joint aspiration and IV antibiotics"],
       "B",
       "Acute gout flares are treated with an NSAID, low-dose colchicine or corticosteroids, and established urate-lowering therapy should be continued unchanged through the flare. Stopping allopurinol causes urate flux that can prolong or precipitate further attacks, and the older practice of ceasing it during flares is no longer recommended. Increasing the dose acutely similarly destabilises urate levels without treating the inflammation. Septic arthritis is a key differential, but an afebrile systemically well man with a classic podagra picture and known gout does not require aspiration and antibiotics as first-line.",
       "Never stop (or start) allopurinol during an acute gout flare - treat the flare and leave urate-lowering therapy unchanged.",
       "RACGP guidelines / Therapeutic Guidelines: Rheumatology"),

    _q("Medicine", "Community-acquired pneumonia", "medium",
       "A 47-year-old woman presents with 3 days of fever, productive cough and pleuritic chest pain. Temperature 38.6 C, HR 104, RR 24, BP 118/74 mmHg, SpO2 93% on room air. CXR shows right middle lobe consolidation. She has no comorbidities or allergies and is assessed as having moderate-severity pneumonia requiring admission. What is the most appropriate empirical antibiotic therapy?",
       ["Oral amoxicillin alone and discharge home",
        "IV ceftriaxone plus IV azithromycin",
        "IV benzylpenicillin plus oral doxycycline",
        "Oral ciprofloxacin",
        "IV vancomycin plus piperacillin-tazobactam"],
       "C",
       "Australian guidelines for moderate-severity community-acquired pneumonia requiring ward admission recommend IV benzylpenicillin plus an oral agent covering atypical organisms, usually doxycycline (or a macrolide). This narrow-spectrum approach reflects local resistance patterns and antimicrobial stewardship principles. Ceftriaxone plus azithromycin is reserved for high-severity pneumonia or where benzylpenicillin is unsuitable, and vancomycin/piperacillin-tazobactam is for severe sepsis with risk factors for resistant organisms. Oral amoxicillin alone suits low-severity outpatient treatment, and quinolones are never empirical first-line for CAP in Australia.",
       "Moderate CAP in Australia: IV benzylpenicillin plus doxycycline - reserve broad-spectrum agents for severe disease.",
       "Therapeutic Guidelines: Antibiotic / RACGP guidelines"),

    _q("Medicine", "Iron deficiency anaemia", "easy",
       "A 64-year-old man is found to have haemoglobin 96 g/L with MCV 72 fL and ferritin 8 microg/L on bloods taken for fatigue. He has no overt bleeding, takes no NSAIDs or anticoagulants, and eats a normal diet. What is the most appropriate next step after starting iron replacement?",
       ["Repeat the full blood count in 3 months",
        "Faecal occult blood testing, with colonoscopy only if positive",
        "Refer for gastroscopy and colonoscopy to identify a gastrointestinal source",
        "Trial of a high-iron diet and review in 6 months",
        "Blood transfusion"],
       "C",
       "Unexplained iron deficiency anaemia in a man (or postmenopausal woman) is gastrointestinal blood loss until proven otherwise, with colorectal cancer the critical diagnosis to exclude; bidirectional endoscopy (gastroscopy and colonoscopy) is the standard workup. Faecal occult blood testing is a population screening tool for asymptomatic people - it has no role in triaging established iron deficiency anaemia, where a negative result does not avert the need for endoscopy. Watchful waiting or dietary measures delay a potential cancer diagnosis, and transfusion is unnecessary at this haemoglobin in a stable patient. Coeliac serology should also be sent as part of the workup.",
       "Iron deficiency anaemia in a man or postmenopausal woman mandates gastroscopy and colonoscopy - do not triage with FOBT.",
       "RACGP guidelines / Cancer Council Australia colorectal guidelines"),

    _q("Medicine", "Hepatitis B serology", "hard",
       "A 36-year-old man born in Vietnam has the following hepatitis B serology at a new-patient health check: HBsAg positive, anti-HBs negative, anti-HBc positive, HBeAg negative, anti-HBe positive. ALT is normal and HBV DNA is 1,500 IU/mL. He feels well. What is the most appropriate interpretation and management?",
       ["Acute hepatitis B - notify and repeat serology in 6 months",
        "Resolved past infection - no follow-up required",
        "Successfully vaccinated - no follow-up required",
        "Chronic hepatitis B in an immune-control phase - enrol in lifelong monitoring with 6-monthly ALT and HBV DNA, and liver cancer surveillance as indicated",
        "Chronic hepatitis B requiring immediate antiviral therapy"],
       "D",
       "Persistent HBsAg positivity defines chronic hepatitis B infection; the combination of HBeAg negativity, anti-HBe positivity, low HBV DNA and normal ALT indicates the immune-control phase. These patients do not need antiviral therapy now, but the disease can reactivate, so guideline-based care is lifelong 6-monthly monitoring of ALT and periodic HBV DNA, plus hepatocellular carcinoma surveillance with ultrasound for higher-risk groups (which for Asian-born men begins at age 40). Resolved infection would show HBsAg negative with anti-HBc and anti-HBs positive, and vaccination produces isolated anti-HBs. Treating in the immune-control phase is not indicated, but discharging him without follow-up is the classic error - chronic hepatitis B is never 'cleared' from monitoring.",
       "HBsAg positive more than 6 months = chronic hepatitis B: phase determines treatment, but every patient needs lifelong structured monitoring.",
       "RACGP guidelines / GESA-ASHM hepatitis B management guidance"),

    _q("Medicine", "Osteoporosis", "easy",
       "A 74-year-old woman sustains a distal radius fracture after tripping on a footpath. DXA shows a lumbar spine T-score of -2.8. Renal function, calcium and vitamin D are normal, and she has no dysphagia or oesophageal disease. In addition to calcium and vitamin D adequacy, what is the most appropriate management?",
       ["Reassure - a single fracture does not require treatment",
        "Commence an oral bisphosphonate such as alendronate",
        "Commence menopausal hormone therapy",
        "Repeat the DXA scan in 2 years before deciding on therapy",
        "Commence teriparatide as first-line therapy"],
       "B",
       "A minimal-trauma fracture in a woman over 50, especially with a densitometric T-score of -2.5 or below, is an unequivocal indication for antiresorptive therapy, and oral bisphosphonates (alendronate or risedronate) are first-line; denosumab and zoledronic acid are alternatives where oral therapy is unsuitable. Both the fracture and the T-score independently qualify her for PBS-subsidised treatment, so reassurance or a 2-year DXA delay leaves her exposed to high re-fracture risk - the first fracture is the strongest predictor of the next. MHT is not first-line for osteoporosis at 74, and teriparatide is reserved for severe disease after bisphosphonate failure.",
       "A minimal-trauma fracture over 50 means osteoporosis treatment is indicated - do not wait for further fractures or repeat scans.",
       "RACGP guidelines / Healthy Bones Australia"),

    _q("Medicine", "Adrenal insufficiency", "medium",
       "A 61-year-old woman on long-term prednisolone 10 mg daily for polymyalgia rheumatica stopped it abruptly 4 days ago. She presents with vomiting, profound fatigue and dizziness. BP 84/56 mmHg, HR 112. Sodium 126 mmol/L, potassium 5.3 mmol/L, glucose 3.4 mmol/L. What is the most appropriate immediate management?",
       ["Take blood for cortisol and ACTH and await results before treating",
        "IV hydrocortisone 100 mg immediately plus IV 0.9% sodium chloride resuscitation",
        "Recommence oral prednisolone 10 mg and discharge with GP follow-up",
        "IV 3% saline to correct the hyponatraemia",
        "Short synacthen test as the first step"],
       "B",
       "Abrupt withdrawal of long-term corticosteroids in a patient with suppressed adrenal axes has precipitated an adrenal (Addisonian) crisis: hypotension, vomiting, hyponatraemia, hyperkalaemia and hypoglycaemia. This is immediately life-threatening, and treatment is IV hydrocortisone 100 mg without delay plus aggressive 0.9% saline resuscitation; a baseline cortisol can be drawn beforehand if it does not delay treatment, but waiting for results or performing a synacthen test in crisis is dangerous. Oral steroids are unreliable in a vomiting, shocked patient. The hyponatraemia corrects with cortisol and saline - hypertonic saline risks overcorrection and is not indicated.",
       "Suspected adrenal crisis: give IV hydrocortisone and saline immediately - confirm the diagnosis later.",
       "Therapeutic Guidelines: Endocrinology / RACGP guidelines"),

    _q("Medicine", "Hyperkalaemia", "medium",
       "A 70-year-old man with CKD stage 4 on ramipril and spironolactone presents with weakness. Potassium is 7.2 mmol/L. ECG shows peaked T waves and QRS duration of 134 ms. What is the most appropriate first action?",
       ["IV insulin with dextrose",
        "Oral sodium polystyrene sulfonate resin",
        "IV calcium gluconate 10% to stabilise the myocardium",
        "Nebulised salbutamol",
        "Urgent haemodialysis as the first step"],
       "C",
       "Severe hyperkalaemia with ECG changes (peaked T waves and a widening QRS) carries imminent risk of ventricular arrhythmia and asystole, and the first action is always IV calcium gluconate to stabilise the cardiac membrane - it acts within minutes but does not lower potassium. Insulin-dextrose and salbutamol follow immediately afterwards to shift potassium intracellularly, and resins or dialysis address total body potassium over hours. Giving shifting agents first leaves the myocardium unprotected during the most dangerous period. The ACE inhibitor and spironolactone combination in advanced CKD is the precipitant and both must be withheld.",
       "Hyperkalaemia with ECG changes: calcium first to protect the heart, then insulin-dextrose to shift, then removal strategies.",
       "Therapeutic Guidelines / RACGP guidelines"),

    _q("Medicine", "Optic neuritis and demyelination", "hard",
       "A 28-year-old woman presents with 3 days of progressive blurred vision and pain on eye movement in the left eye. Visual acuity is 6/36 on the left with impaired colour vision and a left relative afferent pupillary defect; the optic disc looks normal. She recalls 2 weeks of left leg numbness 18 months ago that resolved spontaneously. What is the most appropriate next investigation?",
       ["CT brain without contrast",
        "MRI brain and orbits with gadolinium",
        "Visual evoked potentials alone",
        "Lumbar puncture as the first test",
        "ESR and temporal artery biopsy"],
       "B",
       "Painful subacute monocular visual loss with impaired colour vision and an RAPD in a young woman is optic neuritis, and a normal disc is expected because two-thirds are retrobulbar. The prior self-resolving focal neurological episode raises strong suspicion of multiple sclerosis, making this potentially a second demyelinating event disseminated in time and space. MRI brain and orbits with gadolinium is the key investigation: it confirms optic nerve inflammation and quantifies demyelinating lesion load, which determines both diagnosis and the urgency of disease-modifying therapy. CT cannot image demyelination adequately, evoked potentials and CSF oligoclonal bands are supportive rather than primary tests, and giant cell arteritis is a disease of the over-50s.",
       "Optic neuritis in a young adult: MRI brain and orbits - it confirms the diagnosis and stratifies the risk of multiple sclerosis.",
       "RACGP guidelines / MS Australia clinical guidance"),

    _q("Medicine", "Coeliac disease", "medium",
       "A 31-year-old woman has iron deficiency anaemia, bloating and intermittent loose stools. Her sister has coeliac disease. She started a strict gluten-free diet 3 weeks ago on her own initiative and feels somewhat better. She asks to be tested for coeliac disease. What is the most appropriate advice?",
       ["Order tissue transglutaminase IgA serology now",
        "Proceed straight to duodenal biopsy while she remains gluten-free",
        "She must resume adequate gluten intake for at least 6 weeks before serological testing, with positive serology then confirmed by duodenal biopsy",
        "HLA-DQ2/DQ8 testing alone can confirm the diagnosis",
        "No testing is needed - her symptomatic response confirms coeliac disease"],
       "C",
       "Coeliac serology (tissue transglutaminase IgA, checked with a total IgA level) and duodenal histology both depend on active gluten exposure; testing on a gluten-free diet produces false negatives. She therefore needs a gluten challenge - generally at least 4-6 weeks of adequate daily gluten - before serology, and positive serology is confirmed by duodenal biopsy showing villous atrophy before committing her to a lifelong diet. HLA-DQ2/DQ8 typing is useful only for its negative predictive value: absence virtually excludes coeliac disease, but presence occurs in roughly 40% of the population and cannot confirm it. Symptomatic improvement on a gluten-free diet is non-specific and is never diagnostic.",
       "Coeliac testing is only valid on a gluten-containing diet - challenge first, then serology, then confirmatory biopsy.",
       "RACGP guidelines / GESA coeliac disease guidance"),

    # ---------------- SURGERY (8) ----------------
    _q("Surgery", "Testicular torsion", "easy",
       "A 14-year-old boy presents with 3 hours of sudden severe left testicular pain and vomiting that woke him from sleep. The left testis is high-riding, exquisitely tender and horizontally oriented, with an absent cremasteric reflex. What is the most appropriate management?",
       ["Doppler ultrasound of the scrotum before any intervention",
        "Immediate surgical exploration of the scrotum",
        "Oral antibiotics for epididymo-orchitis and review in 24 hours",
        "Analgesia and observation overnight",
        "Urine culture and outpatient urology referral"],
       "B",
       "Sudden severe testicular pain in an adolescent with a high-riding, horizontally lying testis and absent cremasteric reflex is testicular torsion, a surgical emergency where testicular salvage falls from over 90% within 6 hours to near zero beyond 24 hours. The diagnosis is clinical, and immediate scrotal exploration with detorsion and bilateral orchidopexy is mandatory - ultrasound is reserved for genuinely equivocal cases and must never delay theatre, since a false-negative Doppler can cost the testis. Epididymo-orchitis is uncommon at this age and the examination findings here exclude it as a working diagnosis; observation or outpatient referral guarantees infarction.",
       "Clinical testicular torsion goes straight to theatre - imaging that delays exploration loses testes.",
       "RACGP guidelines / urological society guidance"),

    _q("Surgery", "Diverticulitis", "easy",
       "A 58-year-old woman presents with 2 days of left iliac fossa pain and fever 38.1 C. She is haemodynamically stable with localised tenderness and no peritonism. CT shows uncomplicated sigmoid diverticulitis with no abscess or free gas. She has never had a colonoscopy. What is the most appropriate management?",
       ["Urgent sigmoid colectomy",
        "Antibiotics and supportive care now, with colonoscopy after around 6 weeks to exclude colorectal malignancy",
        "Immediate colonoscopy to confirm the diagnosis",
        "Percutaneous drain insertion",
        "Discharge with analgesia alone and no follow-up"],
       "B",
       "Uncomplicated diverticulitis in a stable patient is managed conservatively with antibiotics (very mild cases may even be managed with analgesia alone), bowel rest as tolerated and review. Colonoscopy is contraindicated acutely because instrumenting an inflamed colon risks perforation, but after the first confirmed episode it is recommended at around 6 weeks to exclude an underlying colorectal cancer mimicking or coexisting with diverticulitis, particularly when the colon has not been recently examined. Surgery and percutaneous drainage are reserved for complicated disease - perforation, obstruction, fistula or abscess.",
       "Uncomplicated diverticulitis: antibiotics now, colonoscopy in 6 weeks - never scope an acutely inflamed colon.",
       "RACGP guidelines / Therapeutic Guidelines: Antibiotic"),

    _q("Surgery", "Sigmoid volvulus", "medium",
       "An 84-year-old nursing home resident with chronic constipation presents with 2 days of marked abdominal distension, absolute constipation and vomiting. The abdomen is tympanitic and non-peritonitic. Abdominal X-ray shows a grossly dilated coffee-bean shaped loop arising from the pelvis. What is the most appropriate initial management?",
       ["Urgent laparotomy and Hartmann procedure",
        "Gastrografin enema to reduce the volvulus",
        "Flexible sigmoidoscopic decompression with placement of a flatus tube",
        "Nasogastric decompression and IV fluids alone",
        "High colonic washout enemas"],
       "C",
       "The coffee-bean sign in an elderly institutionalised patient with chronic constipation is sigmoid volvulus. In the absence of peritonism or features of ischaemia, first-line treatment is endoscopic detorsion by flexible sigmoidoscopy with a flatus tube left in place, which succeeds in the majority of cases and converts an emergency into a semi-elective problem. Because recurrence approaches 60%, elective sigmoid colectomy should then be considered in operable patients. Emergency laparotomy is reserved for suspected gangrene, perforation or failed endoscopic reduction; NG tube and fluids are adjuncts that do not treat the obstruction, and enemas do not reliably reduce a volvulus.",
       "Sigmoid volvulus without peritonism: endoscopic decompression first, then plan definitive sigmoid resection because recurrence is the rule.",
       "RACGP guidelines / colorectal surgical society guidance"),

    _q("Surgery", "Thyroid nodule", "medium",
       "A 39-year-old woman presents with a 2.2 cm right thyroid nodule found incidentally on a carotid ultrasound. She is clinically euthyroid and TSH is 1.8 mIU/L. Dedicated thyroid ultrasound shows a solid hypoechoic nodule with microcalcifications. What is the most appropriate next step?",
       ["Ultrasound-guided fine needle aspiration cytology",
        "Radionuclide thyroid scan",
        "Total thyroidectomy",
        "Repeat ultrasound in 12 months",
        "Commence thyroxine to suppress the nodule"],
       "A",
       "With a normal TSH, the next step for a sonographically suspicious nodule (solid, hypoechoic, microcalcifications) of this size is ultrasound-guided fine needle aspiration, reported by Bethesda category, which directs management from observation through to surgery. A radionuclide scan is only useful when TSH is suppressed, to identify a hot nodule that would not need cytology because autonomous nodules are almost never malignant. Proceeding to thyroidectomy without cytology subjects many patients with benign disease to unnecessary surgery, while 12-month surveillance is inappropriate for a nodule with high-risk ultrasound features. Thyroxine suppression of nodules is ineffective and obsolete.",
       "Thyroid nodule workup: TSH first - if normal, suspicious nodules get ultrasound-guided FNA; scans are only for the suppressed TSH.",
       "RACGP guidelines / Australian thyroid cancer guidance"),

    _q("Surgery", "Melanoma", "hard",
       "A 52-year-old man has an excision biopsy of a changing pigmented lesion on his back. Histology confirms superficial spreading melanoma, Breslow thickness 1.4 mm, non-ulcerated, completely excised with 2 mm margins. There is no palpable lymphadenopathy. What is the most appropriate definitive management?",
       ["No further treatment - the lesion is completely excised",
        "Wide local excision with 1-2 cm margins and discussion of sentinel lymph node biopsy",
        "Wide local excision with 5 mm margins",
        "Elective regional lymph node dissection",
        "Adjuvant immunotherapy without further surgery"],
       "B",
       "Diagnostic excision margins of 2 mm are never adequate definitive treatment for invasive melanoma. A 1.4 mm Breslow thickness melanoma requires wide local excision with 1-2 cm margins, and because the risk of occult nodal metastasis becomes significant above 0.8 mm thickness, sentinel lymph node biopsy should be discussed and performed at the same operation - it provides the most powerful staging information and determines eligibility for adjuvant systemic therapy. Five-millimetre margins are only appropriate for melanoma in situ, elective completion node dissection of clinically negative basins is no longer practised, and adjuvant immunotherapy is reserved for resected stage III or high-risk disease established by staging, not given in place of adequate surgery.",
       "Invasive melanoma needs wide local excision (1-2 cm for 1-4 mm thickness) plus sentinel node biopsy discussion once Breslow exceeds 0.8 mm.",
       "Cancer Council Australia / Melanoma Institute Australia guidelines"),

    _q("Surgery", "Acute limb ischaemia", "medium",
       "A 76-year-old woman with atrial fibrillation not on anticoagulation presents with a 3-hour history of a painful, pale, cold right leg. Pedal pulses are absent, sensation is reduced over the foot, but calf muscles are soft and power is preserved. What is the most appropriate immediate management?",
       ["Duplex ultrasound as an outpatient",
        "IV unfractionated heparin now and urgent vascular surgical referral for revascularisation",
        "Oral aspirin and elevation of the limb",
        "Warm compresses and analgesia with review in the morning",
        "Immediate below-knee amputation"],
       "B",
       "Sudden onset of the classic ischaemic features in a patient with AF and no anticoagulation indicates embolic acute limb ischaemia, here Rutherford IIa (marginally threatened - sensory loss but preserved power). Immediate IV heparinisation prevents proximal and distal propagation of thrombus while urgent vascular assessment arranges revascularisation by embolectomy, thrombolysis or open/endovascular reconstruction; the viable window is roughly 6 hours of warm ischaemia. Outpatient imaging, antiplatelets alone, or overnight observation convert a salvageable limb into an amputation, and primary amputation is only for irreversibly ischaemic (Rutherford III) limbs with fixed mottling and paralysis.",
       "Acute limb ischaemia: heparinise immediately and involve vascular surgery - the limb has about 6 hours.",
       "RACGP guidelines / vascular surgical society guidance"),

    _q("Surgery", "Perforated peptic ulcer", "medium",
       "A 49-year-old man on regular ibuprofen for back pain presents with sudden severe epigastric pain that began 2 hours ago and rapidly became generalised. He lies rigidly still; the abdomen is board-like with generalised rebound tenderness. HR 116, BP 104/68 mmHg. Erect chest X-ray shows free gas under both hemidiaphragms. What is the most appropriate management?",
       ["IV proton pump inhibitor infusion and admit for observation",
        "Urgent gastroscopy to identify the ulcer",
        "IV fluid resuscitation, IV antibiotics, nasogastric tube, IV proton pump inhibitor and emergency operative repair",
        "CT abdomen in 24 hours if not improving",
        "Helicobacter pylori eradication therapy and discharge"],
       "C",
       "Sudden-onset epigastric pain becoming generalised, a rigid abdomen and pneumoperitoneum on erect CXR in an NSAID user is a perforated peptic ulcer with generalised peritonitis. Management is resuscitation followed by emergency surgery - typically laparoscopic or open omental patch repair with peritoneal lavage - alongside IV broad-spectrum antibiotics, nasogastric decompression and a proton pump inhibitor. Observation on a PPI is only ever considered in rare, contained, minimally symptomatic perforations. Gastroscopy is contraindicated because insufflation worsens contamination through the perforation, and any delay to imaging or eradication therapy while peritonitis progresses increases mortality, which rises steeply with each hour to theatre.",
       "Board-like abdomen plus free gas under the diaphragm = perforated viscus: resuscitate and go to theatre - never gastroscope a perforation.",
       "RACGP guidelines / Therapeutic Guidelines: Antibiotic"),

    _q("Surgery", "Compartment syndrome", "hard",
       "A 23-year-old man with a closed tibial shaft fracture treated in a backslab 8 hours ago reports escalating leg pain unrelieved by IV opioids. The calf is tense; passive dorsiflexion of the toes causes severe pain. The foot is warm with palpable pedal pulses and normal capillary refill. What is the most appropriate management?",
       ["Reassure - intact pulses exclude compartment syndrome",
        "Elevate the limb above heart level and increase the opioid dose",
        "Split and remove the cast and padding immediately and arrange urgent fasciotomy",
        "Compartment pressure measurement before any intervention, with surgery only if pressures are high",
        "Duplex ultrasound to exclude deep vein thrombosis"],
       "C",
       "Pain out of proportion to the injury, escalating analgesic requirements and pain on passive stretch of the compartment muscles are the cardinal early signs of acute compartment syndrome, and intact pulses are expected - arterial inflow pressure far exceeds the compartment pressure that destroys muscle, so pulselessness is a pre-terminal sign. All circumferential dressings must be split to skin immediately, and a clinically diagnosed compartment syndrome proceeds to urgent fasciotomy; muscle necrosis begins within hours. Compartment pressure measurement is an adjunct for unconscious or unexaminable patients, not a prerequisite that delays surgery. Elevation above heart level reduces perfusion pressure and is harmful, and a DVT does not produce stretch pain of this character.",
       "Pulses stay present in compartment syndrome - stretch pain and escalating analgesia needs mean split the cast and fasciotomy now.",
       "RACGP guidelines / orthopaedic trauma guidance"),

    # ---------------- PAEDIATRICS (8) ----------------
    _q("Paediatrics", "Pyloric stenosis", "medium",
       "A 5-week-old boy has 1 week of worsening forceful non-bilious vomiting immediately after feeds, after which he is hungry and demands refeeding. He has lost 200 g since his last weigh-in. Venous gas: pH 7.51, chloride 88 mmol/L, potassium 3.1 mmol/L, bicarbonate 34 mmol/L. Ultrasound confirms pyloric muscle thickening. What is the most appropriate management?",
       ["Emergency pyloromyotomy tonight",
        "IV rehydration and correction of the hypochloraemic hypokalaemic alkalosis, followed by pyloromyotomy once electrolytes normalise",
        "Thickened feeds and outpatient review",
        "Nasojejunal feeding for 6 weeks",
        "Trial of oral atropine and discharge"],
       "B",
       "Projectile non-bilious vomiting with a hungry baby and hypochloraemic hypokalaemic metabolic alkalosis is the classic presentation of hypertrophic pyloric stenosis, confirmed on ultrasound. The critical principle is that pyloromyotomy is never an emergency, but the metabolic derangement is: uncorrected alkalosis causes postoperative apnoea under anaesthesia, so surgery is deferred until rehydration and electrolyte correction with sodium chloride-containing fluids plus potassium are complete. Conservative options such as thickened feeds or atropine are not standard Australian practice, and operating tonight on an alkalotic, potassium-deplete infant exposes him to avoidable anaesthetic risk.",
       "Pyloric stenosis: correct the fluids and the hypochloraemic alkalosis first - pyloromyotomy is urgent, never emergent.",
       "RCH Clinical Practice Guidelines"),

    _q("Paediatrics", "Pertussis", "medium",
       "A 3-month-old girl, who has received only her 6-week vaccinations, presents with 1 week of coughing paroxysms followed by vomiting, and one episode at home where she briefly stopped breathing and turned blue. Between coughing bouts she looks well. Oxygen saturation is 97%. What is the most appropriate management?",
       ["Discharge with oral azithromycin and review in 48 hours",
        "Admit for monitoring, perform nasopharyngeal PCR for Bordetella pertussis, start azithromycin, and notify the public health unit",
        "Salbutamol via spacer and discharge",
        "Reassure - the well appearance between episodes excludes serious illness",
        "Chest physiotherapy and saline nebulisers"],
       "B",
       "Paroxysmal coughing with post-tussive vomiting and an apnoeic cyanotic episode in a partially immunised young infant is pertussis until proven otherwise. Infants under 6 months - especially under 3 months - are at highest risk of apnoea, hypoxic encephalopathy and death, and an observed apnoea mandates admission with cardiorespiratory monitoring regardless of how well the baby looks between paroxysms; looking well between episodes is characteristic of the disease, not reassuring. Diagnosis is by nasopharyngeal PCR, treatment is azithromycin (which limits transmission), household contacts need prophylaxis, and pertussis is notifiable. Bronchodilators and physiotherapy have no role.",
       "Pertussis with apnoea in an infant under 6 months means admission and monitoring - the well appearance between paroxysms is the trap.",
       "RCH Clinical Practice Guidelines: Whooping cough"),

    _q("Paediatrics", "Henoch-Schonlein purpura", "medium",
       "A 6-year-old boy presents with a 3-day history of a palpable purpuric rash over the buttocks and extensor legs, colicky abdominal pain, and a swollen painful left ankle. He is afebrile and well. Platelets are 320 x 10^9/L and coagulation is normal. Urinalysis shows microscopic haematuria without proteinuria, and blood pressure is normal. What is the most appropriate management?",
       ["Urgent renal biopsy",
        "IV broad-spectrum antibiotics for meningococcal sepsis",
        "Supportive care with simple analgesia, and structured follow-up of urinalysis and blood pressure over the following 6-12 months",
        "High-dose IV methylprednisolone for all cases",
        "Platelet transfusion"],
       "C",
       "Palpable purpura in a dependent distribution with normal platelets and coagulation, arthritis and abdominal pain in a well, afebrile child is IgA vasculitis (Henoch-Schonlein purpura), which is usually self-limiting and managed with supportive care and simple analgesia. The prognosis is determined by renal involvement, which can appear weeks to months after presentation, so scheduled urinalysis and blood pressure checks for at least 6-12 months are the essential part of management; isolated microscopic haematuria needs monitoring, not biopsy. Normal platelets distinguish this from thrombocytopenic purpura and the well afebrile state from meningococcaemia. Corticosteroids are reserved for severe abdominal pain, orchitis or significant nephritis, not routine use.",
       "HSP itself is benign - the management is months of urine and blood pressure surveillance for the nephritis that arrives late.",
       "RCH Clinical Practice Guidelines: Henoch-Schonlein purpura"),

    _q("Paediatrics", "Immune thrombocytopenic purpura", "easy",
       "A 4-year-old girl develops widespread petechiae and bruising 2 weeks after a viral illness. She is otherwise well with no fever, bone pain, pallor, lymphadenopathy or hepatosplenomegaly. Platelets are 14 x 10^9/L; haemoglobin, white cell count and blood film are otherwise normal. There is no mucosal bleeding. What is the most appropriate management?",
       ["Platelet transfusion",
        "Bone marrow aspirate before any decision",
        "Observation with safety advice (avoid contact sports and NSAIDs) and early review, without pharmacological treatment",
        "Splenectomy",
        "IV immunoglobulin and corticosteroids for all cases"],
       "C",
       "Post-viral isolated thrombocytopenia in a well child with an otherwise normal blood count and film is acute immune thrombocytopenic purpura. Management is guided by bleeding, not the platelet number: with skin manifestations only, observation with safety advice (avoiding contact sport, NSAIDs and intramuscular injections) is recommended, and around 80% remit spontaneously within months. IVIg or corticosteroids are reserved for significant mucosal or life-threatening bleeding. Transfused platelets are consumed immediately and are reserved for critical haemorrhage; marrow examination is only needed for atypical features (abnormal other cell lines, hepatosplenomegaly, bone pain) or before steroid use where leukaemia has not been confidently excluded.",
       "Childhood ITP with skin-only bleeding: treat the child, not the platelet count - observation is standard.",
       "RCH Clinical Practice Guidelines: ITP"),

    _q("Paediatrics", "Inhaled foreign body", "medium",
       "A 2-year-old boy had a coughing and choking episode while eating peanuts yesterday. Today he has a persistent cough and an audible wheeze. He is comfortable with SpO2 96%. Auscultation reveals reduced breath sounds and monophonic wheeze over the right chest. Chest X-ray shows hyperinflation of the right lung on the expiratory film but no visible foreign body. What is the most appropriate management?",
       ["Salbutamol via spacer and review in 48 hours for presumed asthma",
        "Reassure - the normal-appearing X-ray excludes a foreign body",
        "Referral for rigid bronchoscopy to remove the inhaled foreign body",
        "Oral antibiotics for pneumonia",
        "Back blows and chest thrusts now"],
       "C",
       "A witnessed choking episode followed by persistent cough and unilateral monophonic wheeze is an inhaled foreign body until proven otherwise. Peanuts are radiolucent, so a 'normal' X-ray never excludes the diagnosis - the typical indirect sign is air trapping with unilateral hyperinflation on an expiratory film, exactly as here, caused by a ball-valve effect. Definitive management is removal by rigid bronchoscopy under general anaesthesia. Treating as asthma is the classic error (new unilateral wheeze in a toddler is not asthma), retained organic material causes pneumonia and bronchiectasis if missed, and back blows are only for acute complete airway obstruction, not a stable child a day later.",
       "Choking episode plus unilateral wheeze = bronchoscopy; a normal chest X-ray never excludes a radiolucent foreign body.",
       "RCH Clinical Practice Guidelines: Inhaled foreign body"),

    _q("Paediatrics", "Acute otitis media", "easy",
       "A 3-year-old boy from Melbourne presents with 1 day of left ear pain and fever 38.3 C during a coryzal illness. He is alert, well hydrated and playing in the waiting room. The left tympanic membrane is red and bulging. He has no history of recurrent ear infections. What is the most appropriate management?",
       ["Immediate amoxicillin for 10 days",
        "Regular paracetamol and/or ibuprofen for analgesia, with antibiotics only if not improving after 48 hours",
        "Topical antibiotic ear drops",
        "Urgent ENT referral for tympanocentesis",
        "Oral decongestants and antihistamines"],
       "B",
       "Acute otitis media in a systemically well child over 2 years is usually viral or self-resolving, and Australian guidance recommends adequate analgesia with a watch-and-wait approach, reserving antibiotics for failure to improve at 48 hours. Antibiotics shorten symptoms only marginally in this group while causing adverse effects and resistance. Immediate antibiotics are indicated for infants under 6 months, systemically unwell children, those with otorrhoea or cochlear implants, and Aboriginal and Torres Strait Islander children at high risk of chronic suppurative otitis media - none of which applies here. Topical drops do not penetrate an intact drum, and decongestants are ineffective and not recommended in young children.",
       "Well child over 2 with AOM: analgesia and 48-hour review beats immediate antibiotics - but know the exceptions who get them straight away.",
       "Therapeutic Guidelines: Antibiotic / RCH Clinical Practice Guidelines"),

    _q("Paediatrics", "Slipped upper femoral epiphysis", "hard",
       "A 12-year-old overweight boy presents with 3 weeks of left knee pain and a limp, worse after sport. Knee examination is normal, but internal rotation of the flexed left hip is restricted and reproduces his pain. What is the most appropriate next step?",
       ["X-ray of the left knee",
        "Anteroposterior and frog-leg lateral X-rays of both hips, with immediate non-weight-bearing and urgent orthopaedic referral if SUFE is confirmed",
        "Reassure - growing pains are likely and review in 6 weeks",
        "Physiotherapy referral for a presumed muscle strain",
        "Bone scan as the initial investigation"],
       "B",
       "Knee pain with a normal knee examination in an overweight early adolescent is referred hip pathology until proven otherwise, and restricted, painful internal rotation of the hip points to slipped upper femoral epiphysis. Imaging must include both hips (the slip is bilateral in up to 20-40%) with a frog-leg lateral view, because subtle slips are routinely missed on the AP film alone. Confirmed SUFE requires immediate cessation of weight-bearing and urgent referral for in-situ screw fixation - continued walking can convert a stable slip into an unstable one, raising the risk of avascular necrosis from around 5% to nearly 50%. Knee imaging, reassurance and physiotherapy are the standard pathways by which this diagnosis is fatally delayed.",
       "Adolescent knee pain: examine and image the hips - SUFE needs frog-leg laterals of both sides, non-weight-bearing and urgent fixation.",
       "RCH Clinical Practice Guidelines: The limping child"),

    _q("Paediatrics", "Septic arthritis", "medium",
       "A 3-year-old girl presents with fever 38.9 C and refusal to weight-bear on the right leg since this morning. She holds the right hip flexed and externally rotated and cries with any passive movement. WCC 17 x 10^9/L, CRP 92 mg/L, ESR 54 mm/hr. Ultrasound shows a right hip effusion. What is the most appropriate management?",
       ["Oral antibiotics and review in 48 hours",
        "NSAIDs and observation for transient synovitis",
        "Urgent joint aspiration with surgical drainage as indicated, followed by empirical IV antibiotics",
        "MRI in one week if not improving",
        "Skin traction and analgesia"],
       "C",
       "Fever, complete refusal to weight-bear, severe pain on any movement and markedly raised inflammatory markers satisfy the high-risk (Kocher) criteria for septic arthritis of the hip rather than transient synovitis, and the effusion on ultrasound supports this. Septic arthritis of the hip is an orthopaedic emergency: pus under pressure destroys articular cartilage and the femoral head blood supply within days, so management is urgent aspiration for Gram stain and culture, usually with formal arthrotomy washout, followed immediately by empirical IV antibiotics (typically flucloxacillin-based to cover Staphylococcus aureus). Transient synovitis is a diagnosis for the afebrile or minimally febrile child with low inflammatory markers who can partially weight-bear; oral antibiotics or delayed imaging allow joint destruction.",
       "Febrile non-weight-bearing child with high inflammatory markers = septic hip until aspirated - washout and IV antibiotics, urgently.",
       "RCH Clinical Practice Guidelines: Septic arthritis"),

    # ---------------- OBGYN (8) ----------------
    _q("OBGYN", "Ectopic pregnancy", "medium",
       "A 29-year-old woman at 6 weeks amenorrhoea presents with sudden severe left iliac fossa pain and shoulder-tip pain. She is pale; BP 88/54 mmHg, HR 118. Urine hCG is positive. Bedside ultrasound shows an empty uterus and significant free fluid in the pelvis. What is the most appropriate management?",
       ["Serial beta-hCG measurements over 48 hours",
        "Methotrexate 50 mg/m2 intramuscularly",
        "IV fluid resuscitation, urgent cross-match, and immediate laparoscopy/laparotomy for surgical management of a ruptured ectopic pregnancy",
        "Admit for observation and repeat ultrasound in the morning",
        "Suction curettage of the uterus"],
       "C",
       "A positive pregnancy test with an empty uterus, an acute abdomen, shoulder-tip pain (diaphragmatic irritation from haemoperitoneum) and haemodynamic compromise is a ruptured ectopic pregnancy - the leading cause of first-trimester maternal death. Management is simultaneous resuscitation and immediate surgery, usually laparoscopic salpingectomy. Methotrexate is strictly limited to haemodynamically stable women with small unruptured ectopics, low hCG and no significant free fluid; serial hCG and overnight observation are options only for stable patients with pregnancies of unknown location. Curettage treats the wrong site. She will also need her blood group checked and Rh(D) immunoglobulin if RhD negative.",
       "Positive hCG + empty uterus + shock = ruptured ectopic: resuscitate and operate now - methotrexate is only ever for the stable, unruptured case.",
       "RANZCOG / SA Health Perinatal Practice Guidelines"),

    _q("OBGYN", "Pre-eclampsia", "medium",
       "A 31-year-old primigravida at 36 weeks presents with headache and visual blurring. BP is 168/112 mmHg on repeated measurement, urine PCR 120 mg/mmol, platelets 102 x 10^9/L, ALT 88 U/L. Reflexes are brisk with 2 beats of clonus. The CTG is normal. What is the most appropriate management?",
       ["Oral antihypertensive and review in antenatal clinic in 48 hours",
        "Admit, lower blood pressure urgently (e.g. IV labetalol or oral nifedipine), commence IV magnesium sulphate, and plan delivery",
        "Strict bed rest and daily urine dipsticks until 40 weeks",
        "IV magnesium sulphate alone and continue the pregnancy to term",
        "Immediate caesarean section under general anaesthesia before any other measures"],
       "B",
       "She has severe pre-eclampsia with neurological symptoms, severe hypertension, thrombocytopenia and hepatic involvement at 36 weeks. The immediate priorities are urgent blood pressure control to below 160/110 mmHg (to prevent intracerebral haemorrhage), magnesium sulphate for eclampsia prophylaxis given her neurological features and clonus, and planning delivery - the only cure - which at 36 weeks with severe features is clearly indicated. Outpatient management or expectant continuation to term is dangerous at this severity. Delivery does not automatically mean caesarean: with a normal CTG, stabilisation followed by induction of labour may be appropriate, and rushing to theatre before controlling BP and loading magnesium increases maternal risk.",
       "Severe pre-eclampsia: control the pressure, load magnesium sulphate, and deliver - but stabilise the mother before the birth, whatever the mode.",
       "RANZCOG / SOMANZ hypertension in pregnancy guidelines"),

    _q("OBGYN", "Gestational diabetes", "easy",
       "A 32-year-old woman undergoes a routine 75 g oral glucose tolerance test at 27 weeks gestation. Results: fasting glucose 5.4 mmol/L, 1-hour 9.8 mmol/L, 2-hour 8.0 mmol/L. What is the most appropriate initial management?",
       ["Reassure - these values are normal in pregnancy",
        "Commence basal insulin immediately",
        "Dietary modification and physical activity with self-monitoring of blood glucose, escalating to pharmacotherapy if targets are not met",
        "Repeat the OGTT at 36 weeks before acting",
        "Commence metformin as mandatory first-line therapy"],
       "C",
       "A fasting glucose of 5.4 mmol/L (threshold >= 5.1) confirms gestational diabetes on the universal 75 g OGTT performed at 24-28 weeks. First-line management for the majority is medical nutrition therapy and physical activity with structured self-monitoring of capillary glucose against pregnancy targets; a large proportion achieve control without medication. Insulin (or metformin in selected women) is added only when glycaemic targets are persistently exceeded despite lifestyle measures. The values are clearly diagnostic, so reassurance or delaying with a repeat test exposes the pregnancy to risks of macrosomia, shoulder dystocia and neonatal hypoglycaemia. She also needs postpartum follow-up testing given her lifetime risk of type 2 diabetes.",
       "GDM diagnosed at fasting >= 5.1 mmol/L on the 75 g OGTT: diet, activity and glucose monitoring first - medication only if targets are missed.",
       "RANZCOG / ADIPS gestational diabetes guidelines"),

    _q("OBGYN", "Postpartum haemorrhage", "medium",
       "A 27-year-old woman has just delivered a 4.2 kg baby vaginally after a prolonged labour. Fifteen minutes after delivery of the placenta, which appeared complete, she has ongoing heavy vaginal bleeding estimated at 900 mL. The uterine fundus is soft and poorly contracted above the umbilicus. IV access is in place. What is the most appropriate next step?",
       ["Immediate hysterectomy",
        "Uterine fundal massage and further uterotonics (e.g. IV oxytocin infusion, then ergometrine or carboprost as needed), with concurrent resuscitation",
        "Vaginal packing as the first measure",
        "Observation - this volume of loss is physiological after delivery",
        "Transfer to interventional radiology for uterine artery embolisation as the first step"],
       "B",
       "Blood loss over 500 mL after vaginal birth defines primary postpartum haemorrhage, and a soft, high, poorly contracted uterus identifies atony - responsible for about 70% of cases, with prolonged labour and a macrosomic infant as classic risk factors. First-line management is mechanical and pharmacological: fundal massage to stimulate contraction plus escalating uterotonics (oxytocin infusion, ergometrine, carboprost, misoprostol) alongside resuscitation, early tranexamic acid, and examination to exclude trauma and retained tissue (the other 'four Ts'). Packing, balloon tamponade, embolisation and surgery are sequential escalation steps when uterotonics fail - not first measures - and 900 mL of ongoing loss is never physiological.",
       "PPH with a boggy uterus is atony: massage the fundus and escalate uterotonics while resuscitating - and always check the other three Ts.",
       "RANZCOG / SA Health Perinatal Practice Guidelines"),

    _q("OBGYN", "Shoulder dystocia", "hard",
       "During a vaginal birth at term, the fetal head delivers but then retracts against the perineum, and gentle axial traction with the next contraction fails to deliver the anterior shoulder. What is the most appropriate immediate sequence of actions?",
       ["Apply firm fundal pressure to push the baby out",
        "Call for help, instruct the mother to stop pushing, and perform McRoberts manoeuvre (hyperflexion of the maternal hips) with suprapubic pressure",
        "Proceed straight to symphysiotomy",
        "Apply strong downward traction on the fetal head",
        "Perform an immediate Zavanelli manoeuvre and caesarean section"],
       "B",
       "The turtle sign with failure of the anterior shoulder to deliver defines shoulder dystocia, an obstetric emergency where the clock to fetal hypoxic injury is minutes. The structured response begins with calling for help and stopping maternal pushing, then McRoberts manoeuvre - hyperflexing the maternal hips to rotate the symphysis - combined with external suprapubic pressure on the fetal anterior shoulder; this combination resolves the majority of cases and is low-risk. Fundal pressure worsens shoulder impaction and risks uterine rupture, and strong downward head traction causes brachial plexus injury - both are explicitly prohibited. Internal rotational manoeuvres and posterior arm delivery follow if McRoberts fails; symphysiotomy and Zavanelli are last-resort measures.",
       "Shoulder dystocia: help, stop pushing, McRoberts plus suprapubic pressure - never fundal pressure, never downward traction on the head.",
       "RANZCOG shoulder dystocia guidance"),

    _q("OBGYN", "Cervical screening", "easy",
       "A 38-year-old asymptomatic woman has a routine Cervical Screening Test. The result shows oncogenic HPV (not 16/18) detected, with a negative liquid-based cytology report. She has no history of cervical abnormality. What is the most appropriate management?",
       ["Immediate colposcopy",
        "Repeat the HPV test in 12 months",
        "Return to routine 5-yearly screening",
        "Cone biopsy",
        "Repeat the Cervical Screening Test in 6 weeks"],
       "B",
       "Under the National Cervical Screening Program, oncogenic HPV other than types 16/18 with negative or low-grade cytology places a woman at intermediate risk: most such infections clear spontaneously, so the pathway is a repeat HPV test in 12 months rather than immediate colposcopy. If HPV remains detected at 12 months she is then referred for colposcopy (and current guidance refers earlier for those over 50 or under-screened). Immediate colposcopy is reserved for HPV 16/18 detection or high-grade cytology, because these carry the highest short-term risk of high-grade disease. Returning to 5-yearly screening ignores a persistent-infection risk, and cone biopsy is a treatment, not a triage step.",
       "Non-16/18 oncogenic HPV with negative cytology: retest in 12 months; HPV 16/18 or high-grade cytology goes straight to colposcopy.",
       "National Cervical Screening Program guidelines / RANZCOG"),

    _q("OBGYN", "Antepartum haemorrhage", "medium",
       "A 28-year-old woman at 34 weeks gestation presents with sudden constant severe abdominal pain and dark vaginal bleeding of about 300 mL after a day of reduced fetal movements. The uterus is hard and tender between contractions. BP 102/64 mmHg, HR 110. CTG shows a fetal bradycardia of 90 bpm. A 20-week scan showed a fundal placenta. What is the most appropriate management?",
       ["Digital vaginal examination to assess the cervix",
        "Expectant management with corticosteroids until 37 weeks",
        "Urgent category 1 caesarean section with concurrent maternal resuscitation and cross-match",
        "Transvaginal ultrasound to locate the placenta before any decision",
        "Induction of labour with an oxytocin infusion"],
       "C",
       "Constant pain, dark bleeding, a hard tender ('woody') uterus and fetal compromise indicate placental abruption - the painful antepartum haemorrhage, in contrast to the painless bleeding of placenta praevia, which her fundal placenta on the 20-week scan effectively excludes. With a fetal bradycardia at 34 weeks, the fetus is acutely hypoxic from placental separation, and the only correct response is immediate category 1 caesarean section with simultaneous maternal resuscitation, cross-match and preparation for postpartum haemorrhage and coagulopathy. Expectant management and corticosteroids suit minor abruption with a normal CTG; induction is far too slow for an acutely compromised fetus. Revealed blood loss also underestimates concealed haemorrhage in abruption.",
       "Painful bleeding + woody uterus + abnormal CTG = abruption: category 1 caesarean, and remember concealed loss exceeds what you see.",
       "RANZCOG / SA Health Perinatal Practice Guidelines"),

    _q("OBGYN", "Rh(D) isoimmunisation", "easy",
       "A 26-year-old woman who is RhD negative with no detectable antibodies has a complete miscarriage confirmed at 9 weeks gestation. Her partner's blood group is unknown. What is the most appropriate management regarding isoimmunisation?",
       ["No anti-D is required for first-trimester pregnancy loss",
        "Administer Rh(D) immunoglobulin 250 IU within 72 hours of the sensitising event",
        "Administer Rh(D) immunoglobulin only if Kleihauer testing is positive",
        "Wait and test her antibodies in 6 weeks, giving anti-D only if antibodies appear",
        "Administer Rh(D) immunoglobulin 625 IU only if the partner is confirmed RhD positive"],
       "B",
       "Miscarriage is a potentially sensitising event, and Australian guidelines recommend Rh(D) immunoglobulin for RhD negative women without preformed anti-D antibodies after first-trimester sensitising events (miscarriage, termination, ectopic pregnancy), at a dose of 250 IU, given within 72 hours. Waiting for antibodies to appear defeats the purpose - once sensitisation has occurred, anti-D is useless and future pregnancies are at risk of haemolytic disease of the fetus and newborn. Kleihauer testing quantifies fetomaternal haemorrhage to guide additional dosing after larger, later-pregnancy events; it is not a prerequisite in the first trimester. Anti-D is given unless the father is confirmed RhD negative with certain paternity, which is not the case here.",
       "RhD negative woman + any sensitising event = anti-D within 72 hours; 250 IU covers first-trimester events.",
       "RANZCOG / National Blood Authority anti-D guidelines"),

    # ---------------- PSYCHIATRY (6) ----------------
    _q("Psychiatry", "Major depression", "easy",
       "A 34-year-old teacher presents with 2 months of low mood, anhedonia, early morning waking, poor concentration and fatigue affecting her work. She has passive thoughts that life is not worth living but no suicidal plan or intent, and no psychotic symptoms. She has never taken psychotropic medication. What is the most appropriate initial management?",
       ["Electroconvulsive therapy",
        "A tricyclic antidepressant as first-line pharmacotherapy",
        "An SSRI combined with referral for structured psychological therapy such as CBT, plus safety planning and early review",
        "Diazepam for symptom relief and review in a month",
        "Inpatient psychiatric admission"],
       "C",
       "She has moderate major depression with functional impairment. First-line treatment combines an SSRI - preferred over tricyclics for safety in overdose and tolerability - with evidence-based psychological therapy such as CBT, which together outperform either alone; a safety plan and review within 1-2 weeks of starting an antidepressant are essential, particularly in the early period when energy may return before mood lifts. Passive death wishes without plan or intent warrant careful safety planning but not involuntary or inpatient care. Benzodiazepines do not treat depression and risk dependence, and ECT is reserved for severe, psychotic, or treatment-refractory depression or where rapid response is life-saving.",
       "Moderate depression: SSRI plus CBT with an early review and safety plan - benzodiazepines treat nothing and TCAs are no longer first-line.",
       "RANZCP mood disorder guidelines / RACGP guidelines"),

    _q("Psychiatry", "Lithium toxicity", "medium",
       "A 48-year-old man with bipolar disorder stabilised on lithium presents with coarse tremor, ataxia, dysarthria and confusion. He started ibuprofen for a back strain 5 days ago and has had gastroenteritis with poor fluid intake. Lithium level is 2.6 mmol/L (therapeutic 0.6-0.8) and creatinine is 168 umol/L. What is the most appropriate management?",
       ["Reduce the lithium dose by half and review in one week",
        "Cease lithium and the NSAID, give IV sodium chloride 0.9%, and discuss urgent haemodialysis given the level and neurotoxicity",
        "Administer activated charcoal",
        "Continue lithium with increased oral fluids",
        "Switch lithium to sodium valproate today and discharge"],
       "B",
       "He has moderate-severe chronic lithium toxicity precipitated by the classic combination of an NSAID (which reduces renal lithium clearance) and dehydration. Management is immediate cessation of lithium and the precipitant, IV isotonic saline to restore volume and promote renal excretion, and serial levels - but with a level above 2.5 mmol/L, significant neurotoxicity and renal impairment, haemodialysis is indicated because lithium is an ideal dialysable toxin and prolonged neurotoxicity can become irreversible (the SILENT syndrome). Activated charcoal does not bind lithium. Dose reduction or simply pushing oral fluids drastically undertreats established toxicity, and same-day discharge on a new agent is unsafe.",
       "Lithium toxicity is precipitated by NSAIDs, diuretics, ACE inhibitors and dehydration: stop the drug, fill the tank with saline, and dialyse severe cases - charcoal is useless.",
       "Therapeutic Guidelines: Psychotropic / RANZCP guidance"),

    _q("Psychiatry", "First-episode psychosis", "medium",
       "A 19-year-old university student is brought in by his parents with 3 months of social withdrawal, deteriorating grades, and a belief that his lecturers are inserting thoughts into his head. He hears two voices discussing him. Urine drug screen is negative and physical examination, bloods and neurological assessment are unremarkable. He is not aggressive and has some insight that 'something is wrong'. What is the most appropriate management?",
       ["High-dose haloperidol and compulsory admission",
        "Watchful waiting for 6 months as this may resolve",
        "Referral to an early psychosis service and commencement of a low-dose atypical antipsychotic with psychosocial support",
        "Diazepam alone to settle the symptoms",
        "Long-acting depot antipsychotic at first presentation"],
       "C",
       "Three months of thought insertion, third-person auditory hallucinations and functional decline in a young adult with negative organic workup is first-episode psychosis. Best practice is engagement with a specialised early psychosis service and a low-dose second-generation antipsychotic - first-episode patients respond to lower doses but are exquisitely sensitive to adverse effects, so 'start low, go slow' applies - combined with family and psychosocial intervention. Reducing the duration of untreated psychosis improves long-term outcome, so months of watchful waiting are harmful, while a cooperative, non-aggressive patient with partial insight can be treated voluntarily. High-dose typical agents and depot preparations are not appropriate initiation strategies at first presentation.",
       "First-episode psychosis: early psychosis service plus low-dose atypical antipsychotic - shortening untreated psychosis changes the trajectory.",
       "RANZCP schizophrenia guidelines / Orygen early psychosis guidance"),

    _q("Psychiatry", "Serotonin syndrome", "hard",
       "A 42-year-old woman on sertraline 100 mg daily was started on tramadol after dental surgery 3 days ago. She presents agitated and diaphoretic with temperature 38.8 C, HR 124, BP 158/96 mmHg, dilated pupils, hyperreflexia, and sustained ankle clonus that is more marked in the lower limbs. What is the most likely diagnosis and initial management?",
       ["Neuroleptic malignant syndrome - give dantrolene",
        "Serotonin syndrome - cease the serotonergic agents, give IV fluids and benzodiazepines, with cyproheptadine if symptoms persist",
        "Anticholinergic toxicity - give physostigmine",
        "Sepsis - blood cultures and broad-spectrum antibiotics",
        "Thyroid storm - propranolol and carbimazole"],
       "B",
       "The triad of autonomic instability, neuromuscular hyperactivity and altered mental status developing rapidly after adding tramadol (a serotonin reuptake inhibitor and common culprit) to an SSRI is serotonin syndrome; lower-limb-predominant hyperreflexia and spontaneous or inducible clonus are its most specific signs. Management is cessation of all serotonergic agents, IV fluids, benzodiazepines for agitation and muscle activity, active cooling, and the serotonin antagonist cyproheptadine for persisting moderate cases. Neuroleptic malignant syndrome is the key distractor but develops over days in dopamine-antagonist users with lead-pipe rigidity and hyporeflexia, not clonus. Anticholinergic toxicity has dry skin rather than diaphoresis, and sepsis does not explain clonus and mydriasis with this drug history.",
       "Clonus and hyperreflexia after an SSRI-tramadol combination = serotonin syndrome; NMS is rigid and hyporeflexic, serotonin syndrome is clonic and hyperreflexic.",
       "Therapeutic Guidelines: Psychotropic / RANZCP guidance"),

    _q("Psychiatry", "Postpartum psychosis", "medium",
       "A community midwife reviews a 30-year-old woman 6 days after her first delivery. The woman has barely slept for 3 nights, is talking rapidly, and says she has discovered the baby has a 'special divine purpose' and that hospital staff implanted a device in him. Her partner says she is 'not herself at all'. She denies any thoughts of harming the baby. What is the most appropriate management?",
       ["Reassure - postpartum blues are common and self-limiting",
        "Commence an SSRI via the GP and review in 2 weeks",
        "Same-day psychiatric assessment and admission, preferably to a mother-and-baby unit, as a psychiatric emergency",
        "Refer to a parenting support group",
        "Advise the partner to monitor her at home and call if she worsens"],
       "C",
       "Acute onset of psychotic symptoms, grandiose and persecutory delusions involving the infant, pressured speech and profound sleep disturbance in the first postpartum week is puerperal psychosis - a psychiatric emergency with significant risk of suicide and, less commonly, infanticide, which can escalate within hours. It mandates same-day specialist assessment and almost always admission, ideally to a mother-and-baby unit so the dyad stays together while she is treated, with the baby never left in her unsupervised care in the interim. Postpartum blues are mild, transient mood lability without psychosis, peaking around days 3-5; postnatal depression treated with an SSRI develops more gradually and lacks delusions. Denial of harmful thoughts is not reassuring when delusions involve the baby.",
       "Postpartum psychosis is an emergency: same-day assessment and mother-and-baby unit admission - never manage delusions about the infant in the community.",
       "RANZCP perinatal guidance / SA Health Perinatal Practice Guidelines"),

    _q("Psychiatry", "Wernicke encephalopathy", "medium",
       "A 52-year-old man who drinks 120 g of alcohol daily is admitted with a chest infection. On day 2 he becomes confused, with horizontal nystagmus, bilateral lateral rectus weakness and a broad-based ataxic gait. Blood glucose is 4.8 mmol/L. What is the most appropriate immediate management?",
       ["Oral thiamine 100 mg daily",
        "IV high-dose thiamine (e.g. 500 mg three times daily) before any glucose-containing fluids, plus a benzodiazepine withdrawal scale",
        "IV 5% dextrose for nutritional support, then oral vitamins",
        "CT brain and await results before treatment",
        "Haloperidol for agitation and observation"],
       "B",
       "Confusion, ophthalmoplegia and ataxia in a heavy drinker is Wernicke encephalopathy, a medical emergency caused by thiamine deficiency; untreated, it progresses to irreversible Korsakoff syndrome or death. Treatment is immediate high-dose parenteral thiamine - oral absorption is unreliable in alcohol-dependent patients and oral dosing is only prophylactic - and it must be given before glucose-containing fluids, because a carbohydrate load in a thiamine-deplete patient can precipitate or worsen the encephalopathy. He also needs structured alcohol-withdrawal management with a benzodiazepine scale, magnesium replacement (a cofactor for thiamine), and supportive care. Imaging must not delay treatment in a clinically diagnosable emergency, and antipsychotics alone address nothing.",
       "Confusion + ophthalmoplegia + ataxia in a drinker = IV high-dose thiamine immediately, always before glucose.",
       "Therapeutic Guidelines: Psychotropic / RACGP alcohol guidelines"),

    # ---------------- ETHICS (5) ----------------
    _q("Ethics", "Refusal of treatment", "medium",
       "A 44-year-old Jehovah's Witness presents with melaena and haemoglobin 62 g/L. She is alert, orientated, understands that refusing transfusion may lead to her death, and consistently declines all blood products, consistent with a signed advance care directive she carries. Her husband, also a Witness, supports her decision, but her sister demands the team transfuse her. What is the most appropriate course of action?",
       ["Transfuse once she loses consciousness, as consent is then not required",
        "Apply to a tribunal to override her refusal",
        "Respect her refusal, document capacity and the directive, and optimise all non-transfusion measures (IV iron, endoscopic haemostasis, antifibrinolytics, cell salvage where acceptable)",
        "Transfuse on the sister's request as next of kin",
        "Sedate her and transfuse covertly to save her life"],
       "C",
       "A competent adult has an absolute right to refuse any medical treatment, including life-saving transfusion, and her refusal here is informed, consistent, and reinforced by a valid advance care directive that remains binding if she loses capacity - losing consciousness does not nullify a refusal made precisely for that circumstance. Relatives have no authority to override a competent patient's decision or a valid directive, and covert treatment would constitute battery. Tribunals do not overturn capacitous refusals in adults. The clinical duty that remains is to treat her as fully as possible within her limits: urgent endoscopic control of bleeding, IV iron, tranexamic acid, erythropoiesis support, and clarifying which fractionated products or cell salvage she individually accepts.",
       "A capacitous, informed refusal of blood binds the team even after consciousness is lost - treat aggressively within the patient's stated limits.",
       "AHPRA Good Medical Practice / Medical Board of Australia guidance"),

    _q("Ethics", "Confidentiality and partner notification", "hard",
       "A 33-year-old man is diagnosed with HIV. After three counselling sessions he remains adamant that he will not tell his long-term girlfriend, with whom he has condomless sex, and refuses to let anyone else tell her. He is not yet established on antiretroviral therapy. What is the most appropriate course of action?",
       ["Maintain absolute confidentiality - his diagnosis can never be disclosed",
        "Immediately telephone the girlfriend yourself without telling him",
        "Continue counselling towards voluntary disclosure while involving the public health unit, which can authorise contact tracing or disclosure to the at-risk partner if he persistently refuses",
        "Refuse to continue treating him until he tells her",
        "Report him to the police"],
       "C",
       "Confidentiality is fundamental but not absolute: every Australian jurisdiction's public health framework permits disclosure to prevent serious and imminent harm to an identifiable person, and an uninformed partner having ongoing condomless sex with an untreated HIV-positive man meets that threshold. The correct pathway is staged - continue counselling and support voluntary disclosure, optimise his care (effective treatment renders HIV untransmissible), and escalate to the public health unit, which manages contact tracing and can authorise notification of the partner if he persistently refuses. Unilateral disclosure by the clinician bypasses the lawful process and should only ever be a last resort within that framework; conversely, doing nothing abandons an identifiable person to preventable harm. Abandoning the patient or involving police is punitive and counter-therapeutic.",
       "Confidentiality yields to serious imminent harm to an identifiable person - but escalate through counselling and the public health unit, not unilateral disclosure.",
       "AHPRA Good Medical Practice / ASHM HIV guidance"),

    _q("Ethics", "Impaired colleague", "medium",
       "You are a junior doctor on a surgical team. You notice the consultant anaesthetist for this morning's list smells of alcohol, has slurred speech and fumbles while drawing up drugs. He insists he is fine and tells you to mind your own business. What is the most appropriate immediate action?",
       ["Say nothing - he is senior and it is not your place",
        "Take immediate steps to prevent him practising today by informing the most senior available clinician/medical administrator, and ensure a mandatory notification to AHPRA is made",
        "Document your concerns privately and raise them at the next audit meeting",
        "Confront him again after the list is finished",
        "Report him anonymously on social media"],
       "B",
       "Patients are about to be anaesthetised by a practitioner showing signs of acute intoxication, so the first duty is immediate protection of patients: escalate now to the senior clinician or medical administrator on site so he does not start the list. Beyond that, practising while intoxicated by alcohol or drugs is one of the four categories of notifiable conduct under Australia's National Law (with sexual misconduct, practising with an impairment placing the public at risk, and significant departure from accepted standards), creating a mandatory obligation to notify AHPRA that applies to all registered practitioners, including juniors reporting seniors. Waiting until after the list, private documentation, or audit-meeting deferral all leave today's patients exposed; seniority never neutralises the obligation, and public shaming is both unprofessional and legally hazardous.",
       "An intoxicated practitioner is notifiable conduct: stop them practising today, then mandatory AHPRA notification - seniority is no shield.",
       "AHPRA mandatory notification guidelines / Medical Board of Australia"),

    _q("Ethics", "Advance care directives", "easy",
       "An 86-year-old man with advanced dementia is admitted from his nursing home with aspiration pneumonia. He has a valid advance care directive, completed when he had capacity, refusing intensive care admission, intubation and CPR, and naming his daughter as substitute decision-maker. He deteriorates despite ward-based antibiotics. His son, arriving from interstate, demands 'everything be done' including ICU transfer. What is the most appropriate action?",
       ["Transfer to ICU as the son requests to avoid conflict",
        "Follow the advance care directive: continue ward-based and comfort-focused treatment, and communicate openly with the family about its binding nature",
        "Ask the hospital lawyer to decide before any further treatment",
        "Provide CPR but not intubation as a compromise",
        "Let the son and daughter vote on the management plan"],
       "B",
       "A valid advance care directive completed with capacity is the patient's own voice and takes precedence over the wishes of any family member - including the appointed substitute decision-maker, whose role is to honour the patient's documented preferences, not to overrule them. The correct course is to follow the directive, continue medically appropriate ward-level care with a comfort-oriented focus as he deteriorates, and invest time in compassionate communication with the son, who is often expressing grief and guilt rather than a genuine clinical disagreement. Escalating to ICU against the directive would constitute treatment without consent; 'compromise resuscitation' is incoherent and provides non-beneficial, harmful intervention. Legal input is for genuine doubt about validity, which does not exist here.",
       "A valid advance care directive speaks for the patient and outranks every family member - families are supported, not obeyed, when they contradict it.",
       "AHPRA Good Medical Practice / state advance care directive legislation"),

    _q("Ethics", "Mature minor and confidentiality", "medium",
       "A 15-year-old girl attends her GP alone requesting the oral contraceptive pill. She has been in a relationship with her 16-year-old boyfriend for 8 months and they are planning to become sexually active. She gives a clear account of the risks, benefits and alternatives, and asks that her parents not be told. There are no features of coercion, exploitation or abuse. What is the most appropriate course of action?",
       ["Refuse to prescribe without parental consent because she is under 16",
        "Assess her as a mature minor (Gillick competent); if competent, prescribe, maintain confidentiality, encourage parental involvement, and offer STI prevention advice",
        "Prescribe but telephone her parents afterwards to inform them",
        "Report the relationship to police as the partner is older",
        "Insist she return with a parent before any discussion"],
       "B",
       "Australian law, following Gillick and Marion's Case, recognises that a minor who demonstrates sufficient understanding and intelligence to comprehend the proposed treatment can consent on her own behalf, and a 15-year-old giving a clear account of risks, benefits and alternatives is likely to meet that standard. If assessed as competent, the GP should prescribe, preserve her confidentiality (breaching it would deter her from healthcare without preventing sexual activity), actively encourage but not require parental involvement, and address STI protection and the voluntariness of the relationship. A consensual relationship between a 15-year-old and a 16-year-old peer with no coercion does not constitute reportable abuse in this context. Refusing care or covertly informing parents both breach her rights and predictably lead to unprotected intercourse.",
       "A Gillick-competent minor can consent to contraception confidentially - assess competence and coercion, encourage but never require parental involvement.",
       "RACGP guidelines / Medical Board of Australia, Gillick competence principles"),

    # ---------------- EMERGENCY (5) ----------------
    _q("Emergency", "Tension pneumothorax", "easy",
       "A 24-year-old man is brought in after a motorbike crash. He is acutely breathless and agitated. Trachea is deviated to the left, the right chest is hyperresonant with absent breath sounds, neck veins are distended, BP 78/50 mmHg, HR 138, SpO2 84%. What is the most appropriate immediate action?",
       ["Portable chest X-ray to confirm the diagnosis",
        "CT chest",
        "Immediate needle decompression or finger thoracostomy of the right chest, followed by intercostal catheter insertion",
        "Endotracheal intubation as the first step",
        "IV fluid bolus and reassessment"],
       "C",
       "Tracheal deviation away from a hyperresonant, silent hemithorax with distended neck veins and obstructive shock after chest trauma is tension pneumothorax - a clinical diagnosis that must be treated the moment it is recognised. Immediate decompression by needle thoracocentesis (or finger thoracostomy, increasingly preferred in trauma) converts it to a simple pneumothorax, followed by formal intercostal catheter insertion. Any imaging before decompression is a potentially fatal delay - 'the only place a tension pneumothorax should be seen on X-ray is in a textbook'. Positive pressure ventilation before decompression dramatically worsens the tension physiology and can cause immediate arrest, and fluids do not treat the obstructed venous return.",
       "Tension pneumothorax is a clinical diagnosis: decompress first, image never (beforehand) - and beware positive pressure ventilation before the chest is vented.",
       "Australian Resuscitation Council / ARC and EMST trauma principles"),

    _q("Emergency", "Burns resuscitation", "hard",
       "An 80 kg man sustains flame burns at 1400 hours involving circumferential partial-thickness burns to both entire lower limbs, estimated at 27% total body surface area. He arrives at 1600 hours with IV access established. Using the modified Parkland formula (3 mL/kg/%TBSA), what crystalloid resuscitation does he require?",
       ["6,480 mL over 24 hours from arrival time, given at a constant rate",
        "6,480 mL over 24 hours from the time of the burn, with half (3,240 mL) in the first 8 hours post-burn - so 3,240 mL over the 6 hours remaining, then 3,240 mL over the following 16 hours, titrated to urine output",
        "2,000 mL stat then maintenance fluids only",
        "13,000 mL in the first 8 hours",
        "Colloid resuscitation with 4% albumin from the outset"],
       "B",
       "The modified Parkland calculation is 3 mL x 80 kg x 27% = 6,480 mL of crystalloid in the first 24 hours, with half given in the first 8 hours and half in the next 16 hours - but the clock starts at the time of injury, not arrival. Burned at 1400 and arriving at 1600, he has 6 hours left of the first 8-hour period in which to receive 3,240 mL. The formula is only a starting estimate: the resuscitation is titrated to a urine output of 0.5 mL/kg/hr, since both under- and over-resuscitation ('fluid creep') cause serious harm. Colloid is avoided in the first 24 hours while capillary leak is maximal. His circumferential limb burns also need vigilant assessment for compartment compromise and possible escharotomy.",
       "Parkland timing starts at the burn, not the door - half the volume in the first 8 hours post-injury, all titrated to urine output.",
       "ANZBA Emergency Management of Severe Burns / Australian Resuscitation Council"),

    _q("Emergency", "Snake bite", "medium",
       "A 35-year-old farmer in rural Queensland is bitten on the calf by an unidentified snake while clearing scrub. Ten minutes later he is asymptomatic with two puncture marks visible. The nearest hospital with antivenom is 60 minutes away. What is the most appropriate pre-hospital management?",
       ["Wash the bite site thoroughly and apply a tourniquet",
        "Cut and suck the wound to remove venom",
        "Apply a broad pressure-immobilisation bandage over the bite site and the entire limb, splint it, keep him completely still, and arrange urgent ambulance transport",
        "Walk him to the car quickly and drive to hospital",
        "Observe at home and only travel to hospital if symptoms develop"],
       "C",
       "Australian snake venoms spread via the lymphatics, so first aid is the pressure-immobilisation technique: a broad elastic bandage applied over the bite site then extended to cover the whole limb at the firmness used for a sprain, a splint, and absolute immobility of both limb and patient - muscle movement is the main driver of lymphatic flow. The wound must not be washed, because residual venom on the skin is what the venom detection kit swabs at hospital. Tourniquets, incision and suction are dangerous and obsolete. Walking the patient or watchful waiting at home are wrong because envenomation can evolve rapidly (coagulopathy, paralysis, rhabdomyolysis) and every suspected snakebite warrants hospital assessment with serial bloods even if asymptomatic.",
       "Australian snakebite: pressure-immobilisation bandage, splint, total stillness, hospital - and never wash the bite site.",
       "Australian Resuscitation Council / ARC guideline 9.4.1"),

    _q("Emergency", "Cardiac arrest", "easy",
       "A 58-year-old man collapses in the ED waiting room. He is unresponsive with no normal breathing. The defibrillator arrives as CPR is commenced, and the monitor shows ventricular fibrillation. What is the most appropriate immediate action?",
       ["Adrenaline 1 mg IV before any shock",
        "Amiodarone 300 mg IV before any shock",
        "Deliver a single DC shock at 200 J biphasic, then immediately resume CPR for 2 minutes before rhythm reassessment",
        "Three stacked shocks before resuming compressions",
        "Synchronised cardioversion at 100 J"],
       "C",
       "Ventricular fibrillation is a shockable rhythm, and the single most important determinant of survival is minimising time to defibrillation: ARC guidelines mandate a single unsynchronised shock (200 J biphasic) followed by immediate resumption of CPR for 2 minutes before the next rhythm check - pausing to reassess or palpate a pulse straight after the shock wastes perfusion time. Adrenaline is given after the second shock and amiodarone after the third in refractory VF; neither precedes defibrillation. Stacked shocks are reserved for witnessed monitored arrests with a defibrillator already attached (e.g. cath lab). Synchronised cardioversion is for perfusing tachyarrhythmias - there is nothing to synchronise to in VF.",
       "VF arrest: shock first and shock fast - one shock, straight back to compressions; drugs come after the second and third shocks.",
       "Australian Resuscitation Council / ARC ALS guidelines"),

    _q("Emergency", "Head injury on anticoagulation", "medium",
       "A 78-year-old woman on apixaban for atrial fibrillation trips at home and hits her head on the kitchen bench. In ED 2 hours later she is GCS 15 with a frontal scalp haematoma, no loss of consciousness, no vomiting, no focal neurology, and she feels 'fine, just embarrassed'. What is the most appropriate management?",
       ["Discharge home with standard head injury advice",
        "Discharge with instructions to return if she develops a headache",
        "Non-contrast CT brain now, despite her normal examination, because anticoagulation places her at high risk of intracranial haemorrhage",
        "Skull X-ray to exclude a fracture",
        "Admit for 24 hours of neurological observations without imaging"],
       "C",
       "Anticoagulant use is an independent high-risk criterion in every major head injury decision rule: even with a trivial mechanism and a normal examination, an anticoagulated elderly patient can harbour or develop an intracranial haemorrhage, and delayed deterioration is well described. The correct management is a non-contrast CT brain at presentation, and most Australian pathways also recommend a period of observation or safety-netting given the small risk of delayed bleeding on a DOAC even after a normal initial scan. Discharge without imaging accepts an unacceptable miss rate in this group, skull X-rays have no role in modern adult head injury assessment, and observation without imaging merely waits for a treatable haematoma to declare itself by deterioration.",
       "Any head injury on anticoagulation buys a CT brain regardless of how well the patient looks - normal examination does not exclude intracranial bleeding.",
       "RACGP guidelines / state emergency care head injury pathways"),
]
