def _q(subject, topic, difficulty, stem, options, correct, explanation, learning_point, reference):
    return {
        "subject": subject, "topic": topic, "difficulty": difficulty, "question_text": stem,
        "options": [
            {"letter": letter, "text": text, "is_correct": letter == correct}
            for letter, text in zip("ABCDE", options)
        ],
        "explanation": explanation, "learning_point": learning_point, "reference": reference,
    }


MCQS_1 = [
    # ---------------- MEDICINE ----------------
    _q("Medicine", "Atrial fibrillation", "medium",
       "A 68-year-old woman presents with 2 days of palpitations. Her pulse is irregularly irregular at 128 bpm, BP 142/88 mmHg. She is alert with no chest pain or dyspnoea. ECG confirms atrial fibrillation. What is the most appropriate initial management?",
       ["Immediate synchronised DC cardioversion",
        "Rate control with an oral beta-blocker and assessment for anticoagulation",
        "IV amiodarone for chemical cardioversion",
        "Aspirin alone and discharge with outpatient review",
        "IV adenosine to terminate the arrhythmia"],
       "B",
       "This patient is haemodynamically stable with AF of uncertain total duration (symptomatic for 2 days). The safest strategy is rate control with a beta-blocker and a formal stroke-risk assessment (CHA2DS2-VA) for anticoagulation. Cardioversion (electrical or chemical) without 3 weeks of anticoagulation or TOE exclusion of atrial thrombus risks embolic stroke once duration exceeds 48 hours or is uncertain. Adenosine blocks the AV node transiently and neither terminates nor controls AF. Aspirin is not adequate thromboprophylaxis in AF.",
       "Stable AF >48h or of uncertain duration: rate control + anticoagulation; do not cardiovert without anticoagulation cover or TOE.",
       "RACGP / Australian AF guidelines"),

    _q("Medicine", "Wolff-Parkinson-White", "hard",
       "A 24-year-old man presents with palpitations. ECG shows an irregular broad-complex tachycardia at 220 bpm with QRS complexes of varying morphology. His BP is 108/70 mmHg. He had a previous ECG showing a short PR interval and delta waves. Which treatment is contraindicated?",
       ["Synchronised DC cardioversion",
        "IV procainamide",
        "IV verapamil",
        "Expert electrophysiology consultation",
        "Catheter ablation after stabilisation"],
       "C",
       "This is pre-excited atrial fibrillation in WPW syndrome — irregular, broad, very fast with beat-to-beat QRS variation. AV-nodal blocking agents (verapamil, diltiazem, beta-blockers, digoxin, adenosine) are contraindicated: blocking the AV node funnels all conduction down the accessory pathway, which lacks decremental properties, and can accelerate the ventricular response into VF. Safe options are IV procainamide or synchronised cardioversion (mandatory if unstable). Definitive cure is accessory-pathway ablation.",
       "In AF with WPW, never give AV-nodal blockers — use procainamide or DC cardioversion.",
       "RACGP / cardiology society guidance"),

    _q("Medicine", "Acute coronary syndrome", "medium",
       "A 58-year-old man with hypertension presents with 40 minutes of central crushing chest pain radiating to the jaw. ECG shows 3 mm ST elevation in V2–V4. The nearest PCI-capable centre is 3 hours away by road. Symptom onset was 1 hour ago. What is the most appropriate reperfusion strategy?",
       ["Transfer for primary PCI",
        "Immediate fibrinolysis, then transfer to a PCI-capable centre",
        "Aspirin, clopidogrel and heparin alone with admission to the local ward",
        "IV GTN infusion and serial troponins",
        "Urgent echocardiogram before any reperfusion"],
       "B",
       "This is an anterior STEMI presenting within 1 hour of onset. Primary PCI is preferred only when achievable within 90 minutes of first medical contact; a 3-hour transfer exceeds this. The correct rural Australian strategy is immediate fibrinolysis (e.g. tenecteplase) within 30 minutes, followed by routine transfer to a PCI centre for angiography within 24 hours (or rescue PCI if reperfusion fails at 60–90 minutes). Antithrombotics alone deny the patient reperfusion; imaging must not delay it.",
       "STEMI with PCI unavailable within 90 minutes: fibrinolyse then transfer — the classic rural Australia scenario.",
       "RACGP / NHFA-CSANZ ACS guidelines"),

    _q("Medicine", "Heart failure", "medium",
       "A 70-year-old woman with ischaemic cardiomyopathy (LVEF 30%) is reviewed in clinic. She is comfortable at rest with mild exertional dyspnoea. Current therapy: ramipril and furosemide. BP 124/76, HR 78, K+ 4.2, eGFR 55. What is the most appropriate next step to improve survival?",
       ["Increase furosemide",
        "Add digoxin",
        "Add a beta-blocker such as bisoprolol and plan stepwise addition of an MRA and SGLT2 inhibitor",
        "Add amlodipine",
        "Refer for immediate ICD implantation"],
       "C",
       "HFrEF survival is improved by four foundation therapies: ACE inhibitor/ARNI, evidence-based beta-blocker, mineralocorticoid receptor antagonist, and SGLT2 inhibitor. She is on only one. The next step is to add a beta-blocker while euvolaemic and then complete the quadruple therapy. Furosemide relieves congestion but does not improve survival; digoxin helps symptoms/admissions only. ICD consideration comes after optimised medical therapy if LVEF remains ≤35%.",
       "Loop diuretics treat symptoms; the four pillars (ACEi/ARNI, BB, MRA, SGLT2i) treat mortality.",
       "RACGP / NHFA heart failure guidelines"),

    _q("Medicine", "COPD", "easy",
       "A 72-year-old man with severe COPD presents drowsy with an exacerbation. SpO2 is 84% on room air. He is given high-flow oxygen 15 L/min via non-rebreather. Thirty minutes later he is more drowsy. ABG: pH 7.24, pCO2 78 mmHg, pO2 110 mmHg. What is the most appropriate next step?",
       ["Continue high-flow oxygen and observe",
        "Reduce oxygen to target SpO2 88–92% and commence non-invasive ventilation (BiPAP)",
        "Intubate immediately",
        "Give IV sodium bicarbonate",
        "Stop oxygen completely"],
       "B",
       "He has developed oxygen-induced hypercapnic respiratory failure with acidaemia (pH 7.24, CO2 78). The correct response is titrating oxygen to the COPD target of 88–92% and starting BiPAP, which is first-line for acute hypercapnic respiratory failure with pH <7.35. Stopping oxygen entirely causes dangerous hypoxia; immediate intubation is not yet indicated when NIV is available and he is rousable; bicarbonate does not treat the cause.",
       "Titrate O2 to 88–92% in COPD; respiratory acidosis pH <7.35 despite controlled O2 = NIV.",
       "RACGP / COPD-X guidelines"),

    _q("Medicine", "Asthma", "medium",
       "A 28-year-old woman with asthma uses a salbutamol inhaler alone, 4–5 times weekly, with night waking once a fortnight. Spirometry confirms variable airflow obstruction. According to current Australian guidance, what is the most appropriate treatment?",
       ["Continue salbutamol as needed",
        "Commence low-dose budesonide-formoterol as an anti-inflammatory reliever",
        "Commence high-dose inhaled corticosteroid with a spacer",
        "Commence oral montelukast",
        "Commence a long-acting muscarinic antagonist"],
       "B",
       "SABA-only management is no longer recommended for adults and adolescents — it does not treat underlying inflammation and is associated with increased severe exacerbations and asthma death. With symptoms more than twice a week, the preferred Australian option is low-dose ICS-formoterol used as an anti-inflammatory reliever (AIR), or regular low-dose ICS plus SABA. High-dose ICS, montelukast, and LAMA are not appropriate starting points.",
       "Adults with asthma should not be on SABA monotherapy — anti-inflammatory reliever therapy is first-line.",
       "RACGP / Australian Asthma Handbook"),

    _q("Medicine", "Pulmonary embolism", "medium",
       "A 45-year-old woman presents with pleuritic chest pain and dyspnoea 10 days after a knee replacement. HR 118, BP 88/54, SpO2 89%. Bedside echo shows a dilated, hypokinetic right ventricle. CTPA confirms large bilateral proximal pulmonary emboli. What is the most appropriate management?",
       ["Therapeutic enoxaparin alone",
        "Apixaban orally",
        "Systemic thrombolysis with alteplase",
        "Inferior vena cava filter insertion",
        "Urgent surgical embolectomy as first-line"],
       "C",
       "She has massive (high-risk) PE: confirmed PE with sustained hypotension and RV dysfunction. Systemic thrombolysis is first-line in massive PE unless absolutely contraindicated — anticoagulation alone is insufficient because it prevents propagation but does not lyse the obstructing clot rapidly enough to reverse shock. Recent surgery is a relative contraindication requiring risk–benefit judgement, but in circulatory collapse thrombolysis (or embolectomy where lysis is truly contraindicated and surgery available) remains the answer; embolectomy is not first-line where lysis is possible.",
       "PE + hypotension = massive PE = thrombolysis, not anticoagulation alone.",
       "RACGP / thrombosis guidelines"),

    _q("Medicine", "Type 2 diabetes", "easy",
       "A 54-year-old man has a new diagnosis of type 2 diabetes (HbA1c 7.8%) with stable ischaemic heart disease and an eGFR of 52. Beyond lifestyle modification, which initial pharmacological combination is most appropriate?",
       ["Metformin alone",
        "Metformin plus an SGLT2 inhibitor",
        "Sulfonylurea plus metformin",
        "Basal insulin",
        "DPP-4 inhibitor alone"],
       "B",
       "Metformin remains first-line, but in patients with established cardiovascular disease or chronic kidney disease, an SGLT2 inhibitor should be added early — independent of HbA1c — for its proven cardiovascular and renal protection. Sulfonylureas and DPP-4 inhibitors offer no such outcome benefit, and insulin is not indicated at this HbA1c without symptoms.",
       "Comorbidity drives second-agent choice: CVD/CKD/HF → SGLT2 inhibitor (or GLP-1 RA for ASCVD/obesity).",
       "RACGP Management of type 2 diabetes handbook"),

    _q("Medicine", "Hyperthyroidism", "medium",
       "A 32-year-old woman on carbimazole for Graves disease presents with fever 38.6°C and severe sore throat. What is the most important immediate action?",
       ["Prescribe oral antibiotics and review in 48 hours",
        "Stop carbimazole and obtain an urgent full blood count",
        "Increase the carbimazole dose to control thyrotoxicosis",
        "Switch carbimazole to propylthiouracil",
        "Arrange thyroid function tests and review next week"],
       "B",
       "Fever and sore throat in a patient taking carbimazole is agranulocytosis until proven otherwise — an idiosyncratic, potentially fatal reaction occurring in ~0.2–0.5%. The drug must be stopped immediately and an urgent neutrophil count obtained; if neutropenic, she needs admission, cultures and broad-spectrum antibiotics. Continuing or increasing the drug, or deferring assessment, risks overwhelming sepsis. PTU carries the same risk so switching does not address the emergency.",
       "Carbimazole + fever/sore throat = stop drug + urgent FBC.",
       "RACGP / Therapeutic Guidelines: Endocrinology"),

    _q("Medicine", "Chronic kidney disease", "medium",
       "A 60-year-old man with type 2 diabetes has eGFR 48 and urine ACR 35 mg/mmol. BP 148/92 on amlodipine. Two weeks after his GP adds an ACE inhibitor, creatinine has risen from 130 to 152 µmol/L (17%) and K+ is 5.0. What is the most appropriate action?",
       ["Stop the ACE inhibitor permanently",
        "Halve the amlodipine dose",
        "Continue the ACE inhibitor and recheck renal function and potassium in 1–2 weeks",
        "Switch the ACE inhibitor to an ARB",
        "Refer urgently for renal artery stenosis imaging"],
       "C",
       "A creatinine rise of up to 25–30% with K+ ≤5.5 after starting an ACE inhibitor reflects reduced intraglomerular pressure — the very mechanism that confers long-term renoprotection in albuminuric CKD — and is an indication to continue with early re-checking, not to stop. Stopping would deny him the most evidence-based therapy for diabetic kidney disease with albuminuria. An ARB would behave identically. Investigation for renal artery stenosis is reserved for rises >30% or resistant features.",
       "Expect and tolerate a <25–30% creatinine rise after ACEi initiation in CKD — continue and monitor.",
       "RACGP / KHA-CARI CKD guidance"),

    _q("Medicine", "Stroke", "medium",
       "A 76-year-old woman is brought in 90 minutes after sudden right-sided weakness and aphasia. BP 168/94, BSL 6.2. Non-contrast CT shows no haemorrhage and no established infarct. NIHSS is 14. What is the most appropriate immediate management?",
       ["Aspirin 300 mg now",
        "IV thrombolysis and CT angiography to assess for endovascular thrombectomy",
        "Therapeutic heparin infusion",
        "BP reduction to below 140/90 before any treatment",
        "MRI brain before any reperfusion decision"],
       "B",
       "She is within the 4.5-hour thrombolysis window with a disabling deficit, no haemorrhage on CT, and BP below the 185/110 threshold — IV thrombolysis is indicated without delay, and CT angiography should identify large vessel occlusion for endovascular thrombectomy (her NIHSS suggests this is likely). Aspirin is withheld for 24 hours after lysis. Heparin has no role in acute ischaemic stroke. Aggressive BP lowering below 140 is not required pre-lysis and MRI would introduce unacceptable delay.",
       "Time is brain: thrombolyse eligible patients within 4.5h and screen for thrombectomy with CTA.",
       "RACGP / Stroke Foundation Clinical Guidelines"),

    _q("Medicine", "TIA", "medium",
       "A 69-year-old man had 20 minutes of left arm weakness and slurred speech this morning, now fully resolved. He is in sinus rhythm. CT brain is normal. What is the most appropriate management?",
       ["Reassure and review in one week",
        "Aspirin 300 mg now, same-day carotid imaging, ECG and specialist review, with dual antiplatelet therapy for high-risk TIA",
        "Warfarin loading",
        "Outpatient MRI in 2–3 weeks then review",
        "Admit for thrombolysis"],
       "B",
       "TIA confers the greatest stroke risk within the first 48 hours, so assessment and secondary prevention are same-day obligations: immediate aspirin 300 mg once haemorrhage is excluded, urgent carotid imaging (symptomatic 70–99% stenosis warrants endarterectomy within 2 weeks), cardiac rhythm assessment for AF, and risk-factor control. High-risk TIA/minor stroke benefits from 21 days of dual antiplatelet therapy then single-agent. Anticoagulation is only for AF; thrombolysis treats persisting deficits, not resolved ones.",
       "TIA = medical emergency: same-day workup and immediate antiplatelet therapy, not routine outpatient referral.",
       "RACGP / Stroke Foundation Clinical Guidelines"),

    _q("Medicine", "Infective endocarditis", "medium",
       "A 38-year-old man who injects drugs presents with 10 days of fevers and a new pansystolic murmur at the left sternal edge. He has crackles in both lung fields and CXR shows multiple peripheral cavitating opacities. What is the most likely diagnosis?",
       ["Left-sided mitral endocarditis with septic brain emboli",
        "Tricuspid valve endocarditis with septic pulmonary emboli",
        "Miliary tuberculosis",
        "Lung abscesses from aspiration",
        "Granulomatosis with polyangiitis"],
       "B",
       "In people who inject drugs, endocarditis is classically right-sided (tricuspid), usually Staphylococcus aureus. Vegetations embolise to the lungs producing multiple peripheral, often cavitating, septic pulmonary emboli — exactly the CXR described — with a tricuspid regurgitant murmur at the left sternal edge. Left-sided disease embolises systemically (brain, spleen, kidneys), not to the lungs. The management priorities are three sets of blood cultures then empirical IV anti-staphylococcal therapy.",
       "IVDU + fever + cavitating lung lesions = tricuspid endocarditis with septic pulmonary emboli.",
       "RACGP / Therapeutic Guidelines: Antibiotic"),

    _q("Medicine", "First seizure", "medium",
       "A 26-year-old man has a witnessed first generalised tonic-clonic seizure. He has recovered fully. Glucose, electrolytes, ECG and CT brain are normal; EEG is pending. He drives a private car to work. Which statement about management is correct?",
       ["He must start an antiseizure medication immediately",
        "He should be advised not to drive, with the advice documented, and investigated with EEG and MRI before any decision on therapy",
        "He can continue driving if the EEG is normal",
        "He requires lifelong sodium valproate",
        "He should be admitted for 48 hours of observation"],
       "B",
       "After a single unprovoked seizure with normal initial work-up, antiseizure medication is usually not started — recurrence risk is roughly 40–50%, and treatment decisions await EEG and MRI findings. What is mandatory is driving advice: Austroads standards require a seizure-free period (typically around 6 months for private licences, subject to specialist review) and this advice must be clearly documented. A normal EEG does not restore driving eligibility, and admission adds nothing in a fully recovered patient.",
       "First seizure: investigate before treating, and always document driving cessation advice.",
       "RACGP / Austroads Assessing Fitness to Drive"),

    _q("Medicine", "Hypothyroidism", "easy",
       "A 78-year-old woman with ischaemic heart disease is diagnosed with primary hypothyroidism (TSH 28 mIU/L, low fT4). What is the most appropriate initial management?",
       ["Levothyroxine 1.6 µg/kg daily from the outset",
        "Levothyroxine 25 µg daily, titrating slowly with TSH monitoring every 6–8 weeks",
        "Liothyronine (T3) replacement",
        "No treatment unless she becomes symptomatic",
        "Carbimazole"],
       "B",
       "In elderly patients and those with ischaemic heart disease, thyroxine is started low (25 µg, sometimes 12.5 µg) and titrated slowly, because full replacement abruptly increases myocardial oxygen demand and can precipitate angina, infarction or arrhythmia. Full-dose initiation suits young, otherwise healthy patients. TSH is rechecked 6–8 weeks after each change. T3 is not standard therapy; with TSH 28 and symptoms-producing biochemistry, withholding treatment is wrong.",
       "Start low, go slow with thyroxine in the elderly and in ischaemic heart disease.",
       "RACGP / Therapeutic Guidelines: Endocrinology"),

    _q("Medicine", "UTI", "easy",
       "A 26-year-old non-pregnant woman has two days of dysuria and frequency without fever or loin pain. Urine dipstick shows nitrites and leucocytes. What is the most appropriate management?",
       ["Await urine culture before treating",
        "Trimethoprim 300 mg nocte for 3 days",
        "Ciprofloxacin 500 mg bd for 7 days",
        "IV gentamicin",
        "Cranberry juice and review in one week"],
       "B",
       "This is uncomplicated acute cystitis. Australian first-line empirical therapy is trimethoprim 300 mg nocte for 3 days (alternatives: nitrofurantoin 100 mg bd for 5 days, cephalexin). Culture before treatment is unnecessary in uncomplicated cystitis — empirical treatment is appropriate, reserving culture for treatment failure, recurrence, pregnancy, men, or complicated infection. Quinolones are never first-line for cystitis in Australia; gentamicin is for severe pyelonephritis/sepsis.",
       "Uncomplicated cystitis in non-pregnant women: empirical trimethoprim 3 days, no culture needed.",
       "RACGP / Therapeutic Guidelines: Antibiotic"),

    # ---------------- EMERGENCY ----------------
    _q("Emergency", "Anaphylaxis", "easy",
       "A 19-year-old develops widespread urticaria, lip swelling, wheeze and dizziness minutes after eating satay chicken. BP 86/50, HR 124. What is the immediate management?",
       ["IV hydrocortisone 200 mg",
        "Oral cetirizine and observation",
        "IM adrenaline 0.5 mg (1:1000) into the lateral thigh, lying the patient flat",
        "Nebulised salbutamol",
        "IV adrenaline 1 mg bolus"],
       "C",
       "This is anaphylaxis with circulatory and respiratory involvement. The single life-saving intervention is intramuscular adrenaline 0.01 mg/kg (max 0.5 mg) of 1:1000 into the anterolateral thigh, repeated every 5 minutes as required, with the patient kept supine — standing can cause fatal empty-ventricle arrest. Steroids and antihistamines are adjuncts at best and never precede adrenaline; nebulised salbutamol may help bronchospasm only after adrenaline. IV bolus adrenaline 1 mg is a cardiac-arrest dose and dangerous here.",
       "Anaphylaxis: IM adrenaline first, patient flat — everything else is secondary.",
       "ASCIA / RCH anaphylaxis guidelines"),

    _q("Emergency", "Sepsis", "medium",
       "A 64-year-old woman presents febrile and confused, BP 84/52, HR 122, lactate 4.8 mmol/L, likely urinary source. Within the first hour, which set of actions is most appropriate?",
       ["Await urine culture results before antibiotics",
        "Blood cultures, IV broad-spectrum antibiotics, 30 mL/kg crystalloid, and lactate remeasurement",
        "CT abdomen before any treatment",
        "Oral antibiotics and observation in ED",
        "Vasopressors first, then antibiotics once BP normalises"],
       "B",
       "She has septic shock criteria (hypotension, lactate >4, organ dysfunction). The sepsis bundle requires completion within 60 minutes: cultures before antibiotics (without delaying them), broad-spectrum IV antibiotics, 30 mL/kg crystalloid for hypotension or lactate ≥4, and serial lactate to gauge response. Noradrenaline follows if MAP remains <65 after fluids — it complements rather than precedes antibiotics and fluid. Imaging for source control comes after resuscitation has begun.",
       "Sepsis: cultures, antibiotics, 30 mL/kg fluids and lactate within the first hour.",
       "Surviving Sepsis / state sepsis pathways"),

    _q("Emergency", "Overdose", "hard",
       "A 21-year-old woman presents 6 hours after ingesting an unknown quantity of her grandmother's amitriptyline. She is drowsy. ECG shows sinus tachycardia 130 with QRS 128 ms. What is the most appropriate immediate treatment?",
       ["Activated charcoal",
        "IV sodium bicarbonate boluses",
        "IV flumazenil",
        "Synchronised cardioversion",
        "IV lidocaine"],
       "B",
       "TCA toxicity causes sodium-channel blockade: QRS widening >100 ms predicts seizures and >160 ms predicts ventricular arrhythmias. The treatment is IV sodium bicarbonate boluses (1–2 mmol/kg), repeated targeting QRS narrowing and pH 7.45–7.55 — serum alkalinisation and sodium loading displace the drug from cardiac sodium channels. Charcoal is futile and unsafe at 6 hours with drowsiness. Flumazenil can precipitate refractory seizures. Cardioversion does not treat the channel blockade driving the conduction delay.",
       "Wide QRS in TCA overdose = sodium bicarbonate; intubate early and avoid flumazenil.",
       "Therapeutic Guidelines: Toxicology / Poisons Information Centre"),

    _q("Emergency", "Paracetamol overdose", "medium",
       "A 17-year-old presents 5 hours after ingesting 16 g of paracetamol. She is asymptomatic. What is the most appropriate management?",
       ["Discharge with outpatient liver function testing in 48 hours",
        "Take a paracetamol level now and start N-acetylcysteine if above the nomogram treatment line",
        "Activated charcoal now",
        "Start N-acetylcysteine only if ALT is elevated",
        "Observe for 24 hours and treat if she becomes symptomatic"],
       "B",
       "At 16 g (well above the 10 g / 200 mg/kg risk threshold) and 5 hours post-ingestion, a serum paracetamol level should be plotted on the treatment nomogram (valid 4–8+ hours post-ingestion) and N-acetylcysteine started if above the line — NAC is virtually 100% hepatoprotective when begun within 8 hours. Waiting for symptoms or ALT rise means waiting for established hepatotoxicity; charcoal is most useful within 2 hours of ingestion. All deliberate self-poisonings also require psychiatric assessment.",
       "NAC within 8 hours prevents hepatotoxicity — level at 4+ hours, plot on the nomogram, treat above the line.",
       "Therapeutic Guidelines: Toxicology / Australian paracetamol guidelines"),

    _q("Emergency", "Chest pain approach", "hard",
       "A 62-year-old hypertensive man presents with sudden severe tearing chest pain radiating to the interscapular region. BP is 196/104 in the right arm and 158/88 in the left. ECG shows 1 mm inferior ST elevation. What is the most appropriate next step?",
       ["Immediate fibrinolysis for inferior STEMI",
        "Aspirin, ticagrelor and heparin",
        "Urgent CT aortogram and IV beta-blockade titrated to systolic BP 100–120 mmHg",
        "IV GTN alone and serial troponins",
        "Bedside transthoracic echo and discharge if normal"],
       "C",
       "Tearing interscapular pain, marked inter-arm BP differential and hypertension point to acute aortic dissection; a type A dissection can involve the right coronary ostium and mimic inferior STEMI. Thrombolysis or aggressive antithrombotic therapy here is potentially lethal. The correct approach is urgent CT aortography with simultaneous heart-rate/BP control using IV beta-blockade (e.g. esmolol) targeting SBP 100–120, and immediate cardiothoracic referral if type A is confirmed.",
       "Inferior ST elevation + tearing pain + pulse/BP differential = dissection until CT proves otherwise — no lysis, no anticoagulation.",
       "RACGP / emergency medicine references"),

    _q("Emergency", "Altered consciousness", "easy",
       "A 54-year-old man with type 1 diabetes is found unresponsive. GCS 6, sweaty, HR 110. What is the first investigation?",
       ["CT brain",
        "Capillary blood glucose",
        "Arterial blood gas",
        "ECG",
        "Serum ammonia"],
       "B",
       "Hypoglycaemia is the most rapidly fatal yet most rapidly reversible cause of coma and is overwhelmingly likely in an insulin-treated diabetic who is sweaty and tachycardic. A capillary glucose takes seconds and, if low, IV dextrose (or IM glucagon without IV access) restores consciousness — sparing the patient an unnecessary CT and intubation. Every reduced-GCS algorithm begins with 'Don't Ever Forget Glucose' alongside airway protection.",
       "Check the glucose first in any patient with altered consciousness.",
       "RACGP / emergency medicine references"),

    _q("Emergency", "Headache", "medium",
       "A 39-year-old woman presents with the sudden onset of the worst headache of her life, peaking within seconds, 2 hours ago. Examination is normal. What is the most appropriate management?",
       ["Discharge with triptan therapy for migraine",
        "Urgent non-contrast CT brain; if normal, further assessment for subarachnoid haemorrhage per local pathway (delayed LP for xanthochromia or CT angiography)",
        "Reassure as examination is normal",
        "MRI brain in one week",
        "Trial of high-flow oxygen for cluster headache"],
       "B",
       "Thunderclap headache (maximal within a minute) is subarachnoid haemorrhage until excluded. Non-contrast CT within 6 hours of onset and reported by an experienced radiologist is highly sensitive; presenting at 2 hours, she should be scanned urgently. If CT is performed or interpreted outside that window, or is normal but suspicion persists, the pathway proceeds to LP at ≥12 hours for xanthochromia or CT angiography per local protocol. A normal examination never excludes SAH — many sentinel bleeds look well.",
       "Thunderclap headache = urgent CT; a normal examination or normal early CT does not end the workup.",
       "RACGP / emergency medicine references"),

    _q("Emergency", "STEMI complications", "hard",
       "A 67-year-old man with an inferior STEMI becomes hypotensive (BP 78/50) after 600 mcg sublingual GTN. His chest is clear and JVP elevated. ECG shows ST elevation in II, III, aVF with III > II. What is the most appropriate immediate management?",
       ["IV furosemide",
        "IV fluid bolus and avoid further nitrates; obtain right-sided ECG leads",
        "Commence noradrenaline infusion as first measure",
        "Repeat GTN with close monitoring",
        "Intubate and ventilate"],
       "B",
       "Inferior STEMI with hypotension, clear lungs and raised JVP — markedly worsened by nitrates — indicates right ventricular infarction (supported by ST elevation in lead III exceeding II; confirm with V4R). The preload-dependent right ventricle needs volume: IV fluid boluses are the first-line treatment and nitrates/diuretics are contraindicated. Inotropes follow if fluids fail. Furosemide and further GTN would deepen the shock.",
       "Inferior STEMI + hypotension + clear chest = RV infarct: give fluids, never nitrates.",
       "RACGP / NHFA-CSANZ ACS guidelines"),

    _q("Emergency", "Meningococcal disease", "easy",
       "A GP in a rural town assesses a 16-year-old with fever, severe headache, neck stiffness and a spreading purpuric rash on the legs. The nearest hospital is 45 minutes away. What is the most appropriate immediate action?",
       ["Arrange urgent transfer and give the first dose of antibiotics on hospital arrival",
        "Give IM/IV benzylpenicillin now, then arrange urgent ambulance transfer",
        "Take blood cultures and await results before antibiotics",
        "Perform lumbar puncture in the clinic",
        "Give oral amoxicillin and review tomorrow"],
       "B",
       "Fever with a purpuric non-blanching rash is meningococcal septicaemia until proven otherwise, and mortality rises by the hour. Australian guidance is unambiguous: give parenteral benzylpenicillin (or ceftriaxone if available) immediately in the community before transfer — do not wait for hospital arrival, cultures, or lumbar puncture. The disease is also urgently notifiable on clinical suspicion, and close contacts will require clearance antibiotics.",
       "Suspected meningococcaemia in general practice: parenteral penicillin BEFORE transfer.",
       "RACGP / Therapeutic Guidelines: Antibiotic"),
]
