from seed_data.mcqs_1 import _q

MCQS_2 = [
    # ---------------- SURGERY ----------------
    _q("Surgery", "Appendicitis", "easy",
       "A 23-year-old man has 24 hours of periumbilical pain now localised to the right iliac fossa, with anorexia, fever 37.9°C, and tenderness with guarding at McBurney's point. WCC 14.2. What is the most appropriate management?",
       ["Discharge with oral antibiotics and review in 24 hours",
        "IV fluids, IV antibiotics, analgesia and laparoscopic appendicectomy",
        "Colonoscopy to confirm the diagnosis",
        "CT abdomen, and only operate if perforation is seen",
        "Observe overnight without analgesia to avoid masking signs"],
       "B",
       "The classic migratory history with localised RIF peritonism, fever and leucocytosis makes appendicitis a clinical diagnosis in a young man — no confirmatory imaging is required. Standard care is resuscitation, IV antibiotics covering Gram-negatives and anaerobes, adequate analgesia, and laparoscopic appendicectomy. Withholding analgesia to 'preserve signs' is outdated and wrong; opioids do not mask peritonitis from serial examiners. CT is reserved for diagnostic uncertainty, typically in older patients.",
       "Typical appendicitis in a young male is a clinical diagnosis — analgesia, antibiotics, theatre.",
       "RACGP / Therapeutic Guidelines: Antibiotic"),

    _q("Surgery", "Bowel obstruction", "medium",
       "A 74-year-old woman with no previous surgery presents with colicky abdominal pain, distension and bilious vomiting. CT shows dilated small bowel converging on a loop in the right groin below the inguinal ligament. What is the most likely diagnosis and management?",
       ["Adhesional obstruction — conservative management with NG tube",
        "Obstructed femoral hernia — urgent surgical repair",
        "Sigmoid volvulus — endoscopic decompression",
        "Gallstone ileus — ERCP",
        "Caecal cancer — elective right hemicolectomy"],
       "B",
       "Small bowel obstruction in a woman with a virgin abdomen and a loop below the inguinal ligament in the groin is an obstructed femoral hernia — commonest in elderly women, frequently missed because the groin is not examined, and dangerous because the narrow femoral ring strangulates quickly. Management is resuscitation, NG decompression and urgent operative repair; conservative management is inappropriate given the strangulation risk.",
       "No previous surgery + SBO = examine the groin; femoral hernias strangulate and need urgent surgery.",
       "RACGP / surgical references"),

    _q("Surgery", "AAA", "medium",
       "A 71-year-old male smoker presents with sudden severe left flank pain radiating to the groin and a syncopal episode. BP 92/60, HR 110. Urinalysis shows microscopic haematuria. What is the most important next step?",
       ["CT KUB for renal colic",
        "Urgent bedside aortic ultrasound / immediate vascular surgical involvement for suspected ruptured AAA",
        "IV NSAIDs and tamsulosin",
        "Discharge with urology follow-up",
        "MAG3 renogram"],
       "B",
       "First-presentation 'renal colic' in a man over 60 — especially with syncope and hypotension — is a ruptured abdominal aortic aneurysm until proven otherwise; microscopic haematuria occurs in AAA and does not confirm a stone. The next step is immediate senior/vascular involvement with bedside aortic ultrasound (or direct transfer to theatre/CT depending on stability). Treating presumed colic with NSAIDs while an aneurysm leaks is a classic fatal error.",
       "New 'renal colic' over 60 with hypotension or collapse = ruptured AAA until excluded.",
       "RACGP / vascular surgery references"),

    _q("Surgery", "Renal colic", "medium",
       "A 34-year-old man has CT-confirmed 4 mm distal ureteric calculus with no obstruction or infection. Pain is controlled with diclofenac. Creatinine is normal. What is the most appropriate management?",
       ["Immediate ureteroscopy",
        "Extracorporeal shock wave lithotripsy this admission",
        "Conservative management with analgesia and follow-up — most stones this size pass spontaneously",
        "Percutaneous nephrolithotomy",
        "Insertion of a ureteric stent"],
       "C",
       "Stones under 5–6 mm pass spontaneously in the great majority of patients (around 90% for 4 mm distal stones). With controlled pain, no infection, no obstruction and normal renal function, the correct management is conservative: NSAID analgesia, fluids, straining urine, and review with imaging at around 4–6 weeks if not passed. Intervention is indicated for stones >10 mm, sepsis, obstruction with renal impairment, intractable pain, or failure to progress.",
       "Small (<6 mm) uncomplicated ureteric stones: NSAIDs and time — not instruments.",
       "RACGP / urology guidelines"),

    _q("Surgery", "Urinary retention", "hard",
       "A 68-year-old man with chronic urinary symptoms presents unable to void for 18 hours. A catheter drains 1.8 L. Creatinine is 280 µmol/L (baseline 90). Over the next 6 hours he passes 350 mL/hr of urine. What is the most important management consideration?",
       ["Clamp the catheter to slow the diuresis",
        "Monitor for post-obstructive diuresis with fluid balance, electrolytes, and IV fluid replacement as needed",
        "Immediate TURP",
        "Remove the catheter and trial of void tomorrow",
        "Give furosemide to maintain urine output"],
       "B",
       "High-pressure chronic retention with renal impairment is followed in a proportion of patients by post-obstructive diuresis (>200 mL/hr), driven by retained solute, tubular dysfunction and washed-out medullary gradient. Unmonitored, it causes hypovolaemia, hyponatraemia, hypokalaemia and AKI-on-AKI. Management is strict fluid balance, regular electrolytes, and IV replacement (commonly ~75% of output). Clamping the catheter and early trial of void are dangerous; TURP is a later consideration after renal recovery.",
       "After relieving chronic retention, anticipate post-obstructive diuresis — monitor and replace.",
       "RACGP / urology references"),

    _q("Surgery", "Acute pancreatitis", "medium",
       "A 45-year-old woman presents with severe epigastric pain radiating to the back and vomiting. Lipase is 2,400 U/L. Ultrasound shows gallstones with no duct dilatation. She is haemodynamically stable. Along with analgesia, what is the cornerstone of initial management?",
       ["Urgent ERCP within 24 hours",
        "IV crystalloid fluid resuscitation, early oral intake as tolerated, and cholecystectomy during the same admission",
        "Prophylactic IV antibiotics",
        "Immediate laparoscopic cholecystectomy tonight",
        "Total parenteral nutrition and strict fasting for 7 days"],
       "B",
       "Mild gallstone pancreatitis is managed supportively: IV crystalloid resuscitation, analgesia, antiemetics, and early enteral feeding as tolerated (prolonged fasting and routine TPN worsen outcomes). Prophylactic antibiotics are not indicated without cholangitis or infected necrosis. Urgent ERCP is reserved for coexistent cholangitis or persisting biliary obstruction. Definitive prevention of recurrence is laparoscopic cholecystectomy during the same admission for mild disease — but after initial stabilisation, not emergently overnight.",
       "Pancreatitis care = fluids, analgesia, early feeding; same-admission cholecystectomy for mild gallstone pancreatitis.",
       "RACGP / gastroenterology guidelines"),

    _q("Surgery", "Bowel ischaemia", "hard",
       "An 81-year-old woman with atrial fibrillation (not anticoagulated) presents with 4 hours of severe constant abdominal pain. Her abdomen is soft with minimal tenderness. Lactate is 3.8 mmol/L. What is the most likely diagnosis?",
       ["Acute diverticulitis",
        "Acute mesenteric ischaemia",
        "Biliary colic",
        "Gastroenteritis",
        "Constipation"],
       "B",
       "Severe pain out of proportion to examination findings in an elderly patient with AF and a raised lactate is acute mesenteric ischaemia (embolic occlusion of the superior mesenteric artery) until proven otherwise. The soft abdomen early in the course is precisely the trap — peritonism appears only after infarction. Management is urgent CT angiography, anticoagulation, and revascularisation/laparotomy. Every alternative listed fails to explain the severity–findings mismatch and lactate.",
       "'Pain out of proportion' + AF + lactate = mesenteric ischaemia — image the vessels urgently.",
       "RACGP / surgical references"),

    _q("Surgery", "Cholecystitis", "easy",
       "A 52-year-old woman has 2 days of constant right upper quadrant pain, fever 38.2°C, and a positive Murphy's sign. Ultrasound shows gallstones, a thickened gallbladder wall and pericholecystic fluid. LFTs are normal. What is the optimal management?",
       ["Oral antibiotics and outpatient surgical referral",
        "IV antibiotics, analgesia and early laparoscopic cholecystectomy this admission",
        "ERCP",
        "Elective cholecystectomy in 6–8 weeks after 'cooling down'",
        "Percutaneous cholecystostomy as first-line"],
       "B",
       "This is acute calculous cholecystitis. Evidence consistently favours early laparoscopic cholecystectomy (within 72 hours to ~1 week of onset) over delayed surgery: fewer complications, shorter total stay, and no increase in bile-duct injury. Interim care is IV antibiotics, fluids and analgesia. Normal LFTs make choledocholithiasis unlikely, so ERCP is not indicated. Cholecystostomy is reserved for patients too unwell for surgery.",
       "Acute cholecystitis: antibiotics plus EARLY (same-admission) laparoscopic cholecystectomy.",
       "RACGP / surgical guidelines"),

    _q("Surgery", "Post-operative complications", "medium",
       "Five days after a right hemicolectomy, a 66-year-old man develops fever 38.8°C, tachycardia 118, and new abdominal pain with localised peritonism. WCC 18, CRP 280. What is the most likely diagnosis and next investigation?",
       ["Basal atelectasis — chest physiotherapy",
        "Anastomotic leak — CT abdomen/pelvis with contrast",
        "Urinary tract infection — urine culture",
        "Wound infection — wound swab",
        "DVT — Doppler ultrasound"],
       "B",
       "Fever, tachycardia and peritonism at day 5–7 after bowel anastomosis is an anastomotic leak until proven otherwise — the most feared complication of colorectal surgery, and the classic cause of 'failure to progress' or new sepsis at this point. CT with contrast identifies free gas, collections, and contrast extravasation. The timing matters: day 1–2 fever suggests atelectasis, day 3–5 urinary/respiratory infection, day 5–7 leak or collection, later DVT/PE — but peritonism trumps the timetable and demands urgent surgical review.",
       "Day 5 post-bowel-anastomosis sepsis with peritonism = leak; get a contrast CT and the surgical team.",
       "RACGP / surgical references"),

    _q("Surgery", "Breast lump", "medium",
       "A 44-year-old woman presents with a new 2 cm painless firm breast lump. What is the appropriate diagnostic approach?",
       ["Reassure and review after her next period",
        "Triple assessment: clinical examination, imaging (mammogram ± ultrasound), and core needle biopsy",
        "Mammogram alone; biopsy only if BI-RADS 5",
        "Fine needle aspiration alone",
        "MRI breast as the initial test"],
       "B",
       "Every discrete new breast lump requires triple assessment — clinical examination, age-appropriate imaging (mammography plus targeted ultrasound at 44), and percutaneous sampling, preferably core biopsy (which distinguishes invasive from in-situ disease, unlike FNA cytology). The components are complementary: concordantly benign triple assessment has >99% negative predictive value, while any discordance mandates further workup. Reassurance or imaging alone risks the classic missed cancer.",
       "No new discrete breast lump leaves the pathway without completed triple assessment.",
       "RACGP / Cancer Australia guidelines"),

    # ---------------- PAEDIATRICS ----------------
    _q("Paediatrics", "Febrile child", "medium",
       "A 25-day-old boy has a fever of 38.4°C at home. In ED he is alert and feeding, with no localising signs and normal observations apart from the fever. What is the most appropriate management?",
       ["Discharge with paracetamol and review tomorrow",
        "Admit for a full septic screen (blood, urine and CSF cultures) and empirical IV antibiotics",
        "Urine bag specimen and discharge if dipstick negative",
        "Oral amoxicillin and review in 48 hours",
        "Observe in ED for 4 hours and discharge if he remains well"],
       "B",
       "Any fever ≥38°C in a neonate (<28 days) mandates a full septic screen — blood cultures, catheter/SPA urine, lumbar puncture — and empirical IV antibiotics (e.g. amoxicillin plus gentamicin or cefotaxime), regardless of how well the baby appears. Neonates localise infection poorly, deteriorate precipitously, and well appearance has poor negative predictive value at this age. Serious bacterial infection rates approach 10–15% in febrile neonates.",
       "Febrile neonate = full septic screen + empirical IV antibiotics, no exceptions for looking well.",
       "RCH Clinical Practice Guidelines: Febrile child"),

    _q("Paediatrics", "Croup", "easy",
       "A 2-year-old girl presents at night with a barking cough, hoarse voice and stridor when upset but not at rest. She is well otherwise. What is the most appropriate management?",
       ["Nebulised adrenaline and ICU referral",
        "A single dose of oral corticosteroid (e.g. dexamethasone 0.15 mg/kg) and discharge with advice",
        "Throat examination with a tongue depressor to exclude epiglottitis",
        "Oral antibiotics",
        "Chest X-ray to confirm the diagnosis"],
       "B",
       "This is mild croup (no stridor at rest). All children with croup benefit from a single oral corticosteroid dose, which reduces symptom duration and re-presentation; mild cases can then be discharged with safety-netting. Nebulised adrenaline is reserved for moderate-severe croup with stridor at rest. Examining the throat with a depressor can precipitate complete obstruction and is contraindicated, and croup is a clinical diagnosis — imaging adds distress without value.",
       "Steroids for every croup, adrenaline only for stridor at rest; never instrument the throat.",
       "RCH Clinical Practice Guidelines: Croup"),

    _q("Paediatrics", "Bronchiolitis", "easy",
       "A 5-month-old boy has 3 days of coryza, cough, wheeze and crackles with moderate work of breathing. SpO2 93%, feeding about 60% of normal. What management is supported by evidence?",
       ["Salbutamol via spacer",
        "Oral prednisolone",
        "Supportive care: feeding support and oxygen if SpO2 falls below target — with observation",
        "Antibiotics for possible bacterial pneumonia",
        "Nebulised hypertonic saline and chest physiotherapy"],
       "C",
       "Bronchiolitis management is purely supportive: maintain hydration (small frequent feeds, NG or IV if intake <50%), give oxygen per saturation targets, and escalate to high-flow if distress is significant. Trials show no benefit from salbutamol, corticosteroids, antibiotics, nebulised adrenaline, hypertonic saline or physiotherapy in bronchiolitis — choosing bronchodilators or steroids is the most common exam error. Day 2–3 is peak severity, so disposition planning accounts for that trajectory.",
       "Bronchiolitis: hydration and oxygen only — no salbutamol, no steroids, no antibiotics.",
       "RCH Clinical Practice Guidelines: Bronchiolitis"),

    _q("Paediatrics", "Intussusception", "medium",
       "A 9-month-old girl has episodes of sudden screaming with drawing up of her legs, then appears pale and floppy between episodes. She has vomited twice. Abdomen is soft with a vague right-sided fullness. What is the next best step?",
       ["Reassure — likely infantile colic",
        "Abdominal ultrasound looking for a target sign, with paediatric surgical involvement",
        "Barium meal and follow-through",
        "Stool culture and discharge",
        "Trial of lactose-free formula"],
       "B",
       "Paroxysmal screaming episodes with pallor and lethargy between attacks in an infant aged 3 months–3 years is intussusception until proven otherwise — the inter-episode floppiness/lethargy is a hallmark that distinguishes it from colic (and may dominate the picture, mimicking sepsis). Ultrasound is the investigation of choice (target/doughnut sign, ~100% sensitive in experienced hands), followed by air enema reduction unless peritonitis or perforation mandates surgery. Redcurrant jelly stool is a late sign — waiting for it is the trap.",
       "Episodic pain + inter-episode lethargy in an infant = ultrasound for intussusception now.",
       "RCH Clinical Practice Guidelines: Intussusception"),

    _q("Paediatrics", "Kawasaki disease", "medium",
       "A 3-year-old boy has had a fever for 6 days despite antibiotics, with bilateral non-purulent conjunctivitis, cracked red lips, a polymorphous rash, and swollen hands. CRP is 110. What is the most appropriate management?",
       ["Change to broader-spectrum antibiotics",
        "IV immunoglobulin 2 g/kg plus aspirin, and echocardiography",
        "Supportive care — likely viral exanthem",
        "Oral corticosteroids alone",
        "Await blood culture results before treatment"],
       "B",
       "He meets criteria for Kawasaki disease: fever ≥5 days plus ≥4 principal features (conjunctivitis, oral changes, rash, extremity changes). Treatment is IVIG 2 g/kg as a single infusion plus aspirin, ideally within 10 days of fever onset, reducing coronary aneurysm risk from ~25% to under 5%. Echocardiography is performed at diagnosis and in follow-up. Fever unresponsive to antibiotics is the classic clue; this is also one of the few paediatric indications for aspirin.",
       "Fever ≥5 days + mucocutaneous signs = Kawasaki: IVIG + aspirin within 10 days, echo the coronaries.",
       "RCH Clinical Practice Guidelines: Kawasaki disease"),

    _q("Paediatrics", "Child protection", "hard",
       "A 6-week-old presents with a swollen thigh. X-ray shows a femoral fracture. The parents say he 'rolled off the couch' yesterday. He also has a torn frenulum and two bruises on his back. What is the most appropriate action?",
       ["Accept the explanation and arrange fracture management only",
        "Treat the fracture, admit the infant to a safe environment, perform a full skeletal survey and notify child protection services",
        "Discharge with early follow-up and a home visit next week",
        "Confront the parents with an accusation of abuse",
        "Order a bone density scan for osteogenesis imperfecta before involving anyone"],
       "B",
       "A femoral fracture in a non-mobile 6-week-old with an inconsistent mechanism (6-week-olds cannot roll), a torn frenulum (highly specific for inflicted injury) and truncal bruising is a constellation of sentinel injuries for physical abuse. The obligations are: treat the injury, secure the child's safety (admission), complete a forensic workup (skeletal survey, ± neuroimaging and ophthalmology for occult injury), and make a mandatory report to the statutory child protection service. Reporting requires reasonable suspicion, not proof; accusatory confrontation is counterproductive and unsafe.",
       "Fractures in non-mobile infants are abuse until proven otherwise — admit, investigate, report.",
       "RCH Clinical Practice Guidelines: Child abuse"),

    _q("Paediatrics", "Gastroenteritis", "easy",
       "An 18-month-old girl has 2 days of vomiting and diarrhoea. She is alert with moist mucous membranes, normal capillary refill, and a wet nappy this morning. She refuses her bottle but sips water. What is the most appropriate management?",
       ["IV fluid resuscitation",
        "Oral rehydration solution in small frequent volumes, continue feeding, and safety-net advice",
        "Loperamide to reduce stool frequency",
        "Ondansetron and nil by mouth for 6 hours",
        "Stool culture and antibiotics"],
       "B",
       "She has clinically mild or no dehydration, so the evidence-based approach is oral rehydration solution given little and often (syringe or cup, e.g. 0.5 mL/kg every 5 minutes if vomiting), continuing breastfeeds/feeds, and clear advice on red flags. Antiemetics may assist ORT in moderate dehydration but 'nil by mouth' is wrong; antimotility agents are contraindicated in young children; antibiotics and routine cultures are unnecessary in uncomplicated viral gastroenteritis.",
       "Mild dehydration: small frequent oral rehydration beats IV — and never stop feeds.",
       "RCH Clinical Practice Guidelines: Gastroenteritis"),

    _q("Paediatrics", "Febrile convulsion", "medium",
       "A 2-year-old boy had a 3-minute generalised tonic-clonic seizure with fever during a viral illness, recovering fully within 20 minutes. Examination is normal with an obvious viral URTI focus. His parents are terrified. What do you advise?",
       ["He has epilepsy and needs an EEG and daily antiseizure medication",
        "Simple febrile convulsions are common (3% of children), benign, and carry only a marginally increased epilepsy risk; treat the fever source and provide first-aid education",
        "Lumbar puncture is mandatory",
        "Regular paracetamol will prevent future febrile convulsions",
        "He must be admitted for 48 hours of monitoring"],
       "B",
       "This is a simple febrile convulsion: generalised, <15 minutes, once in 24 hours, in a developmentally normal child aged 6 months–6 years with rapid recovery and an evident focus. Parents should hear that it is common and benign; recurrence occurs in ~30% but long-term epilepsy risk is only marginally above baseline. Antipyretics do not prevent recurrence (worth saying explicitly), EEG and antiseizure medication are not indicated, and LP is reserved for suspected CNS infection or the unimmunised/pretreated child.",
       "Simple febrile convulsion: educate and reassure — no EEG, no anticonvulsants, and antipyretics don't prevent recurrence.",
       "RCH Clinical Practice Guidelines: Febrile seizure"),

    _q("Paediatrics", "Neonatal jaundice", "hard",
       "A breastfed term baby is brought in on day 2 of life with jaundice that was first noticed at 18 hours of age. Total serum bilirubin is above the phototherapy threshold, unconjugated. Mother is blood group O positive, baby A positive. What is the most likely diagnosis and management?",
       ["Physiological jaundice — reassure",
        "Breast milk jaundice — stop breastfeeding",
        "ABO incompatibility haemolysis — phototherapy, DAT/Coombs testing and close bilirubin monitoring",
        "Biliary atresia — urgent surgical referral",
        "Sepsis is excluded by the well appearance"],
       "C",
       "Jaundice appearing within the first 24–48 hours is pathological until proven otherwise, and the setup of an O-positive mother with an A-positive infant is classic ABO haemolytic disease. Management is phototherapy at threshold, direct antiglobulin (Coombs) testing, haemoglobin/reticulocytes, and vigilant monitoring for rises requiring exchange transfusion. Physiological jaundice begins after 24 hours and peaks day 3–5; breast milk jaundice is a later, more prolonged picture and never requires stopping breastfeeding at this stage; pale stools/conjugated pattern would suggest biliary atresia.",
       "Jaundice in the first 24 hours is never physiological — think haemolysis and check the DAT.",
       "RCH Clinical Practice Guidelines: Jaundice in early infancy"),

    _q("Paediatrics", "Anaphylaxis (paediatric)", "easy",
       "A 4-year-old (16 kg) develops generalised urticaria, stridor and wheeze after eating peanut butter at a birthday party. What is the correct adrenaline dose and route?",
       ["0.16 mg (1:1000) intramuscularly into the lateral thigh",
        "0.5 mg intramuscular regardless of weight",
        "0.16 mg intravenously",
        "1 mg subcutaneously",
        "Adrenaline is contraindicated under 5 years of age"],
       "A",
       "Paediatric anaphylaxis dosing is 0.01 mg/kg of 1:1000 adrenaline intramuscularly into the anterolateral thigh — for 16 kg that is 0.16 mg (or an EpiPen Jr 0.15 mg device for 7.5–20 kg). The 0.5 mg dose is the adult maximum. The IM route into the thigh achieves the most rapid reliable absorption; IV bolus adrenaline in this setting risks arrhythmia and is reserved for arrest or refractory shock with infusion expertise.",
       "Anaphylaxis dosing: 0.01 mg/kg IM (max 0.5 mg) of 1:1000 into the lateral thigh — know the device weight bands.",
       "ASCIA / RCH anaphylaxis guidelines"),

    _q("Paediatrics", "UTI in children", "medium",
       "An 8-month-old girl has a fever of 39°C for 2 days with no focus on examination. What is the most appropriate way to assess for urinary tract infection?",
       ["Bag urine specimen for culture",
        "Catheter or suprapubic urine specimen for microscopy and culture",
        "Clean-catch attempt only if fever persists another 48 hours",
        "Empirical antibiotics without urine testing",
        "Renal ultrasound first"],
       "B",
       "UTI is the commonest serious bacterial infection in febrile infants without a focus, so urine testing is mandatory — but the specimen must be reliable. Bag specimens have contamination rates up to 50% and are unsuitable for culture-based diagnosis; in a pre-continent febrile infant, catheter or suprapubic aspirate specimens are the standard (clean catch is an acceptable attempt if it can be obtained promptly). Treating without a specimen sacrifices the diagnosis and the indication for imaging follow-up.",
       "Fever without focus in infancy: test urine, and never base the diagnosis on a bag specimen.",
       "RCH Clinical Practice Guidelines: UTI"),

    _q("Paediatrics", "Asthma (paediatric acute)", "medium",
       "A 7-year-old with known asthma presents with moderate acute asthma: talking in phrases, subcostal recession, SpO2 93%, bilateral wheeze. Initial management?",
       ["Salbutamol 12 puffs via spacer, oral prednisolone, and reassessment",
        "Nebulised salbutamol driven by oxygen as first-line over a spacer",
        "IV salbutamol bolus",
        "IV hydrocortisone and aminophylline",
        "Chest X-ray before bronchodilators"],
       "A",
       "Moderate paediatric asthma is treated with salbutamol via pMDI and spacer — 6 puffs under 6 years, 12 puffs for 6 and over — repeated and titrated ('burst' therapy), plus early oral corticosteroid (prednisolone 1–2 mg/kg). Spacer delivery is as effective as nebulisation in non-life-threatening asthma, with fewer side effects, and is the RCH-preferred route. IV therapies are for severe/critical asthma unresponsive to inhaled treatment, and routine CXR is unnecessary.",
       "Spacers beat nebulisers in acute paediatric asthma; 6 puffs <6 years, 12 puffs ≥6 years, plus oral steroid.",
       "RCH Clinical Practice Guidelines: Asthma"),

    _q("Paediatrics", "Developmental assessment", "easy",
       "Parents of an 18-month-old boy report he has no single words, does not point to request or show, does not respond consistently to his name, and has limited eye contact. What is the most appropriate response?",
       ["Reassure — boys often talk late",
        "Refer for developmental/autism assessment and audiology now, without waiting",
        "Review again at 2 years before any referral",
        "Order chromosomal microarray and review with results",
        "Advise more screen-free play and review in 6 months"],
       "B",
       "Absent single words at 18 months combined with deficits in joint attention (no pointing/showing), inconsistent name response, and reduced eye contact are red flags for autism spectrum disorder — not a normal variant pattern. Early developmental assessment and early intervention measurably improve outcomes, and 'wait and see' wastes the period of maximal neuroplasticity. Audiology is mandatory in any speech/language concern to exclude hearing impairment. Investigations like microarray follow specialist assessment rather than replacing referral.",
       "Joint-attention red flags (no pointing, poor name response) trump 'late talker' reassurance — refer early, test hearing.",
       "RCH Clinical Practice Guidelines / developmental surveillance"),
]
