QUOTES = [
    {"quote": "Wherever the art of medicine is loved, there is also a love of humanity.", "author": "Hippocrates", "category": "medical"},
    {"quote": "The good physician treats the disease; the great physician treats the patient who has the disease.", "author": "William Osler", "category": "medical"},
    {"quote": "Medicine is a science of uncertainty and an art of probability.", "author": "William Osler", "category": "medical"},
    {"quote": "He who studies medicine without books sails an uncharted sea, but he who studies medicine without patients does not go to sea at all.", "author": "William Osler", "category": "medical"},
    {"quote": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi", "category": "motivation"},
    {"quote": "Success is not final, failure is not fatal: it is the courage to continue that counts.", "author": "Winston Churchill", "category": "history"},
    {"quote": "It always seems impossible until it is done.", "author": "Nelson Mandela", "category": "history"},
    {"quote": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas Edison", "category": "history"},
    {"quote": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "author": "Will Durant (on Aristotle)", "category": "psychology"},
    {"quote": "The expert in anything was once a beginner.", "author": "Helen Hayes", "category": "motivation"},
    {"quote": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius", "category": "motivation"},
    {"quote": "Whether you think you can, or you think you can't — you're right.", "author": "Henry Ford", "category": "psychology"},
    {"quote": "The man who moves a mountain begins by carrying away small stones.", "author": "Confucius", "category": "motivation"},
    {"quote": "Hard days are what make you stronger.", "author": "Aly Raisman", "category": "motivation"},
    {"quote": "Strength does not come from physical capacity. It comes from an indomitable will.", "author": "Mahatma Gandhi", "category": "psychology"},
    {"quote": "I am not what happened to me, I am what I choose to become.", "author": "Carl Jung", "category": "psychology"},
    {"quote": "Between stimulus and response there is a space. In that space is our power to choose our response.", "author": "Viktor Frankl", "category": "psychology"},
    {"quote": "Those who have a 'why' to live can bear with almost any 'how'.", "author": "Viktor Frankl", "category": "psychology"},
    {"quote": "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.", "author": "Marie Curie", "category": "history"},
    {"quote": "Discipline is choosing between what you want now and what you want most.", "author": "Abraham Lincoln (attributed)", "category": "motivation"},
    {"quote": "Wherever you go, go with all your heart.", "author": "Confucius", "category": "motivation"},
    {"quote": "An investment in knowledge pays the best interest.", "author": "Benjamin Franklin", "category": "history"},
    {"quote": "Do not wait to strike till the iron is hot, but make it hot by striking.", "author": "William Butler Yeats", "category": "motivation"},
    {"quote": "Perseverance is failing 19 times and succeeding the 20th.", "author": "Julie Andrews", "category": "motivation"},
    {"quote": "Cure sometimes, treat often, comfort always.", "author": "Hippocrates (attributed)", "category": "medical"},
    {"quote": "Observation, Reason, Human Understanding, Courage; these make the physician.", "author": "Martin H. Fischer", "category": "medical"},
    {"quote": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu", "category": "motivation"},
    {"quote": "Rest when you're weary. Refresh and renew yourself. Then get back to work.", "author": "Ralph Marston", "category": "psychology"},
    {"quote": "You don't have to be great to start, but you have to start to be great.", "author": "Zig Ziglar", "category": "motivation"},
    {"quote": "Every accomplishment starts with the decision to try.", "author": "John F. Kennedy", "category": "history"},
]
