from seed_data.topics_part1 import RACGP, RCH, RANZCOG, SA_HEALTH, RCPSYCH, _t

TOPICS_2 = [
    _t("Intussusception", "Paediatrics",
       "Telescoping of proximal bowel into distal segment (usually ileocolic); commonest cause of bowel obstruction in infants 3 months-3 years.",
       "Paroxysmal severe colicky pain with drawing up of legs, pallor and lethargy between episodes, vomiting (may become bilious), later redcurrant jelly stool (late sign); sausage-shaped RUQ mass. Ultrasound is the investigation of choice: 'target/doughnut' sign.",
       "Resuscitate first: IV fluids, NG decompression if obstructed, analgesia. Definitive: air (pneumatic) enema reduction under fluoroscopy — success ~90%. Surgery if peritonitis, perforation, shock, or failed enema. Observe post-reduction; recurrence ~10%.",
       "Peritonitis, free air, shock — contraindications to enema, straight to theatre. Lethargy alone can be the dominant sign in infants (mimics sepsis/encephalopathy).",
       "AMC Pearl: An episodically screaming infant who is pale and floppy BETWEEN episodes is intussusception until proven otherwise. AMC Pearl: Air enema is both diagnostic and therapeutic — but only after exclusion of peritonitis.",
       [RCH]),

    _t("Croup (laryngotracheobronchitis)", "Paediatrics",
       "Viral upper airway obstruction (parainfluenza most common) of children 6 months-6 years: barking cough, stridor, hoarseness, worse at night.",
       "Clinical diagnosis — do NOT distress the child with throat examination or imaging. Severity: mild (no stridor at rest), moderate (stridor at rest, some recession), severe (marked recession, agitation, hypoxia/fatigue).",
       "All severities: single dose oral corticosteroid — dexamethasone 0.15-0.3 mg/kg (or prednisolone 1 mg/kg). Mild: discharge with advice. Moderate: steroid, observe 30-60 min. Severe: nebulised adrenaline 1:1000 (0.5 mL/kg, max 5 mL) + steroid + senior help; observe ≥3-4h after adrenaline for rebound.",
       "Drooling, dysphagia, toxic appearance (think epiglottitis/bacterial tracheitis), cyanosis, fatigue with quietening stridor (impending obstruction), no improvement after adrenaline.",
       "AMC Pearl: A 'quiet' stridor in a tiring child signals impending complete obstruction — escalate, don't reassure. AMC Pearl: Steroids for every croup presentation, even mild — they halve representation rates.",
       [RCH]),

    _t("Bronchiolitis", "Paediatrics",
       "Viral LRTI (usually RSV) of infants <12 months: coryza progressing to cough, wheeze/crackles, work of breathing, feeding difficulty. Peak severity day 2-3.",
       "Clinical diagnosis; no routine CXR, bloods, or viral testing (CXR often misleads to unnecessary antibiotics). Assess: feeding (<50% intake), hydration, respiratory rate/effort, SpO2, apnoeas, risk factors (prematurity, <6 weeks, cardiac/lung disease).",
       "Supportive only: small frequent feeds or NG/IV hydration if <50% intake, oxygen if SpO2 <90-92% per local guideline, high-flow nasal cannula for moderate-severe distress. Evidence shows NO benefit: salbutamol, steroids, antibiotics, nebulised adrenaline, chest physio. Most infants are managed at home with safety-netting.",
       "Apnoeic episodes, SpO2 <90%, severe recession/grunting, infants <6-8 weeks old, dehydration, parental inability to cope — admit; exhaustion/respiratory failure → HDU/ICU.",
       "AMC Pearl: Bronchiolitis treatment is hydration and oxygen — choosing salbutamol or steroids is the classic exam error. AMC Pearl: Day 2-3 is the expected worst point; plan review accordingly.",
       [RCH]),

    _t("Schizophrenia", "Psychiatry",
       "Chronic psychotic disorder: positive symptoms (delusions, hallucinations, disorganisation), negative symptoms (avolition, blunted affect), cognitive impairment. Onset typically late teens-20s.",
       "Clinical (DSM-5): ≥2 of delusions, hallucinations, disorganised speech, grossly disorganised/catatonic behaviour, negative symptoms — for ≥6 months with ≥1 month active symptoms and functional decline. Exclude organic causes (drug-induced, delirium, autoimmune encephalitis) and mood disorder with psychosis. First episode: physical exam, bloods, urine drug screen, ± neuroimaging.",
       "First-line: second-generation antipsychotic (risperidone, olanzapine, aripiprazole) at lowest effective dose, with psychoeducation, family support and early intervention service. Depot if adherence poor. Clozapine after failure of two adequate antipsychotic trials (treatment resistance) — monitor FBC (agranulocytosis), myocarditis, metabolic effects. Monitor metabolic syndrome for all.",
       "Command hallucinations to harm, risk to self/others (may need involuntary treatment under state Mental Health Act), neuroleptic malignant syndrome (fever, rigidity, autonomic instability, raised CK), clozapine fever/neutropenia.",
       "AMC Pearl: Clozapine is indicated after TWO failed adequate antipsychotic trials — earlier in the exam answer than many expect. AMC Pearl: First-episode psychosis in a young person warrants drug screen and organic workup before the label.",
       [RCPSYCH, RACGP]),

    _t("Bipolar disorder", "Psychiatry",
       "Episodic mood disorder: mania/hypomania (elevated/irritable mood, grandiosity, decreased need for sleep, pressured speech, risk-taking) with depressive episodes. Bipolar I requires one manic episode.",
       "Clinical: manic episode ≥1 week (or any duration if hospitalised) with functional impairment; hypomania ≥4 days without marked impairment. Screen every 'depression' presentation for past elevated mood. Exclude substance-induced and organic causes; baseline TFTs, renal function (pre-lithium).",
       "Acute mania: cease antidepressants; lithium or sodium valproate plus/or an atypical antipsychotic (olanzapine, quetiapine); benzodiazepines short-term for agitation. Bipolar depression: quetiapine, lurasidone, or lithium/lamotrigine — avoid antidepressant monotherapy. Maintenance: lithium is gold standard (reduces suicide); monitor levels 0.6-0.8 mmol/L, renal and thyroid function 6-monthly. Valproate contraindicated in women of childbearing potential without robust contraception.",
       "Lithium toxicity (>1.5: tremor, ataxia, confusion — dehydration, NSAIDs, ACEi precipitate), acute mania with risk-taking/psychosis (often needs involuntary admission), postpartum psychosis.",
       "AMC Pearl: Antidepressant monotherapy in bipolar disorder risks manic switch — always cover with a mood stabiliser or avoid. AMC Pearl: Lithium toxicity is precipitated by dehydration, NSAIDs, ACE inhibitors and thiazides — the classic medication-interaction question.",
       [RCPSYCH, RACGP]),

    _t("Major depressive disorder", "Psychiatry",
       "≥2 weeks of depressed mood or anhedonia plus neurovegetative and cognitive symptoms causing functional impairment. Lifetime prevalence ~15%; leading cause of disability.",
       "DSM-5: ≥5 of 9 symptoms (mood, anhedonia, sleep, appetite/weight, energy, concentration, psychomotor change, worthlessness/guilt, suicidal ideation) for ≥2 weeks. Always assess suicide risk and screen for bipolarity, substance use, and organic causes (TFTs, FBC, B12/folate).",
       "Mild: psychological therapy first-line (CBT, behavioural activation), lifestyle (exercise, sleep, alcohol reduction). Moderate-severe: SSRI first-line (sertraline, escitalopram) plus psychotherapy; review at 2-4 weeks (younger patients earlier for emergent suicidality). Inadequate response: optimise dose → switch agent → augment. Psychotic depression: antidepressant + antipsychotic or ECT. ECT for life-threatening depression (refusal to eat/drink, high suicide risk, psychosis, previous response).",
       "Active suicidal intent with plan, psychotic features, refusal of oral intake, melancholic stupor — psychiatric emergency; postpartum onset (risk to mother and infant).",
       "AMC Pearl: Psychological therapy is genuinely first-line for mild depression — medication is not the default answer. AMC Pearl: Review 1-2 weeks after starting an SSRI in adolescents/young adults for activation and emergent suicidality.",
       [RCPSYCH, RACGP]),

    _t("Suicide risk assessment", "Psychiatry",
       "Structured evaluation of suicidal ideation, intent, plan, means and protective factors. Asking about suicide does not increase risk — it is the core clinical skill.",
       "Explore: ideation (passive vs active), plan (specificity, lethality), access to means, preparatory acts (notes, giving away possessions), previous attempts (strongest single predictor), psychiatric illness, substance use, recent losses, social isolation; protective factors (family, faith, future orientation, engagement). Mental state: hopelessness predicts strongly. Collateral history.",
       "Immediate safety: high-risk (active intent + plan + means or recent serious attempt) — do not leave alone, remove means, urgent psychiatric assessment ± involuntary admission under the state Mental Health Act. Moderate: crisis/safety plan, means restriction, involve supports, mental health team follow-up within days. Treat the underlying disorder. Document the assessment and the rationale for the disposition.",
       "Command hallucinations, recent discharge from psychiatric care (highest-risk period), intoxication with stated intent, attempt with high lethality or concealment, marked hopelessness with sudden 'calm'.",
       "AMC Pearl: A previous attempt is the single strongest predictor of completed suicide. AMC Pearl: Sudden unexplained calm in a previously suicidal patient may indicate a finalised decision — reassess, don't celebrate.",
       [RCPSYCH, RACGP]),

    _t("Capacity and consent", "Ethics",
       "Valid consent must be voluntary, informed, specific, and given by a person with decision-making capacity. Capacity is decision-specific and presumed in adults until shown otherwise.",
       "Capacity assessment — the patient can: (1) understand the relevant information, (2) retain it long enough to decide, (3) weigh/use it in reaching a decision, (4) communicate the decision. Fluctuating capacity (delirium) — reassess; impaired capacity does not equal global incapacity.",
       "Adults with capacity may refuse any treatment, even life-saving — respect the refusal after ensuring information and voluntariness. Lacking capacity: follow advance care directive if valid and applicable; otherwise substitute decision-maker hierarchy per state law (guardian, attorney, spouse, carer, relative). Emergencies: treat under necessity when consent unobtainable and treatment immediately required. Minors: Gillick competence allows a mature minor to consent to treatment; parental consent otherwise — court for refusal of life-saving care.",
       "Refusal that seems driven by psychosis/depression (assess capacity AND mental illness — Mental Health Act may apply), coercion by family, fluctuating capacity, child protection concerns overriding parental refusal.",
       "AMC Pearl: Capacity is decision-specific and time-specific — a person with dementia may still validly consent to simple treatments. AMC Pearl: A competent adult Jehovah's Witness may refuse blood; their child's life-saving transfusion can be authorised despite parental refusal.",
       [RACGP]),

    _t("Notifiable diseases", "Ethics",
       "Australian clinicians and laboratories must notify specified communicable diseases to state/territory health departments — a legal duty that overrides confidentiality.",
       "Notifiable conditions include (varying slightly by state): meningococcal disease, measles, pertussis, tuberculosis, hepatitis A/B/C, HIV, syphilis, gonorrhoea, chlamydia, dengue, Q fever, legionellosis, listeriosis, COVID-19, and foodborne outbreaks. Some require immediate phone notification (e.g. measles, meningococcal), others routine written notification.",
       "Notify per state protocol (urgency depends on disease); treat the patient; support contact tracing — for STIs use patient referral or provider referral, with partner notification services available. Public health may direct prophylaxis (e.g. meningococcal contacts, measles MMR/immunoglobulin within 72h/144h).",
       "Suspected measles or meningococcal disease — notify on clinical suspicion (do not wait for laboratory confirmation); deliberate transmission concerns; patients refusing to inform partners of HIV (escalate via public-health pathways, not unilateral breach first).",
       "AMC Pearl: Notification on clinical suspicion (not lab confirmation) is required for urgent conditions like measles and meningococcus. AMC Pearl: Notification is a legal duty and not a breach of confidentiality — the exam tests whether you know it overrides consent.",
       [RACGP]),

    _t("Child protection and mandatory reporting", "Ethics",
       "All Australian states mandate reporting of suspected child abuse/neglect by doctors. The child's safety overrides confidentiality and the therapeutic relationship with parents.",
       "Recognise: injuries inconsistent with history or development (bruises in non-mobile infants, posterior rib fractures, metaphyseal corner fractures, immersion-pattern burns), delayed presentation, changing story, frequent attendances, failure to thrive, sexualised behaviour, fearfulness. Document verbatim statements, body charts, photographs per protocol.",
       "Immediate medical needs first. If suspicion of significant harm: report to the statutory child protection service (mandatory — belief on reasonable grounds suffices; you need not be certain and you are legally protected for good-faith reports). Admit the child if discharge is unsafe. Involve paediatric/forensic teams for examination; do not confront caregivers with accusations or investigate yourself.",
       "Any injury in a non-mobile infant, head injury or retinal haemorrhages in infancy (abusive head trauma), disclosure by the child, siblings potentially at risk, caregiver refusing assessment or attempting removal.",
       "AMC Pearl: A bruise in a baby who cannot yet cruise ('those who don't cruise rarely bruise') mandates child-protection evaluation. AMC Pearl: You report reasonable suspicion — proof is the statutory agency's job, not yours.",
       [RCH, RACGP]),

    _t("Chest pain (approach)", "Emergency",
       "Undifferentiated chest pain requires simultaneous exclusion of the six lethal causes: ACS, PE, aortic dissection, tension pneumothorax, oesophageal rupture, cardiac tamponade.",
       "Immediate: ECG within 10 minutes, observations, targeted history (character, radiation, exertional, pleuritic, tearing; risk factors). hs-troponin serial testing for ACS; CXR (pneumothorax, mediastinum); D-dimer/CTPA per Wells for PE; CT aortogram if dissection suspected (tearing interscapular pain, pulse/BP differential, new AR murmur).",
       "Treat the cause: ACS pathway (aspirin, antithrombotics, reperfusion); PE (anticoagulation/thrombolysis); dissection (urgent BP control with IV beta-blocker targeting SBP 100-120 + cardiothoracic referral — type A is surgical); tension pneumothorax (immediate needle decompression then chest drain); tamponade (pericardiocentesis). Low-risk pathways (HEART score) allow safe early discharge of many.",
       "Pain with syncope, hypotension, pulse deficit, new murmur, hypoxia, unilateral silent chest, surgical emphysema — these flag the lethal six; never give thrombolysis if dissection is possible.",
       "AMC Pearl: Aortic dissection + inferior STEMI pattern (RCA involvement) — thrombolysis would be lethal; image first when the story suggests dissection. AMC Pearl: A normal ECG and single negative troponin do NOT exclude ACS at presentation.",
       [RACGP]),

    _t("Dyspnoea (approach)", "Emergency",
       "Acute breathlessness spans airway, pulmonary, cardiac, metabolic and psychiatric causes; structured assessment prevents anchoring.",
       "ABC + observations including SpO2 and RR (most sensitive deteriorating sign). History: onset speed, chest pain, fever/sputum, orthopnoea, risk factors. Examination: stridor vs wheeze vs crepitations vs silent chest; JVP, oedema. Investigations: ECG, CXR, ABG/VBG, spirometry/PEF, NT-proBNP, D-dimer/CTPA as directed; bedside ultrasound (B-lines, effusion, pneumothorax, RV strain).",
       "Treat hypoxia while diagnosing: titrated oxygen (88-92% in COPD risk, otherwise 92-96%). Cause-directed: bronchodilators + steroids (asthma/COPD), furosemide + nitrates + CPAP (acute pulmonary oedema), antibiotics (pneumonia), decompression (pneumothorax), anticoagulation (PE), adrenaline (anaphylaxis). NIV for hypercapnic COPD (BiPAP) and cardiogenic pulmonary oedema (CPAP).",
       "Silent chest, exhaustion, falling GCS, rising CO2, SpO2 <90% despite oxygen, stridor (airway emergency — call anaesthetics), unilateral absent breath sounds with shock (tension pneumothorax).",
       "AMC Pearl: Rising respiratory rate is the earliest objective sign of deterioration — trends beat single values. AMC Pearl: In acute pulmonary oedema, CPAP + nitrates reduce intubation; routine morphine does not and may harm.",
       [RACGP]),

    _t("Headache (approach)", "Emergency",
       "Most headaches are primary (migraine, tension, cluster); the task is detecting the dangerous secondary causes: SAH, meningitis, raised ICP, temporal arteritis, CO poisoning.",
       "Red-flag screen (SNOOP): Systemic symptoms/fever, Neurological deficit, Onset thunderclap (maximal <1 min — SAH until excluded: CT head, highly sensitive <6h; LP for xanthochromia ≥12h if CT negative beyond window), Older onset >50 (ESR/CRP for GCA — jaw claudication, scalp tenderness, visual symptoms), Pattern change/papilloedema. Migraine: unilateral pulsating 4-72h, photophobia, nausea, aura.",
       "Migraine acute: aspirin or NSAID + antiemetic (metoclopramide) early; triptan if needed (avoid in IHD/uncontrolled HTN); avoid opioids. Prophylaxis if frequent: propranolol, amitriptyline, candesartan, topiramate. GCA suspected: start prednisolone 40-60 mg immediately (before biopsy) to save sight. Cluster: high-flow oxygen + subcutaneous sumatriptan; verapamil prophylaxis.",
       "Thunderclap onset, fever + neck stiffness ± rash, new focal deficit or seizure, papilloedema, headache waking from sleep/worse on lying or Valsalva, jaw claudication with visual symptoms, headache after head trauma on anticoagulants.",
       "AMC Pearl: Thunderclap headache with a normal early CT still needs LP at ≥12 hours for xanthochromia (or CT angiography per local pathway). AMC Pearl: Suspected GCA = steroids NOW, biopsy within days — never wait for biopsy while vision is at risk.",
       [RACGP]),

    _t("Abdominal pain (approach)", "Emergency",
       "Undifferentiated abdominal pain demands a region- and demographic-based surgical sieve, with early exclusion of vascular catastrophes and ectopic pregnancy.",
       "History (site, onset, character, radiation, associated GI/GU/gynae symptoms) + examination (peritonism, masses, hernial orifices, PR as indicated) + targeted tests: beta-hCG in ALL women of reproductive age, lipase (pancreatitis), urinalysis, ECG (inferior MI mimics epigastric pain), lactate (ischaemia), erect CXR (free air). Imaging: ultrasound (biliary, gynae, AAA), CT for the undifferentiated acute abdomen.",
       "Resuscitate while assessing: IV access, fluids, analgesia (opioids do not mask peritonism), antiemetics, NBM. Surgical causes (peritonitis, obstruction, perforation, ischaemia) — early surgical referral. Medical mimics: DKA, inferior MI, lower lobe pneumonia, hypercalcaemia, adrenal crisis, herpes zoster.",
       "Pain out of proportion to findings (mesenteric ischaemia — often AF + lactate), rigid silent abdomen, pulsatile mass with pain/syncope (ruptured AAA — theatre, do not delay for CT if unstable), bilious vomiting, hypotension with positive hCG (ruptured ectopic).",
       "AMC Pearl: 'Pain out of proportion to examination' in an elderly patient with AF = mesenteric ischaemia until proven otherwise. AMC Pearl: Withholding analgesia pending surgical review is wrong — and a recurring exam distractor.",
       [RACGP]),

    _t("Altered consciousness (approach)", "Emergency",
       "Reduced GCS spans structural, metabolic, toxic and infective causes. The immediate priorities are airway protection and reversible causes.",
       "ABC with cervical-spine care; GCS and pupils; bedside glucose immediately. Screen DIMTOP causes: Drugs/toxins, Infection, Metabolic (glucose, Na, Ca, urea, ammonia), Trauma, Oxygen deficit/vascular (stroke, hypoxia, hypercapnia), Psychiatric (diagnosis of exclusion). Investigations: VBG, electrolytes, cultures, CT head (focal signs, trauma, no clear metabolic cause), LP if meningitis suspected and safe.",
       "Immediate: airway positioning ± adjuncts; intubate if GCS ≤8 or unprotected airway. Treat reversible causes: glucose for hypoglycaemia, naloxone for opioid toxicity (respiratory rate <8, pinpoint pupils), thiamine before glucose in suspected alcoholism, antibiotics/aciclovir for meningoencephalitis, control seizures.",
       "Unequal/fixed pupils (herniation — neurosurgical emergency, consider mannitol/hypertonic saline), hypoglycaemia (rapidly fatal and instantly reversible), Cushing triad (bradycardia, hypertension, irregular breathing), fever + reduced GCS.",
       "AMC Pearl: 'Don't ever forget glucose' — checking BSL is the first investigation in every reduced-GCS scenario. AMC Pearl: GCS ≤8 = intubate (airway protection precedes diagnosis).",
       [RACGP]),

    _t("Anaphylaxis", "Emergency",
       "Acute multi-system hypersensitivity reaction: airway/breathing/circulatory compromise after exposure to an allergen (foods, drugs, stings). Fatalities are associated with delayed adrenaline.",
       "Clinical: acute onset with skin/mucosal features (urticaria, angio-oedema) PLUS respiratory compromise, hypotension, or persistent GI symptoms — or hypotension/bronchospasm alone after a known allergen. Skin signs are absent in up to 20%.",
       "IM adrenaline 0.01 mg/kg (max 0.5 mg, 1:1000) into the lateral thigh IMMEDIATELY; repeat every 5 minutes as needed. Lie patient flat (legs raised); do NOT stand them up. High-flow oxygen, IV fluid bolus 20 mL/kg for hypotension. Adjuncts only after adrenaline: nebulised salbutamol for bronchospasm; antihistamines for skin symptoms only. Refractory: adrenaline infusion. Observe ≥4 hours (biphasic reactions); discharge with EpiPen, ASCIA action plan, and allergy referral.",
       "Stridor/tongue swelling (early intubation), hypotension despite two adrenaline doses, patients on beta-blockers (consider glucagon), biphasic recurrence after apparent recovery.",
       "AMC Pearl: IM adrenaline in the anterolateral thigh is ALWAYS the first drug — antihistamines and steroids never precede it. AMC Pearl: Standing a patient up during anaphylaxis can precipitate fatal empty-ventricle arrest; keep them supine.",
       [RCH, RACGP]),

    _t("Acute stroke", "Medicine",
       "Sudden focal neurological deficit of vascular origin: 85% ischaemic, 15% haemorrhagic. Time-critical reperfusion therapy makes recognition (FAST) and rapid imaging essential.",
       "Immediate non-contrast CT brain to exclude haemorrhage; CT angiography for large vessel occlusion (thrombectomy candidates); BSL (hypoglycaemia mimics). NIHSS quantifies severity. Determine 'last known well' time precisely.",
       "Ischaemic: IV thrombolysis (alteplase/tenecteplase) within 4.5h of onset if no contraindications and BP <185/110; endovascular thrombectomy for large vessel occlusion up to 24h in selected patients (perfusion imaging). Aspirin 24h after thrombolysis (immediately if no lysis). Stroke unit care for all. Haemorrhagic: reverse anticoagulation, BP lowering (target SBP ~140), neurosurgical referral. Secondary prevention: antiplatelets/anticoagulation (AF), statin, BP control, carotid endarterectomy for symptomatic 70-99% stenosis.",
       "Falling GCS (malignant MCA oedema, haemorrhage expansion), basilar occlusion (fluctuating brainstem signs), cerebellar stroke/haemorrhage (obstructive hydrocephalus — surgical), BP >185/110 blocking thrombolysis.",
       "AMC Pearl: CT first — never give antithrombotics until haemorrhage is excluded. AMC Pearl: Hypoglycaemia is the great stroke mimic; glucose is checked before the CT scanner.",
       [RACGP]),

    _t("Transient ischaemic attack", "Medicine",
       "Transient focal neurological deficit of vascular origin without infarction — a medical emergency heralding stroke (highest risk within 48 hours).",
       "Clinical diagnosis after the event; same-day investigations: ECG (AF), carotid imaging (Doppler/CTA), brain imaging (MRI with DWI preferred — many 'TIAs' show infarction), bloods, BP. ABCD2 informs urgency but high-risk features (AF, crescendo TIAs, anticoagulated patient, carotid territory symptoms) mandate immediate specialist assessment regardless.",
       "Start antiplatelet therapy immediately once haemorrhage excluded: aspirin 300 mg, then dual antiplatelet (aspirin + clopidogrel) for 21 days in high-risk TIA/minor stroke, then single agent. AF: anticoagulate (DOAC). Carotid stenosis 70-99% symptomatic: endarterectomy within 2 weeks. Aggressive risk-factor control: statin, BP, diabetes, smoking. No driving per Austroads (private licence: 2-4 weeks minimum, per guideline).",
       "Crescendo TIAs (≥2 in a week), TIA on anticoagulation, AF with TIA, severe carotid stenosis — all need urgent (same-day) escalation.",
       "AMC Pearl: TIA work-up is same-day, not outpatient-in-a-month — early stroke risk approaches 5-10% in the first week. AMC Pearl: Remember driving restrictions — patients must be told and it must be documented.",
       [RACGP]),

    _t("First seizure (adult)", "Medicine",
       "A single unprovoked seizure does not equal epilepsy; the tasks are confirming it was a seizure, finding provokers, and counselling on driving and safety.",
       "History from witness is the key 'investigation': aura, tonic-clonic phases, lateral tongue bite, incontinence, post-ictal confusion (vs syncope: brief, pallor, rapid recovery, ± myoclonic jerks). Investigations: glucose, electrolytes (Na, Ca, Mg), ECG (arrhythmia/long QT mimics), drug/alcohol history, CT acutely (trauma, focal signs, anticoagulants) then MRI, EEG within days (yield highest early).",
       "Treat provoked causes (hypoglycaemia, hyponatraemia, alcohol withdrawal, drugs). Antiseizure medication is usually NOT started after a single unprovoked seizure unless high recurrence risk (epileptiform EEG, structural lesion, nocturnal seizure, focal deficit). If treating: valproate (males), levetiracetam or lamotrigine (women of childbearing potential). Safety advice: no driving (private car ~6 months seizure-free per Austroads), no swimming alone, shower not bath, heights/machinery precautions.",
       "Status epilepticus (>5 min: IV/IM benzodiazepine → levetiracetam/phenytoin → anaesthesia), seizure with fever/meningism, new focal deficit, head trauma, pregnancy (eclampsia), recurrent seizures same day.",
       "AMC Pearl: Driving cessation and documentation of that advice is a must-mention in every first-seizure station. AMC Pearl: Lateral tongue biting and prolonged post-ictal confusion best discriminate seizure from syncope.",
       [RACGP]),

    _t("Overdose management (general)", "Emergency",
       "Poisoning management rests on resuscitation, risk assessment (agent, dose, time, patient factors), supportive care, decontamination, antidotes, and enhanced elimination — guided by the Poisons Information Centre (13 11 26).",
       "Risk assessment: what, how much, when, co-ingestants (always check paracetamol level — frequently occult), intent. Investigations: paracetamol level at 4h, ECG (QRS >100 ms and tachycardia in TCA overdose; QT prolongation), VBG, BSL, electrolytes.",
       "Resuscitate first. Decontamination: activated charcoal 50 g if within ~1-2h and airway protected (useless/dangerous for metals, alcohols, corrosives). Antidotes: N-acetylcysteine (paracetamol, by nomogram), naloxone (opioids), sodium bicarbonate (TCA with wide QRS), flumazenil rarely (risk of seizures), atropine/pralidoxime (organophosphates), desferrioxamine (iron). Enhanced elimination: haemodialysis for toxic alcohols, lithium, salicylates, metformin lactic acidosis. All deliberate overdoses need psychiatric assessment before discharge.",
       "TCA overdose with QRS >100 ms (give bicarbonate, intubate early), paracetamol >150 mg/kg or staggered ingestion, falling GCS with unprotected airway, hyperthermia/serotonin syndrome, refusal of treatment with impaired capacity.",
       "AMC Pearl: A paracetamol level belongs in EVERY overdose work-up regardless of stated ingestant. AMC Pearl: NAC is virtually 100% protective when started within 8 hours of paracetamol ingestion — never delay it for a level beyond that window.",
       [RACGP]),

    _t("Abdominal aortic aneurysm", "Surgery",
       "Focal aortic dilatation ≥3 cm; risk of rupture rises steeply >5.5 cm. Risk factors: male sex, age, smoking, hypertension, family history.",
       "Often asymptomatic, found incidentally or by pulsatile expansile abdominal mass. Ultrasound for detection/surveillance; CT angiography for precise sizing and operative planning. Ruptured AAA triad: abdominal/back pain, hypotension, pulsatile mass (complete triad in minority — consider in any older man with collapse or 'renal colic').",
       "Surveillance (ultrasound): 3-4.5 cm 12-monthly, 4.5-5 cm 6-monthly, ≥5.0 refer vascular surgery; repair (EVAR or open) at ≥5.5 cm, rapid growth >1 cm/yr, or symptoms. Aggressive risk-factor management: smoking cessation (slows growth), BP control, statin/antiplatelet for cardiovascular risk. Ruptured: immediate vascular surgery — permissive hypotension (SBP ~80-100), massive transfusion, theatre; do not delay for CT if unstable with known AAA.",
       "Any new abdominal/back pain in a patient with known AAA (symptomatic = urgent repair assessment), tender aneurysm, hypotension/collapse — rupture until proven otherwise.",
       "AMC Pearl: First presentation of 'renal colic' in a man >60 is a ruptured AAA until excluded. AMC Pearl: Elective repair threshold is 5.5 cm (or symptoms/rapid growth) — smaller asymptomatic aneurysms get surveillance, not surgery.",
       [RACGP]),

    _t("Renal colic (urolithiasis)", "Surgery",
       "Calculi (most calcium oxalate) cause loin-to-groin colicky pain with microscopic haematuria. Lifetime prevalence ~10%; recurrence ~50% at 10 years.",
       "Sudden severe unilateral loin pain radiating to groin, restlessness, nausea; haematuria on dipstick (absent in ~15%). Non-contrast CT KUB is gold standard (size, site, obstruction); ultrasound first-line in pregnancy and young/recurrent patients. Check creatinine, exclude infection (urinalysis, ± cultures), beta-hCG in women.",
       "Analgesia: NSAIDs first-line (IV/PR/oral — as effective as opioids with fewer side effects); opioids second-line. Stones <5-6 mm: usually pass spontaneously — conservative management with strainer, fluids, ± alpha-blocker (tamsulosin) for distal stones 5-10 mm. Intervention (lithotripsy, ureteroscopy, PCNL) for: stones >10 mm, failure to pass/progress 4-6 weeks, intractable pain, obstruction with renal impairment. Prevention: fluids >2.5 L/day, dietary sodium and animal-protein moderation (NOT calcium restriction).",
       "Fever + obstructed stone (infected obstructed system — emergency decompression with nephrostomy or stent BEFORE definitive stone treatment), solitary kidney with obstruction, anuria, AKI.",
       "AMC Pearl: Sepsis with an obstructing stone = urgent decompression, not antibiotics alone — the highest-stakes answer in this topic. AMC Pearl: Dietary calcium restriction INCREASES stone risk; advise normal calcium with low salt instead.",
       [RACGP]),

    _t("Acute urinary retention", "Surgery",
       "Painful inability to void with a palpable/percussible bladder; in older men usually BPH-related, often precipitated by drugs, constipation, infection or alcohol.",
       "Clinical: suprapubic pain, distended dull bladder; bladder scan confirms volume (>500 mL typical). Assess precipitating causes (anticholinergics, opioids, alcohol, UTI, constipation), PR for prostate and masses, neurological screen (saddle sensation, lower-limb signs) for cauda equina. Check renal function and urine culture.",
       "Immediate urethral catheterisation (suprapubic if urethral impossible/contraindicated); record residual volume. Treat precipitants; start an alpha-blocker (tamsulosin) in men 24-48h before trial of void. Monitor for post-obstructive diuresis (>200 mL/hr — replace fluids) after high-pressure chronic retention with renal impairment. Failed trial of void or recurrent retention: urology referral (TURP consideration).",
       "Retention with back pain, saddle anaesthesia, leg weakness or lax anal tone (cauda equina — emergency MRI and decompression), haematuria with clot retention (3-way catheter washout), renal failure, frank sepsis.",
       "AMC Pearl: Painless retention with neurological symptoms is cauda equina until MRI proves otherwise. AMC Pearl: After relieving chronic retention, watch for post-obstructive diuresis and replace fluids — discharging these patients early is the trap.",
       [RACGP]),
]
