RACGP = {"name": "RACGP", "url": "https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-racgp-guidelines"}
RCH = {"name": "RCH", "url": "https://www.rch.org.au/clinicalguide/"}
RANZCOG = {"name": "RANZCOG", "url": "https://ranzcog.edu.au/womens-health/clinical-resources/"}
SA_HEALTH = {"name": "SA Health", "url": "https://sahealthlibrary.sa.gov.au/OandGguidelines"}
RCPSYCH = {"name": "RCPsych", "url": "https://www.rcpsych.ac.uk/mental-health"}


def _t(name, subject, summary, diagnosis, management, red_flags, pearls, sources):
    return {
        "topic_name": name, "subject": subject, "summary": summary, "diagnosis": diagnosis,
        "management": management, "red_flags": red_flags, "amc_pearls": pearls, "sources": sources,
    }


TOPICS_1 = [
    _t("Pre-eclampsia", "OBGYN",
       "Multisystem hypertensive disorder of pregnancy after 20 weeks gestation, defined by new hypertension plus evidence of maternal organ or uteroplacental dysfunction. A leading cause of maternal and perinatal morbidity in Australia.",
       "BP ≥140/90 on two occasions after 20 weeks plus one of: proteinuria (urine PCR ≥30 mg/mmol), creatinine >90 µmol/L, ALT/AST elevation, platelets <100, neurological features (headache, visual disturbance, hyperreflexia/clonus), or fetal growth restriction. Severe: BP ≥160/110.",
       "First-line antihypertensives: labetalol, methyldopa or nifedipine (target BP <160/110, ideally 110-140/85). Definitive treatment is delivery — timing balances gestation vs severity. MgSO4 for eclampsia prophylaxis when severe features. Aspirin 100-150 mg nocte from 12-16 weeks for high-risk women in subsequent pregnancies.",
       "BP ≥160/110, severe headache, visual disturbance, epigastric/RUQ pain, clonus, oliguria, pulmonary oedema, HELLP (haemolysis, elevated LFTs, low platelets), eclamptic seizure — all require urgent obstetric admission.",
       "AMC Pearl: Proteinuria is no longer mandatory for diagnosis — new hypertension + any end-organ feature suffices. AMC Pearl: Eclampsia first-line treatment is magnesium sulfate 4 g IV load then 1 g/hr infusion, NOT benzodiazepines.",
       [RANZCOG, SA_HEALTH]),

    _t("Gestational diabetes mellitus (GDM)", "OBGYN",
       "Glucose intolerance first recognised in pregnancy, screened universally at 24-28 weeks (earlier if risk factors). Increases risk of macrosomia, shoulder dystocia, pre-eclampsia and later maternal type 2 diabetes.",
       "75 g 2-hour OGTT at 24-28 weeks. Diagnostic thresholds (any one): fasting ≥5.1, 1-hour ≥10.0, 2-hour ≥8.5 mmol/L. Early testing for high-risk women (previous GDM, BMI >30, PCOS, family history, high-risk ethnicity).",
       "First-line: medical nutrition therapy, exercise, and glucose self-monitoring (targets: fasting ≤5.0, 2-hr postprandial ≤6.7). Second-line: metformin and/or insulin if targets not met after 1-2 weeks. Growth scans third trimester; postpartum OGTT at 6-12 weeks.",
       "Fasting glucose persistently >5.5 despite diet, macrosomia or polyhydramnios on scan, pre-existing diabetes discovered in pregnancy (HbA1c ≥6.5%) — manage as overt diabetes with specialist team.",
       "AMC Pearl: GDM management starts with diet and lifestyle, not medication. AMC Pearl: Postnatal OGTT at 6-12 weeks (not HbA1c) is needed because pregnancy alters red-cell turnover; lifelong 1-3 yearly diabetes screening follows.",
       [RANZCOG, RACGP, SA_HEALTH]),

    _t("Wolff-Parkinson-White (WPW) syndrome", "Medicine",
       "Pre-excitation syndrome from an accessory atrioventricular pathway (bundle of Kent), predisposing to AVRT and, dangerously, rapid conduction of AF.",
       "Resting ECG: short PR interval (<120 ms), delta wave (slurred QRS upstroke), broad QRS. Symptomatic episodes of palpitations/syncope suggest AVRT. Pre-excited AF: irregular broad-complex tachycardia with varying QRS morphology.",
       "Orthodromic AVRT (regular narrow complex): vagal manoeuvres then IV adenosine. Pre-excited AF: AV-nodal blockers (adenosine, verapamil, beta-blockers, digoxin) are CONTRAINDICATED — use IV procainamide or synchronised DC cardioversion if unstable. Definitive: catheter ablation of the accessory pathway.",
       "Syncope, pre-excited AF with rapid ventricular response (risk of degeneration to VF), family history of sudden death — urgent cardiology/electrophysiology referral.",
       "AMC Pearl: In AF with WPW, AV-node blockers funnel conduction down the accessory pathway and can precipitate VF — the classic exam trap. AMC Pearl: Unstable tachyarrhythmia of any mechanism = synchronised DC cardioversion.",
       [RACGP]),

    _t("Asthma (adult)", "Medicine",
       "Chronic inflammatory airway disease with variable expiratory airflow limitation. Australian management follows a stepwise approach with inhaled corticosteroid-based therapy central from the outset.",
       "Clinical pattern of wheeze, cough, chest tightness plus variable airflow limitation: spirometry showing FEV1/FVC below normal with bronchodilator reversibility (FEV1 increase ≥12% and ≥200 mL). PEF variability supports diagnosis.",
       "First-line for most adults: low-dose ICS-formoterol as anti-inflammatory reliever (AIR), or regular low-dose ICS plus SABA. Step up to maintenance-and-reliever (MART) then add LAMA/refer if uncontrolled. Acute severe attack: oxygen titrated to 93-95%, salbutamol via spacer or nebuliser, ipratropium, oral prednisolone 37.5-50 mg; IV magnesium for severe/life-threatening.",
       "Silent chest, exhaustion, cyanosis, SpO2 <92%, inability to speak, normal/raised CO2 in a distressed patient (impending respiratory failure) — ICU-level escalation.",
       "AMC Pearl: SABA-only treatment is no longer recommended for adults — anti-inflammatory reliever (ICS-formoterol) is preferred. AMC Pearl: A normalising pCO2 in acute severe asthma signals fatigue, not improvement.",
       [RACGP]),

    _t("Atrial fibrillation", "Medicine",
       "Most common sustained arrhythmia; irregularly irregular pulse with absent P waves. Major preventable cause of stroke.",
       "ECG: absent P waves, irregularly irregular RR intervals. Classify: paroxysmal, persistent, permanent. Assess stroke risk with CHA2DS2-VA and bleeding risk; check TSH, electrolytes, echo for structural disease.",
       "Rate control first-line for most: beta-blocker or non-dihydropyridine CCB (digoxin if sedentary/heart failure). Rhythm control (flecainide, amiodarone, DC cardioversion, ablation) for symptomatic/young/new-onset. Anticoagulation: DOAC first-line if CHA2DS2-VA ≥2 (consider at 1); warfarin if mechanical valve or moderate-severe mitral stenosis. If onset >48h or unknown: anticoagulate 3 weeks before elective cardioversion or TOE-guided.",
       "Haemodynamic instability (hypotension, ischaemic chest pain, acute heart failure, syncope) → immediate synchronised DC cardioversion. Rapid pre-excited AF → avoid AV-nodal blockers.",
       "AMC Pearl: DOACs are preferred over warfarin for non-valvular AF. AMC Pearl: Don't cardiovert stable AF of >48 hours without anticoagulation or TOE — stroke risk.",
       [RACGP]),

    _t("Infective endocarditis", "Medicine",
       "Infection of the endocardial surface, typically valves; subacute presentations are easily missed. Risk: prosthetic valves, prior IE, IVDU, rheumatic and congenital heart disease.",
       "Modified Duke criteria: positive blood cultures (typical organisms x2), echocardiographic vegetation/abscess/new regurgitation; minor — fever, vascular phenomena (Janeway lesions, septic emboli), immunological (Osler nodes, Roth spots, glomerulonephritis), risk factors. Three sets of blood cultures BEFORE antibiotics; TTE then TOE if suspicion persists.",
       "Empirical IV therapy after cultures (e.g. benzylpenicillin + flucloxacillin + gentamicin for native valve; add vancomycin if prosthetic/MRSA risk), then directed therapy 4-6 weeks. Surgery for heart failure from valve destruction, uncontrolled infection, abscess, recurrent emboli, fungal IE.",
       "New regurgitant murmur with fever, heart failure, conduction abnormalities (aortic root abscess), embolic stroke in a febrile patient, persistent bacteraemia despite therapy.",
       "AMC Pearl: Fever + new murmur = endocarditis until proven otherwise; take three blood culture sets before any antibiotics. AMC Pearl: S. aureus IE in an IV drug user is classically right-sided (tricuspid) with septic pulmonary emboli.",
       [RACGP]),

    _t("Sepsis", "Emergency",
       "Life-threatening organ dysfunction caused by a dysregulated host response to infection. Time-critical: each hour of delayed antibiotics in septic shock increases mortality.",
       "Suspected infection + acute organ dysfunction (SOFA increase ≥2): altered mentation, SBP <100, RR ≥22, lactate >2, oliguria, coagulopathy. Septic shock: vasopressors needed for MAP ≥65 plus lactate >2 despite fluids.",
       "Sepsis pathway within 60 minutes: take blood cultures x2, lactate, urine output; give broad-spectrum IV antibiotics per local protocol, 30 mL/kg crystalloid for hypotension/lactate ≥4, titrate oxygen. Reassess; noradrenaline first-line vasopressor if MAP <65 after fluids. Source control (drain abscess, remove line) early.",
       "Hypotension despite fluids, lactate ≥4, mottled skin, altered consciousness, neutropenia, no urine output — immediate senior/ICU escalation.",
       "AMC Pearl: Cultures before antibiotics, but never delay antibiotics beyond 60 minutes to get them. AMC Pearl: Lactate is the exam's favourite marker of occult hypoperfusion — normal BP does not exclude sepsis.",
       [RACGP, RCH]),

    _t("Bacterial meningitis", "Medicine",
       "Medical emergency: infection of the meninges, most commonly N. meningitidis and S. pneumoniae in adults. Classic triad (fever, neck stiffness, altered mental state) is absent in many.",
       "Lumbar puncture: turbid CSF, neutrophil pleocytosis, low glucose (CSF:serum <0.4), high protein, Gram stain/PCR. Blood cultures. CT before LP only if focal neurology, seizures, GCS <10, immunocompromise, or papilloedema.",
       "Do not delay antibiotics for LP: IV ceftriaxone 4 g (or 2 g bd) immediately; add benzylpenicillin/ampicillin if Listeria risk (age >50, immunocompromised, pregnant); add vancomycin if pneumococcal resistance risk. Dexamethasone 10 mg IV with/before first antibiotic dose. In the community with suspected meningococcal disease: IM/IV benzylpenicillin before urgent transfer. Notify public health; ciprofloxacin prophylaxis for close contacts of meningococcus.",
       "Petechial/purpuric non-blanching rash (meningococcaemia), rapidly falling GCS, seizures, shock, raised ICP signs — resuscitate and treat immediately.",
       "AMC Pearl: GP setting with fever + purpuric rash → give IM benzylpenicillin BEFORE transfer; this is a recurring AMC scenario. AMC Pearl: Meningococcal disease is notifiable and contacts need clearance antibiotics.",
       [RCH, RACGP]),

    _t("Acute appendicitis", "Surgery",
       "Commonest surgical abdominal emergency; luminal obstruction leads to inflammation, ischaemia and perforation. Classic migration of pain from periumbilical to RIF.",
       "Primarily clinical: RIF tenderness (McBurney's point), guarding, low-grade fever, anorexia; raised WCC/CRP. Ultrasound first-line in children/pregnancy/young women (also excludes gynae pathology); CT abdomen if diagnosis uncertain in adults. Always do beta-hCG in women of reproductive age.",
       "NBM, IV fluids, analgesia, IV antibiotics (e.g. ceftriaxone + metronidazole), and laparoscopic appendicectomy. Perforation with generalised peritonitis: resuscitation and urgent surgery. Appendix mass without peritonitis may be managed initially with antibiotics ± interval imaging to exclude malignancy.",
       "Generalised peritonitis (rigid abdomen), septic shock, pain out of proportion (consider ischaemia), elderly patient with vague symptoms — atypical presentations perforate more often.",
       "AMC Pearl: Analgesia does NOT mask the diagnosis — never withhold opioids pending surgical review. AMC Pearl: In any female with RIF pain, exclude ectopic pregnancy first with beta-hCG.",
       [RACGP]),

    _t("Bowel obstruction", "Surgery",
       "Mechanical blockage of intestinal transit. Small bowel: adhesions and hernias dominate; large bowel: colorectal cancer, volvulus, diverticular strictures.",
       "Colicky abdominal pain, vomiting (early in SBO, late/faeculent later), distension, absolute constipation. Examine hernial orifices and for surgical scars. AXR: dilated loops (SBO >3 cm central with valvulae; LBO >6 cm peripheral with haustra; caecum >9 cm critical). CT with contrast defines level, cause, and ischaemia.",
       "'Drip and suck': NBM, IV fluid resuscitation with electrolyte correction, nasogastric decompression, analgesia, antiemetics, urinary catheter for fluid balance. Adhesional SBO without compromise: trial of conservative management ± Gastrografin study. Surgery for strangulation, closed loop, ischaemia, irreducible hernia, or failure to resolve. Sigmoid volvulus: flexible sigmoidoscopic decompression.",
       "Constant (not colicky) pain, peritonism, fever, tachycardia, rising lactate — strangulation/ischaemia; caecal diameter >9 cm or closed-loop obstruction — perforation risk; both demand urgent surgery.",
       "AMC Pearl: Colicky pain that becomes constant signals strangulation — the key exam discriminator for operative management. AMC Pearl: Always examine the groin; an obstructed femoral hernia is a classic missed cause in elderly women.",
       [RACGP]),

    _t("Pulmonary embolism", "Medicine",
       "Thrombus (usually from leg/pelvic veins) occluding pulmonary arteries; presentation ranges from incidental to cardiac arrest.",
       "Wells score stratifies pre-test probability. PE unlikely: D-dimer — if negative, PE excluded. PE likely or positive D-dimer: CTPA (V/Q scan if contrast contraindicated or pregnancy after normal CXR). ECG: sinus tachycardia commonest; S1Q3T3 classic. Bedside echo (RV strain) in unstable patients.",
       "Anticoagulation first-line: DOAC (apixaban or rivaroxaban) for most; LMWH in pregnancy and active cancer (or DOAC for many cancers now). Massive PE with hypotension: systemic thrombolysis (alteplase) unless contraindicated. Duration: 3 months for provoked; extended for unprovoked/recurrent after risk-benefit review.",
       "Hypotension/shock, syncope, RV strain with raised troponin (submassive), hypoxia despite oxygen — consider thrombolysis/ICU. In pregnancy, do not withhold imaging — untreated PE kills.",
       "AMC Pearl: A negative D-dimer in a low-probability patient safely excludes PE — no imaging needed. AMC Pearl: Massive PE with shock = thrombolysis; anticoagulation alone is insufficient.",
       [RACGP]),

    _t("Deep vein thrombosis", "Medicine",
       "Thrombosis of deep veins, usually lower limb; proximal DVTs embolise. Risk: surgery, immobility, malignancy, pregnancy, OCP/HRT, thrombophilia.",
       "Wells DVT score. Unlikely: D-dimer to exclude. Likely: compression ultrasound of proximal veins (whole-leg if available). Unilateral swelling >3 cm difference, pitting oedema, collateral veins support diagnosis.",
       "DOAC first-line (apixaban/rivaroxaban without lead-in LMWH). LMWH in pregnancy. Provoked: 3 months; unprovoked: at least 3-6 months then reassess. Compression stockings for symptom relief. Consider age-appropriate cancer screening for unprovoked DVT; do not routinely test thrombophilia.",
       "Phlegmasia cerulea dolens (massive swollen blue painful limb — vascular emergency), concurrent dyspnoea/chest pain (PE), iliofemoral extension.",
       "AMC Pearl: Unprovoked DVT in an older patient → check for occult malignancy with history, examination and age-appropriate screening, not a 'pan-scan'. AMC Pearl: Superficial thrombophlebitis near the saphenofemoral junction behaves like DVT and may need anticoagulation.",
       [RACGP]),

    _t("Acute coronary syndrome", "Medicine",
       "Spectrum of myocardial ischaemia from unstable angina through NSTEMI to STEMI, caused by atherosclerotic plaque rupture and thrombosis.",
       "ECG within 10 minutes of presentation; serial high-sensitivity troponin at 0 and 1-3 hours. STEMI: persistent ST elevation in contiguous leads or new LBBB. NSTEMI: troponin rise without ST elevation. Risk-stratify (GRACE/HEART).",
       "All ACS: aspirin 300 mg stat, P2Y12 inhibitor (ticagrelor/clopidogrel), anticoagulation (heparin/enoxaparin), GTN and opioid for pain, oxygen only if SpO2 <93%. STEMI: reperfusion — primary PCI within 90 minutes, or fibrinolysis if PCI unavailable within timeframe, then transfer. NSTEMI: angiography within 24-72 hours by risk. Secondary prevention: statin, beta-blocker, ACE inhibitor, dual antiplatelet 12 months, cardiac rehab.",
       "Ongoing pain with dynamic ECG changes, arrhythmia (VT/VF), cardiogenic shock, new murmur (papillary rupture/VSD), heart failure — escalate to cathlab/ICU.",
       "AMC Pearl: Routine oxygen is NOT given unless SpO2 <93% — hyperoxia worsens infarct. AMC Pearl: hs-troponin can be negative in the first hour — serial testing is mandatory before discharge.",
       [RACGP]),

    _t("STEMI management", "Emergency",
       "ST-elevation myocardial infarction: complete coronary occlusion requiring emergency reperfusion. 'Time is muscle'.",
       "Persistent ST elevation ≥1 mm in two contiguous limb leads or ≥2 mm in precordial leads, or new LBBB with typical symptoms. Posterior MI: ST depression V1-V3 with dominant R — do V7-V9. Right ventricular infarct: ST elevation in V4R with inferior STEMI.",
       "Primary PCI if achievable within 90 minutes of first medical contact (door-to-balloon). Otherwise fibrinolysis (tenecteplase) within 30 minutes if symptom onset <12 h and no contraindications, then routine transfer for angiography within 24 h (rescue PCI if no reperfusion at 60-90 min). Adjuncts: aspirin + ticagrelor/clopidogrel, anticoagulant, analgesia.",
       "Cardiogenic shock (urgent PCI regardless of delay), VF/VT arrest, complete heart block in inferior MI, mechanical complications day 3-7 (free wall rupture, VSD, acute MR). RV infarct: hypotension with clear lungs — give fluids, avoid nitrates.",
       "AMC Pearl: Inferior STEMI + hypotension + clear chest = RV infarction → IV fluids and NO GTN. AMC Pearl: In rural Australia where PCI is >90 minutes away, fibrinolysis then transfer is the correct answer.",
       [RACGP]),

    _t("Chronic heart failure", "Medicine",
       "Clinical syndrome of impaired cardiac filling or ejection; classified by LVEF into HFrEF (≤40%), HFmrEF and HFpEF. Common end-point of IHD and hypertension.",
       "Symptoms (dyspnoea, orthopnoea, PND, fatigue, oedema) + signs (raised JVP, displaced apex, S3, crepitations). NT-proBNP elevated; normal level makes HF unlikely. Echocardiography is essential to classify and find cause. CXR: cardiomegaly, congestion.",
       "HFrEF foundation quadruple therapy: ACE inhibitor/ARNI + beta-blocker (bisoprolol/carvedilol/metoprolol XL) + mineralocorticoid antagonist + SGLT2 inhibitor; loop diuretic for congestion symptoms. Titrate to target doses. Device therapy (ICD/CRT) for persistent LVEF ≤35%. HFpEF: manage comorbidities, diuretics, SGLT2 inhibitor. Acute pulmonary oedema: sit up, oxygen, IV furosemide, GTN if SBP >100, CPAP if needed.",
       "Hypotension with poor perfusion (cardiogenic shock), worsening renal function with congestion, syncope/VT, K+ >5.5 on RAAS blockade.",
       "AMC Pearl: All four pillars (ACEi/ARNI, BB, MRA, SGLT2i) improve survival in HFrEF; diuretics only relieve symptoms. AMC Pearl: Do not start/up-titrate beta-blockers during acute decompensation.",
       [RACGP]),

    _t("COPD", "Medicine",
       "Progressive, largely smoking-related airflow limitation that is not fully reversible. Diagnosis requires spirometry; management follows the COPD-X plan.",
       "Post-bronchodilator FEV1/FVC <0.7 confirms persistent airflow limitation in a patient with dyspnoea/chronic cough and risk factors. Severity by FEV1 %predicted. Assess exacerbation history and breathlessness (mMRC).",
       "COPD-X: Confirm with spirometry; Optimise function (SABA prn → LAMA or LABA → LAMA+LABA; add ICS only if repeated exacerbations + eosinophilia); Prevent deterioration (smoking cessation — the single most effective intervention, influenza/pneumococcal/COVID vaccination, pulmonary rehabilitation); manage eXacerbations: increase bronchodilators, prednisolone 30-50 mg 5 days, antibiotics if purulent sputum, controlled O2 targeting 88-92%, NIV for hypercapnic respiratory failure (pH <7.35).",
       "SpO2 <88% or rising CO2 with drowsiness, pH <7.35 (needs NIV), inability to speak, haemodynamic instability, failure of response to initial therapy.",
       "AMC Pearl: Titrate oxygen to 88-92% in COPD — uncontrolled high-flow O2 causes hypercapnic narcosis. AMC Pearl: Smoking cessation and pulmonary rehab alter the disease course; inhalers mainly alter symptoms.",
       [RACGP]),

    _t("Type 2 diabetes mellitus", "Medicine",
       "Progressive insulin resistance and beta-cell failure. Australian first-line management combines lifestyle change with metformin, with cardiorenal-protective agents prioritised early.",
       "Diagnosis: fasting glucose ≥7.0, random/2-hr OGTT ≥11.1 with symptoms, or HbA1c ≥6.5% (repeat to confirm if asymptomatic). Screen with AUSDRISK; annual screening of eyes, feet, kidneys (ACR, eGFR), lipids, BP.",
       "First-line: lifestyle modification + metformin. Second-line guided by comorbidity: SGLT2 inhibitor for cardiovascular/renal disease or heart failure; GLP-1 RA for atherosclerotic disease/obesity; otherwise sulfonylurea/DPP-4. Individualised HbA1c target, generally ≤7.0%. BP <140/90 (lower if tolerated), statin for most over 40, ACEi/ARB for albuminuria.",
       "HbA1c >10% with symptoms or ketosis (consider insulin ± exclude T1DM/LADA), foot ulcer with infection or ischaemia (urgent high-risk foot service), eGFR <30 (metformin contraindicated), recurrent severe hypoglycaemia.",
       "AMC Pearl: Metformin remains first-line, but SGLT2 inhibitors are added early when there is heart failure or CKD regardless of HbA1c. AMC Pearl: Stop metformin and SGLT2i during acute illness/dehydration ('sick day rules') to avoid lactic acidosis and euglycaemic DKA.",
       [RACGP]),

    _t("Hypothyroidism", "Medicine",
       "Thyroid hormone deficiency, in Australia most commonly autoimmune (Hashimoto's). Insidious: fatigue, weight gain, cold intolerance, constipation, menorrhagia, dry skin, bradycardia.",
       "Primary: TSH elevated with low free T4 (subclinical: high TSH, normal fT4). TPO antibodies support autoimmune aetiology. Secondary (pituitary): low/normal TSH with low fT4.",
       "Levothyroxine replacement, full dose (1.6 µg/kg) in young healthy patients; start low (25-50 µg) and titrate in elderly or ischaemic heart disease. Recheck TSH 6-8 weeks after dose changes; take on an empty stomach. Subclinical: treat if TSH >10, pregnant/planning pregnancy, or symptomatic with antibodies. In pregnancy requirements rise ~30% — increase dose and monitor each trimester.",
       "Myxoedema coma (hypothermia, bradycardia, reduced GCS — ICU, IV thyroxine ± hydrocortisone), associated adrenal insufficiency (give steroids BEFORE thyroxine), rapid replacement in elderly precipitating angina.",
       "AMC Pearl: If concurrent adrenal insufficiency is possible, hydrocortisone must precede thyroxine or you precipitate adrenal crisis. AMC Pearl: TSH is the screening and monitoring test of choice in primary disease.",
       [RACGP]),

    _t("Hyperthyroidism", "Medicine",
       "Thyrotoxicosis most commonly from Graves disease (TSH-receptor antibodies), toxic multinodular goitre, or thyroiditis. Weight loss, heat intolerance, tremor, palpitations, AF in the elderly.",
       "Suppressed TSH with raised fT4/fT3. TRAb positive in Graves; technetium uptake scan distinguishes Graves (diffuse), toxic nodule (focal) and thyroiditis (low uptake). Graves' eye disease is clinical.",
       "Symptom control: beta-blocker (propranolol). Definitive: carbimazole (first-line antithyroid drug, 12-18 months for Graves), radioactive iodine (avoid in active eye disease, pregnancy), or thyroidectomy. Thyroiditis is self-limiting — beta-blockade only. PTU first trimester of pregnancy, carbimazole thereafter.",
       "Thyroid storm (fever, tachyarrhythmia, delirium — ICU: propranolol, PTU, iodine after PTU, hydrocortisone), agranulocytosis on carbimazole (fever + sore throat → stop drug, urgent FBC), pregnancy.",
       "AMC Pearl: Any patient on carbimazole presenting with fever or sore throat needs an urgent FBC to exclude agranulocytosis — stop the drug first. AMC Pearl: Carbimazole is teratogenic in the first trimester; use PTU then switch.",
       [RACGP]),

    _t("Chronic kidney disease", "Medicine",
       "Reduced eGFR (<60) or evidence of kidney damage (albuminuria, structural) for ≥3 months. Diabetes and hypertension cause most cases in Australia; CKD multiplies cardiovascular risk.",
       "eGFR (CKD-EPI) and urine ACR on two occasions ≥3 months apart. Stage by eGFR (1-5) and albuminuria (A1-A3). Renal ultrasound for obstruction/structure; check FBC, Ca/PO4/PTH from stage 3b.",
       "Slow progression: BP control (ACEi/ARB first-line with albuminuria — target ≤130/80), SGLT2 inhibitor (renoprotective independent of diabetes), glycaemic control, statin, smoking cessation, avoid nephrotoxins (NSAIDs, contrast). Manage complications: anaemia (iron, ESA), CKD-MBD, acidosis (bicarbonate). Refer nephrology: eGFR <30, ACR >30 mg/mmol persistent, rapid decline (>5/yr), resistant hypertension.",
       "eGFR falling >5 mL/min/yr, K+ >6.0, pH <7.2, uraemic symptoms (pericarditis, encephalopathy — dialysis indications), pulmonary oedema unresponsive to diuretics.",
       "AMC Pearl: A small creatinine rise (<25%) after starting ACEi is expected — continue the drug; stop only for larger rises or hyperkalaemia. AMC Pearl: 'Sick day' withholding of SADMANS drugs (SGLT2i, ACEi, diuretics, metformin, ARB, NSAIDs, sulfonylureas) prevents AKI.",
       [RACGP]),

    _t("Urinary tract infection", "Medicine",
       "Spectrum from acute cystitis to pyelonephritis. In Australia, trimethoprim resistance is rising; therapy follows Therapeutic Guidelines/RACGP advice.",
       "Cystitis: dysuria, frequency, urgency, suprapubic pain; urine dipstick (nitrites, leucocytes) supports, MSU culture confirms (obtain in men, children, pregnancy, recurrent/complicated cases). Pyelonephritis: fever, loin pain, vomiting ± sepsis.",
       "Non-pregnant women, uncomplicated cystitis: trimethoprim 300 mg nocte 3 days, or nitrofurantoin 100 mg bd 5 days. Men: 7 days, investigate if recurrent. Pregnancy: treat ALL bacteriuria including asymptomatic (nitrofurantoin/cephalexin — avoid trimethoprim first trimester); test of cure. Pyelonephritis: mild — oral amoxicillin-clavulanate/ciprofloxacin; severe — IV gentamicin + amoxicillin, imaging if obstruction suspected.",
       "Sepsis, obstruction with infection (infected obstructed kidney = urological emergency, needs urgent decompression), pregnancy, male/recurrent UTIs (investigate), failure after 48h therapy.",
       "AMC Pearl: Asymptomatic bacteriuria is treated only in pregnancy (and before urological procedures). AMC Pearl: An obstructed infected kidney needs emergency nephrostomy/stent, not just antibiotics.",
       [RACGP]),

    _t("Pelvic inflammatory disease", "OBGYN",
       "Ascending infection of the upper genital tract (endometritis, salpingitis, tubo-ovarian abscess), commonly chlamydia, gonorrhoea, and anaerobes. Major cause of infertility and ectopic pregnancy.",
       "Clinical: lower abdominal pain + cervical motion tenderness or adnexal tenderness, ± fever, abnormal discharge/bleeding. Take NAAT for chlamydia/gonorrhoea, HVS, beta-hCG (exclude ectopic). Low threshold to treat — sequelae of missed PID outweigh overtreatment.",
       "Outpatient: ceftriaxone 500 mg IM single dose + doxycycline 100 mg bd 14 days + metronidazole 400 mg bd 14 days. Inpatient (severe, pregnancy, abscess, failed oral therapy): IV ceftriaxone + azithromycin + metronidazole. Contact tracing and treatment of partners; abstain until both treated. Remove IUD only if no improvement at 48-72h.",
       "Tubo-ovarian abscess (mass, swinging fevers — may need drainage), peritonitis, pregnancy with PID, failure to improve in 72h (re-image, consider laparoscopy).",
       "AMC Pearl: Cervical motion tenderness ('cervical excitation') in a sexually active woman = treat as PID empirically; do not wait for swab results. AMC Pearl: Always exclude ectopic pregnancy first — the two presentations overlap.",
       [RANZCOG, RACGP, SA_HEALTH]),

    _t("Ectopic pregnancy", "OBGYN",
       "Implantation outside the uterine cavity, 95% tubal. The most important cause of first-trimester maternal death — every woman with abdominal pain and a positive pregnancy test has an ectopic until proven otherwise.",
       "Positive beta-hCG with empty uterus on transvaginal ultrasound; adnexal mass ± free fluid. Serial hCG: suboptimal rise (<63% in 48h) suggests ectopic/failing pregnancy. Discriminatory zone ~1500-2000 IU: intrauterine sac should be visible above this.",
       "Unstable/ruptured: immediate resuscitation and laparoscopy/laparotomy (salpingectomy usual). Stable options — surgical (salpingectomy or salpingotomy if contralateral tube damaged); medical: methotrexate IM single dose if hCG <5000, no fetal heartbeat, mass <35 mm, no significant pain, reliable follow-up; expectant for falling hCG <1500. Anti-D for Rh-negative women having surgical management.",
       "Shoulder-tip pain, collapse/syncope, peritonism, haemodynamic instability — ruptured ectopic, theatre immediately. Avoid methotrexate if unable to follow up.",
       "AMC Pearl: After methotrexate, intercourse and pregnancy must be avoided for 3 months and follow-up hCG until negative is mandatory. AMC Pearl: Shoulder-tip pain in early pregnancy = haemoperitoneum irritating the diaphragm.",
       [RANZCOG, SA_HEALTH]),

    _t("Postpartum haemorrhage", "OBGYN",
       "Blood loss ≥500 mL after vaginal birth (≥1000 mL caesarean) or any loss causing compromise. Causes: the four Ts — Tone (70%), Trauma, Tissue, Thrombin.",
       "Clinical: measured blood loss, uterine tone, inspection for tears, placenta completeness, observations. Primary PPH within 24h; secondary 24h-12 weeks (retained products, endometritis).",
       "Simultaneous resuscitation and cause treatment: call for help, two large IV cannulae, crossmatch 4 units, fundal massage, empty bladder. Uterotonics ladder: oxytocin 5-10 IU IV then infusion → ergometrine (avoid in hypertension) → carboprost IM (avoid in asthma) → misoprostol. Tranexamic acid 1 g IV early. Repair trauma, remove retained tissue. Refractory: intrauterine balloon tamponade, B-Lynch suture, uterine artery ligation/embolisation, hysterectomy as last resort.",
       "Loss >1000 mL or any shock, ongoing trickle with rising HR, DIC (oozing from puncture sites), uterus boggy despite uterotonics — activate massive transfusion protocol.",
       "AMC Pearl: Atony is the cause until proven otherwise — fundal massage plus oxytocin is the universal first step. AMC Pearl: Ergometrine is contraindicated in pre-eclampsia/hypertension; carboprost in asthma.",
       [RANZCOG, SA_HEALTH]),

    _t("Shoulder dystocia", "OBGYN",
       "Obstetric emergency: anterior shoulder impacts behind the symphysis after delivery of the head. Risks fetal hypoxia, brachial plexus injury, fracture; maternal PPH and tears. Risk factors: macrosomia, GDM, obesity, previous dystocia — but most cases are unpredicted.",
       "Clinical: head delivers then retracts ('turtle-neck sign'), restitution fails, gentle traction does not deliver the anterior shoulder.",
       "Call for help, note the time, discourage pushing. HELPERR sequence: Help; Evaluate for episiotomy; Legs — McRoberts manoeuvre (hyperflex hips); Pressure — suprapubic (NOT fundal); Enter — internal rotation manoeuvres (Rubin II, Woods screw); Remove posterior arm; Roll to all-fours (Gaskin). Last resorts: cleidotomy, Zavanelli. Document times and manoeuvres; paired cord gases; neonatal review for brachial plexus injury.",
       "More than 5 minutes head-to-body interval (hypoxia risk), fetal bradycardia during manoeuvres, maternal haemorrhage post-delivery.",
       "AMC Pearl: McRoberts + suprapubic pressure resolves ~90% and is always the first manoeuvre sequence. AMC Pearl: Fundal pressure is contraindicated — it worsens impaction and risks uterine rupture.",
       [RANZCOG, SA_HEALTH]),

    _t("Febrile child (assessment)", "Paediatrics",
       "Fever is the commonest paediatric presentation; the task is identifying the febrile child with serious bacterial infection (UTI, pneumonia, meningitis, sepsis) among self-limiting viral illness.",
       "Age-stratified approach: ANY fever ≥38°C in an infant <3 months (especially <28 days) warrants urgent assessment ± full septic screen (FBC, cultures, urine SPA/catheter, ± LP, CXR). Older children: assess appearance (alert, perfusion, hydration, work of breathing), localising signs, urine if no focus. Traffic-light style risk assessment per RCH guidelines.",
       "Well child with clear viral focus: symptomatic care (fluids, paracetamol/ibuprofen for comfort, not fever phobia), safety-net advice and review. Infant <28 days with fever: admit, full septic screen, empirical IV antibiotics (e.g. amoxicillin + gentamicin or cefotaxime). 1-3 months: senior review, low threshold for screen. Any toxic-appearing child: sepsis pathway, IV/IO access, ceftriaxone, fluids.",
       "Non-blanching rash, lethargy/poor arousal, weak cry, mottled or cyanosed, capillary refill >3s, grunting, apnoea, bulging fontanelle, seizures, parental concern of 'not their child' — treat as serious infection.",
       "AMC Pearl: Height of fever and response to antipyretics do NOT discriminate serious from minor illness; appearance does. AMC Pearl: Fever without focus in a young child — always test the urine.",
       [RCH]),

    _t("Kawasaki disease", "Paediatrics",
       "Medium-vessel vasculitis of young children (peak 6 months-5 years); the leading cause of acquired heart disease in developed countries via coronary artery aneurysms.",
       "Fever ≥5 days plus ≥4 of: bilateral non-purulent conjunctivitis; oral changes (strawberry tongue, cracked lips); polymorphous rash; cervical lymphadenopathy >1.5 cm; extremity changes (erythema/oedema, later periungual desquamation). Incomplete KD: fever + 2-3 criteria + raised CRP/ESR — echo supports. No confirmatory test; exclude differentials.",
       "IVIG 2 g/kg single infusion within 10 days of onset (ideally ASAP) plus aspirin (initially anti-inflammatory dose, then low-dose antiplatelet for ≥6-8 weeks). Echocardiography at diagnosis, 1-2 weeks, and 6-8 weeks. Refractory fever 36h post-IVIG: second IVIG dose ± corticosteroids.",
       "Coronary aneurysms on echo, persistent fever after IVIG, myocarditis, shock (Kawasaki shock syndrome may mimic septic shock).",
       "AMC Pearl: One of the few paediatric indications where aspirin is deliberately used despite Reye syndrome concerns. AMC Pearl: Think Kawasaki in any child with fever ≥5 days unresponsive to antibiotics — delayed IVIG beyond day 10 markedly raises aneurysm risk.",
       [RCH]),
]
