# type: ignore
"""phase2: flashcard notes+difficulty, waitlist

Revision ID: 0ed655dcd75c
Revises: ffd399aa6191
Create Date: 2026-06-11 02:03:19.566463
"""
from alembic import op
import sqlalchemy as sa


revision = '0ed655dcd75c'
down_revision = 'ffd399aa6191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('plan_interest', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_email'), 'waitlist_entries', ['email'], unique=True)
    op.add_column('flashcards', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('flashcards', sa.Column('personal_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'personal_notes')
    op.drop_column('flashcards', 'difficulty')
    op.drop_index(op.f('ix_waitlist_entries_email'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    # ### end Alembic commands ###
